import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
import { ADMIN_APP_JS, PUBLIC_APP_JS } from "../lib/ui/client.mjs";

test("public client loads the pinned local Photo Sphere Viewer bundle only for approved HTTPS panorama markup", () => {
  const packageJson = JSON.parse(fs.readFileSync(new URL("../../package.json", import.meta.url), "utf8"));
  const bundle = new URL("../../public/vendor/photo-sphere-viewer.js", import.meta.url);
  const styles = new URL("../../public/vendor/photo-sphere-viewer.css", import.meta.url);
  const publicClient = new URL("../../public/vendor/ms-realty-public.js", import.meta.url);
  const adminClient = new URL("../../public/vendor/ms-realty-admin.js", import.meta.url);
  const designStyles = new URL("../../public/vendor/ms-realty.css", import.meta.url);

  assert.equal(packageJson.dependencies["@photo-sphere-viewer/core"], "5.14.3");
  assert.equal(fs.existsSync(bundle), true);
  assert.equal(fs.existsSync(styles), true);
  assert.equal(fs.existsSync(publicClient), true);
  assert.equal(fs.existsSync(adminClient), true);
  assert.equal(fs.existsSync(designStyles), true);
  assert.match(fs.readFileSync(bundle, "utf8"), /MSRealtyPhotoSphereViewer/);
  assert.equal(fs.readFileSync(publicClient, "utf8").endsWith(`${PUBLIC_APP_JS}\n`), true);
  assert.equal(fs.readFileSync(adminClient, "utf8").endsWith(`${ADMIN_APP_JS}\n`), true);
  assert.match(fs.readFileSync(designStyles, "utf8"), /^\/\* GENERATED/);
  assert.match(fs.readFileSync(designStyles, "utf8"), /data-mobile-sticky-actions/);
  assert.doesNotThrow(() => new Function(PUBLIC_APP_JS));
  assert.doesNotThrow(() => new Function(ADMIN_APP_JS));
  assert.match(PUBLIC_APP_JS, /PHOTO_SPHERE_VIEWER_SCRIPT_URL = "\/vendor\/photo-sphere-viewer\.js"/);
  assert.match(PUBLIC_APP_JS, /PHOTO_SPHERE_VIEWER_CSS_URL = "\/vendor\/photo-sphere-viewer\.css"/);
  assert.match(PUBLIC_APP_JS, /function loadPhotoSphereViewer/);
  assert.doesNotMatch(PUBLIC_APP_JS, /esm\.sh|jsdelivr/);
  assert.match(PUBLIC_APP_JS, /\[data-photo-sphere-viewer="psv-listing-tour"\]/);
  assert.match(PUBLIC_APP_JS, /data-panorama-url/);
  assert.match(PUBLIC_APP_JS, /function isApprovedPanoramaUrl/);
  assert.match(PUBLIC_APP_JS, /test\|example\|invalid\|localhost/);
  assert.match(PUBLIC_APP_JS, /keyboard: false/);
  assert.match(PUBLIC_APP_JS, /startKeyboardControl/);
  assert.match(PUBLIC_APP_JS, /data-photo-sphere-viewer-state", "fallback/);
  assert.match(PUBLIC_APP_JS, /navigationLink\.hidden = true/);
  assert.match(PUBLIC_APP_JS, /section\.hidden = true/);
  assert.match(PUBLIC_APP_JS, /function initImageFallbacks/);
  assert.match(PUBLIC_APP_JS, /main\[data-react-public-ui\] img, img\[data-fallback-src\]/);
  assert.match(PUBLIC_APP_JS, /data-image-state", "unavailable/);
  assert.match(PUBLIC_APP_JS, /function initMobileFilterPreview/);
  assert.match(PUBLIC_APP_JS, /window\.setTimeout\(preview, 320\)/);
  assert.match(PUBLIC_APP_JS, /x-ms-realty-preview": "search-count/);
  assert.match(PUBLIC_APP_JS, /initMobileFilterPreview\(\);/);
  assert.match(PUBLIC_APP_JS, /function initPublicMobileNavigation/);
  assert.match(PUBLIC_APP_JS, /initPublicMobileNavigation\(\);/);
  assert.match(PUBLIC_APP_JS, /function initSearchScrollRestoration/);
  assert.match(PUBLIC_APP_JS, /sessionStorage\.setItem\(SEARCH_SCROLL_KEY/);
  assert.match(PUBLIC_APP_JS, /entries\[0\]\.type === "back_forward"/);
  assert.match(PUBLIC_APP_JS, /focus\(\{ preventScroll: true \}\)/);
  assert.match(PUBLIC_APP_JS, /function initDialogFocusReturn/);
  assert.match(PUBLIC_APP_JS, /function showToast/);
  assert.match(PUBLIC_APP_JS, /function copyShareUrl/);
  assert.match(PUBLIC_APP_JS, /error\.name !== "AbortError"/);
  assert.match(PUBLIC_APP_JS, /data-request-success/);
  assert.match(PUBLIC_APP_JS, /form\.getAttribute\("data-success-message"\)/);
  assert.match(PUBLIC_APP_JS, /note\.focus\(\)/);
  assert.match(PUBLIC_APP_JS, /submit\.disabled = true/);
  assert.match(PUBLIC_APP_JS, /submit\.setAttribute\("aria-busy", "true"\)/);
  assert.match(PUBLIC_APP_JS, /warn\.focus\(\{ preventScroll: true \}\)/);
  assert.match(PUBLIC_APP_JS, /prefers-reduced-motion: reduce/);
  assert.match(PUBLIC_APP_JS, /warn\.scrollIntoView\(\{ block: "nearest", behavior: reduceMotion \? "auto" : "smooth" \}\)/);
  assert.match(PUBLIC_APP_JS, /data-saved-listings-view/);
  assert.match(PUBLIC_APP_JS, /data-saved-listings-ready/);
  assert.match(PUBLIC_APP_JS, /data-saved-navigation-label/);
  assert.match(PUBLIC_APP_JS, /savedViewFocus\.focus\(\)/);
  assert.match(PUBLIC_APP_JS, /event\.key === KEY/);
  assert.match(PUBLIC_APP_JS, /img\[data-fallback-src\]/);
  assert.match(PUBLIC_APP_JS, /function initMobileListingGallery/);
  assert.match(PUBLIC_APP_JS, /data-mobile-gallery-current/);
  assert.match(PUBLIC_APP_JS, /progress\.setAttribute\("aria-label"/);
  assert.match(PUBLIC_APP_JS, /getBoundingClientRect\(\)/);
  assert.match(PUBLIC_APP_JS, /gallery\.addEventListener\("scroll", scheduleGalleryPosition, \{ passive: true \}\)/);
  assert.match(PUBLIC_APP_JS, /initMobileListingGallery\(\);/);
  assert.match(PUBLIC_APP_JS, /data-mobile-contact-options-open/);
  assert.match(PUBLIC_APP_JS, /leadOptionsDialog\.close\(\)/);
  assert.match(PUBLIC_APP_JS, /callbackTime\.required = intent === "callback"/);
  assert.match(PUBLIC_APP_JS, /getTimezoneOffset\(\)/);
  assert.match(PUBLIC_APP_JS, /function useSameOriginHistoryBack/);
  assert.match(PUBLIC_APP_JS, /previous\.origin !== window\.location\.origin/);
  assert.match(PUBLIC_APP_JS, /window\.history\.back\(\)/);
  assert.match(PUBLIC_APP_JS, /addEventListener\("pagehide"/);
});

test("admin client enhances the reviewed 360 form without disabling lead queue filters", () => {
  assert.match(ADMIN_APP_JS, /initLeadQueueFilters\(\);/);
  assert.match(ADMIN_APP_JS, /initLeadPipelineFilters\(\);/);
  assert.match(ADMIN_APP_JS, /initTourEditor\(\);/);
  assert.match(ADMIN_APP_JS, /data-tour-editor-form/);
  assert.match(ADMIN_APP_JS, /function tourPayload/);
  assert.match(ADMIN_APP_JS, /credentials: "same-origin"/);
  assert.match(ADMIN_APP_JS, /payload\.is_public !== true/);
  assert.match(ADMIN_APP_JS, /data-tour-review-status", "available/);
});

test("public client has no Hermes chat surface", () => {
  assert.doesNotMatch(PUBLIC_APP_JS, /submitHermesChat|data-hermes-chat-form|hermes_public_chat|\/api\/hermes\/chat/);
  assert.doesNotMatch(PUBLIC_APP_JS, /HERMES_API_KEY|HERMES_CHAT_COMPLETIONS_URL/);
});
