import assert from 'node:assert/strict';
import test from 'node:test';
import {initPublicSearchEvidence} from '../lib/ui/public-search-evidence-client.mjs';
import {searchEvidenceCopy,SearchEvidenceDialog} from '../lib/react-public-search-evidence.mjs';
import {h,renderStaticElement} from '../lib/react-static-html.mjs';
import {loadLocaleRegistry} from '../lib/locales.mjs';
import {searchPath} from '../lib/seo.mjs';
import {SEARCH_INTENT_INPUT_FIELDS} from '../lib/search-request.mjs';
function node(tag='div'){return {tagName:tag.toUpperCase(),children:[],listeners:{},dataset:{},value:'',hidden:false,disabled:false,addEventListener(e,fn){this.listeners[e]=fn;},fire(e,target=this){return this.listeners[e]?.({target,preventDefault(){}});},replaceChildren(){this.children=[];},appendChild(n){this.children.push(n);},setAttribute(){},removeAttribute(){},focus(){this.focused=true;},getClientRects(){return[1];},reportValidity(){return true;},checkValidity(){return true;}};}
function harness(mode='match',kind='search',stored=null){
 const d=node('dialog'),result=node(),status=node(),change=node('form'),retry=node('button'),apply=node('button'),wishes=node(),close=node('button'),title=node('h2'),note=node(),reference=node(),criteria=node('dl'),button=node('button'),submit=node('button'),filters=node('form');
 d.dataset={locale:'en',kind,copy:JSON.stringify(searchEvidenceCopy('en')),labels:JSON.stringify({price_max:'Maximum price'}),fields:JSON.stringify(SEARCH_INTENT_INPUT_FIELDS),criteria:JSON.stringify({search_intent:{price_max:100000,property_families:['apartment']},nl_context:'quiet'}),searchPath:'/en/search'};
 const selectors={'[data-evidence-result]':result,'[data-evidence-status]':status,'[data-evidence-change]':change,'[data-evidence-retry]':retry,'[data-evidence-apply]':apply,'[data-evidence-wishes]':wishes,'[data-evidence-close]':close,'#pse-title':title,'[data-evidence-note]':note,'[data-evidence-reference]':reference,'[data-evidence-criteria]':criteria};
 d.querySelector=s=>selectors[s];d.showModal=()=>{d.open=true;};d.close=()=>{d.open=false;d.fire('close');};
 change.querySelector=()=>submit;change.elements={field:Object.assign(node('select'),{value:'price_max'}),value:Object.assign(node('input'),{value:'130000.25'}),family:node('select')};
 filters.values={price_max:'100000'};button.dataset={evidenceOpen:mode,listingId:mode==='match'?'MS-CRAWL-0003':''};
 const document={querySelector:()=>d,querySelectorAll:s=>s==='[data-evidence-open]'?[button]:[filters],createElement:node,addEventListener(){}};
 const requests=[],navigations=[],storage=new Map(stored?[['ms-realty:match-context',JSON.stringify(stored)]]:[]),sessionStorage={getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},location={origin:'http://local.test',search:'',assign:href=>navigations.push(href)};
 class FormData{constructor(f){this.f=f;}forEach(fn){Object.entries(this.f.values).forEach(([k,v])=>fn(v,k));}}
 new Function('document','location','sessionStorage','fetch','FormData',`(${initPublicSearchEvidence.toString()})();`)(document,location,sessionStorage,(url,options)=>new Promise(resolve=>requests.push({url,options,resolve})),FormData);button.fire('click');
 return{d,result,status,change,retry,apply,wishes,close,button,filters,requests,navigations,async respond(body,code=200,index=requests.length-1){requests[index].resolve({ok:code===200,status:code,json:async()=>body});await new Promise(resolve=>setImmediate(resolve));}};
}
const source={listing_id:'MS-CRAWL-0003',canonical_url:'/en/properties/MS-CRAWL-0003',reviewer:'Fixture reviewer',reviewed_at:'2026-09-01',source_hash:'a'.repeat(64)};
const match=(overrides={})=>({kind:'listing_match_explanation',locale:'en',listing_id:'MS-CRAWL-0003',applied:false,criteria:{price_max:100000},status:'incomplete',comparisons:[{field:'price_max',requested:100000,status:'unknown',evidence:null}],source,...overrides});
const alternative=(overrides={})=>({kind:'search_alternatives',locale:'en',applied:false,criteria:{price_max:100000},status:'preview',result_count:null,count_scope:'current_human_approved_source_records',alternatives:[{change:{field:'price_max',before:100000,after:130000.25},proposed_url:'/en/search?search_intent=reviewed',matching_reviewed_listings:2,source_examples:[source],applied:false,requires_confirmation:true}],...overrides});
function text(n){return [n.textContent||'',...n.children.map(text)].join(' ');}
test('match sends the actual selected listing and preserves unknown facts without a score',async()=>{const ui=harness();const sent=JSON.parse(ui.requests[0].options.body);assert.equal(sent.listingId,'MS-CRAWL-0003');assert.equal(sent.criteria.search_intent.price_max,100000);await ui.respond(match());assert.match(text(ui.result),/Not recorded/);assert.doesNotMatch(text(ui.result),/100%|within your budget/);assert.match(text(ui.result),/Fixture reviewer/);});
test('wrong listing receipts, unavailable sources, and changed versions show no comparisons',async()=>{for(const body of [match({listing_id:'MS-CRAWL-0001'}),match({status:'unavailable',comparisons:[],source:null}),match({status:'source_changed',comparisons:[]})]){const ui=harness();await ui.respond(body);assert.doesNotMatch(text(ui.result),/Not recorded|Matches the recorded fact/);assert.equal(ui.apply.disabled,true);}});
test('current filter edits and closing abort late comparisons',async()=>{for(const close of [false,true]){const ui=harness();if(close)ui.close.fire('click');else{ui.filters.values.price_max='80000';ui.filters.fire('input');}assert.equal(ui.requests[0].options.signal.aborted,true);await ui.respond(match());assert.equal(ui.result.children.length,0);}});
test('listing context is scoped to the exact selected ID and locale',()=>{for(const id of ['MS-CRAWL-0003','MS-CRAWL-0009']){const ui=harness('match','listing',{listingId:id,locale:'en',at:Date.now(),criteria:{price_max:777}});assert.deepEqual(JSON.parse(ui.requests[0].options.body).criteria,id==='MS-CRAWL-0003'?{price_max:777}:{});}});
test('alternative preview keeps reviewed-source counts separate and only navigates after apply',async()=>{const ui=harness('alternatives');await ui.respond(alternative());assert.equal(ui.navigations.length,0);assert.match(text(ui.result),/not a live result count/);assert.equal(ui.apply.disabled,false);ui.apply.fire('click');assert.equal(ui.navigations[0],'http://local.test/en/search?search_intent=reviewed');});
test('typed decimal preview changes one field and retains all other criteria',async()=>{const ui=harness('alternatives');await ui.respond(alternative({status:'no_supported_alternative',alternatives:[]}));ui.change.fire('submit');const body=JSON.parse(ui.requests[1].options.body);assert.deepEqual(body.change,{field:'price_max',value:130000.25});assert.deepEqual(body.criteria.search_intent.property_families,['apartment']);});
test('unavailable, invalid-count and unsafe alternative responses never enable apply',async()=>{for(const body of [alternative({status:'unavailable'}),alternative({result_count:42}),alternative({alternatives:[{...alternative().alternatives[0],proposed_url:'https://evil.invalid/search'}]})]){const ui=harness('alternatives');await ui.respond(body);assert.equal(ui.apply.disabled,true);ui.apply.fire('click');assert.equal(ui.navigations.length,0);}});
test('failed previews retain entered values for retry',async()=>{const ui=harness('alternatives');await ui.respond({},503);assert.equal(ui.change.elements.value.value,'130000.25');assert.equal(ui.retry.disabled,false);ui.retry.fire('click');assert.equal(ui.requests.length,2);});
test('seven locale evidence dialogs have named numeric and property controls',()=>{for(const locale of ['bg','en','ru','de','nl','el','he']){const html=renderStaticElement(h(SearchEvidenceDialog,{page:{kind:'search',locale,path:searchPath(loadLocaleRegistry(),locale),search:{intent:{}},chrome:{nav:[]}}}));assert.match(html,/aria-labelledby="pse-title"/);assert.match(html,/name="value" type="number" min="0" step="any" required/);assert.match(html,/data-evidence-apply[^>]*disabled/);assert.ok(searchEvidenceCopy(locale).countScope);assert.ok(html.includes('data-search-path="'+searchPath(loadLocaleRegistry(),locale)+'"'));}});
test('refresh detects a changed source before an explicit second refresh accepts new facts',async()=>{const ui=harness();await ui.respond(match());ui.retry.fire('click');assert.equal(JSON.parse(ui.requests[1].options.body).sourceHash,'a'.repeat(64));await ui.respond(match({status:'source_changed',comparisons:[],source:{...source,source_hash:'b'.repeat(64)}}));assert.match(ui.status.textContent,/listing changed/);ui.retry.fire('click');assert.equal(JSON.parse(ui.requests[2].options.body).sourceHash,undefined);});
test('a comparison carrying another listing source is refused',async()=>{const ui=harness();await ui.respond(match({comparisons:[{field:'price_max',requested:100000,status:'matched',evidence:{...source,listing_id:'MS-CRAWL-0009',value:1000}}]}));assert.equal(ui.result.children.length,0);assert.match(ui.status.textContent,/could not check/);});

test('invalid typed filters cannot silently become an unbounded comparison',async()=>{const ui=harness();await ui.respond(match());ui.filters.checkValidity=()=>false;ui.filters.fire('input');ui.retry.fire('click');assert.equal(ui.requests.length,1);assert.equal(ui.apply.disabled,true);assert.match(ui.status.textContent,/filters changed/);});
