/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    locales: Locale;
    listings: Listing;
    listing_translations: ListingTranslation;
    properties: Property;
    locations: Location;
    listing_enrichment_tasks: ListingEnrichmentTask;
    search_outbox: SearchOutbox;
    media_assets: MediaAsset;
    listing_tours: ListingTour;
    realty_cases: RealtyCase;
    realty_case_conditions: RealtyCaseCondition;
    realty_case_condition_events: RealtyCaseConditionEvent;
    realty_case_events: RealtyCaseEvent;
    realty_case_mandate_versions: RealtyCaseMandateVersion;
    realty_case_evidence: RealtyCaseEvidence;
    realty_case_outbox: RealtyCaseOutbox;
    public_leads: PublicLead;
    lead_contacts: LeadContact;
    funnel_events: FunnelEvent;
    provider_connections: ProviderConnection;
    provider_webhook_events: ProviderWebhookEvent;
    provider_delivery_receipts: ProviderDeliveryReceipt;
    viewings: Viewing;
    consent_events: ConsentEvent;
    seller_pipeline_events: SellerPipelineEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    locales: LocalesSelect<false> | LocalesSelect<true>;
    listings: ListingsSelect<false> | ListingsSelect<true>;
    listing_translations: ListingTranslationsSelect<false> | ListingTranslationsSelect<true>;
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    listing_enrichment_tasks: ListingEnrichmentTasksSelect<false> | ListingEnrichmentTasksSelect<true>;
    search_outbox: SearchOutboxSelect<false> | SearchOutboxSelect<true>;
    media_assets: MediaAssetsSelect<false> | MediaAssetsSelect<true>;
    listing_tours: ListingToursSelect<false> | ListingToursSelect<true>;
    realty_cases: RealtyCasesSelect<false> | RealtyCasesSelect<true>;
    realty_case_conditions: RealtyCaseConditionsSelect<false> | RealtyCaseConditionsSelect<true>;
    realty_case_condition_events: RealtyCaseConditionEventsSelect<false> | RealtyCaseConditionEventsSelect<true>;
    realty_case_events: RealtyCaseEventsSelect<false> | RealtyCaseEventsSelect<true>;
    realty_case_mandate_versions: RealtyCaseMandateVersionsSelect<false> | RealtyCaseMandateVersionsSelect<true>;
    realty_case_evidence: RealtyCaseEvidenceSelect<false> | RealtyCaseEvidenceSelect<true>;
    realty_case_outbox: RealtyCaseOutboxSelect<false> | RealtyCaseOutboxSelect<true>;
    public_leads: PublicLeadsSelect<false> | PublicLeadsSelect<true>;
    lead_contacts: LeadContactsSelect<false> | LeadContactsSelect<true>;
    funnel_events: FunnelEventsSelect<false> | FunnelEventsSelect<true>;
    provider_connections: ProviderConnectionsSelect<false> | ProviderConnectionsSelect<true>;
    provider_webhook_events: ProviderWebhookEventsSelect<false> | ProviderWebhookEventsSelect<true>;
    provider_delivery_receipts: ProviderDeliveryReceiptsSelect<false> | ProviderDeliveryReceiptsSelect<true>;
    viewings: ViewingsSelect<false> | ViewingsSelect<true>;
    consent_events: ConsentEventsSelect<false> | ConsentEventsSelect<true>;
    seller_pipeline_events: SellerPipelineEventsSelect<false> | SellerPipelineEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  name?: string | null;
  role: 'admin' | 'broker' | 'editor' | 'translator';
  /**
   * Workspaces this operator may access. Empty = admin-wide. Only admins may edit.
   */
  workspace_ids?: string[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locales".
 */
export interface Locale {
  id: number;
  code: string;
  native_name: string;
  admin_name: string;
  direction: 'ltr' | 'rtl';
  public_enabled?: boolean | null;
  indexable?: boolean | null;
  fallback_locale?: (number | null) | Locale;
  reviewer_owner?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: string;
  cms_status: 'source_imported_review_required' | 'draft' | 'review' | 'published' | 'archived';
  source_locale: number | Locale;
  source_domain: string;
  /**
   * URL field from migration manifest.
   */
  source_url: string;
  facts: {
    title?: string | null;
    h1?: string | null;
    description?: string | null;
    location?: string | null;
    location_native?: string | null;
    location_legacy?: string | null;
    municipality?: string | null;
    municipality_code?: string | null;
    district?: string | null;
    district_code?: string | null;
    region?: string | null;
    region_id?: string | null;
    country_code?: string | null;
    geography_id?: string | null;
    geography_path?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    settlement_ekatte?: string | null;
    location_review_status?: string | null;
    location_precision?: string | null;
    property_type?: string | null;
    offer_type?: string | null;
    listing_status?: ('available' | 'reserved' | 'sold' | 'rented' | 'archived') | null;
    bedrooms?: number | null;
    bedrooms_not_applicable?: boolean | null;
    price_eur?: number | null;
    price_on_request?: boolean | null;
    image_count?: number | null;
    area_sqm?: number | null;
    floor?: number | null;
    total_floors?: number | null;
    land_area_sqm?: number | null;
    condition?: string | null;
  };
  seo: {
    title?: string | null;
    description?: string | null;
    og_title?: string | null;
    og_description?: string | null;
    canonical?: string | null;
    canonical_override?: string | null;
    robots?: ('index,follow' | 'noindex,follow') | null;
    schema_present?: boolean | null;
  };
  workflow?: {
    availability_verified_at?: string | null;
    availability_verified_by?: string | null;
    location_verified_at?: string | null;
    location_verified_by?: string | null;
    price_verified_at?: string | null;
    price_verified_by?: string | null;
    price_on_request_verified_at?: string | null;
    price_on_request_verified_by?: string | null;
    publish_approved?: boolean | null;
    publish_approved_at?: string | null;
    publish_approved_by?: string | null;
    last_edited_at?: string | null;
    last_editor?: string | null;
    last_edit_event?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  property: string | Property;
  location?: (string | null) | Location;
  translations?: (number | ListingTranslation)[] | null;
  media?: (number | MediaAsset)[] | null;
  tour?: (number | null) | ListingTour;
  routing?: {
    target_path?: string | null;
    target_locale?: string | null;
    planned_status?: number | null;
    deployable?: boolean | null;
    review_required?: boolean | null;
  };
  migration?: {
    record_id?: string | null;
    review_state?: string | null;
    metadata_gaps?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: string;
  location?: (string | null) | Location;
  property_family?: ('apartment' | 'house' | 'plot' | 'agricultural_land' | 'commercial' | 'hotel') | null;
  property_subtype?: string | null;
  taxonomy_mapping_version: string;
  taxonomy_review_status: 'mapped' | 'mapping_review_required';
  facts: {
    legacy_property_type?: string | null;
    location_id?: string | null;
    location_label?: string | null;
    municipality?: string | null;
    district?: string | null;
    region_id?: string | null;
    country_code?: string | null;
    geography_id?: string | null;
    geography_path?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    condition?: string | null;
    construction_status?: string | null;
    parking_kind?: string | null;
    living_area_sqm?: number | null;
    built_area_sqm?: number | null;
    usable_area_sqm?: number | null;
    gross_floor_area_sqm?: number | null;
    land_area_sqm?: number | null;
    bedrooms_count?: number | null;
    premises_count?: number | null;
    hotel_room_count?: number | null;
    floor_number?: number | null;
    total_floors?: number | null;
    storeys_count?: number | null;
    zoning_status?: string | null;
    utilities_status?: string | null;
    road_access_status?: string | null;
    land_category?: string | null;
    permanent_use?: string | null;
    permitted_use?: string | null;
    public_location_precision?: string | null;
    primary_area_sqm?: number | null;
  };
  fact_verification: {
    field: string;
    state: 'unknown' | 'not_applicable' | 'entered_pending_review' | 'broker_verified';
    source_type?: string | null;
    source_reference?: string | null;
    id?: string | null;
  }[];
  zero_value_audit?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  legacy_listing_id: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: string;
  label: string;
  public_location_precision: 'exact' | 'approximate' | 'locality';
  internal_latitude?: number | null;
  internal_longitude?: number | null;
  public_latitude?: number | null;
  public_longitude?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing_translations".
 */
export interface ListingTranslation {
  id: number;
  listing: string | Listing;
  locale: number | Locale;
  source_locale: number | Locale;
  status: 'missing' | 'draft' | 'hermes_drafted' | 'human_edited' | 'approved' | 'published' | 'stale';
  translation_state: 'missing' | 'draft' | 'hermes_drafted' | 'human_edited' | 'approved' | 'published' | 'stale';
  source_hash: string;
  translated_hash: string;
  reviewer?: string | null;
  /**
   * Required before: approved, published
   */
  approved_at?: string | null;
  direction?: ('ltr' | 'rtl') | null;
  public_indexable?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_assets".
 */
export interface MediaAsset {
  id: number;
  /**
   * URL field from migration manifest.
   */
  url: string;
  /**
   * URL field from migration manifest.
   */
  asset_url?: string | null;
  alt?: string | null;
  width?: number | null;
  height?: number | null;
  kind: 'photo' | 'floor_plan' | 'site_chrome' | 'document' | 'unknown';
  is_public: boolean;
  review_status: 'approved_imported_photo' | 'reviewed_private' | 'review_required';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing_tours".
 */
export interface ListingTour {
  id: number;
  provider: 'photo-sphere-viewer' | 'supersplat-viewer';
  listing_id: string | Listing;
  /**
   * Required for approved Photo Sphere Viewer tours.
   */
  panorama_url?: string | null;
  /**
   * Required for approved SuperSplat Viewer tours.
   */
  viewer_url?: string | null;
  /**
   * URL field from migration manifest.
   */
  thumbnail_url?: string | null;
  hotspots: {
    value?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    id?: string | null;
  }[];
  is_public: boolean;
  /**
   * Required before: approved, published
   */
  accessibility_caption?: string | null;
  review_status: 'needs_panorama_upload' | 'needs_viewer_upload' | 'review_required' | 'approved' | 'published';
  fallback_gallery?:
    | {
        url?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing_enrichment_tasks".
 */
export interface ListingEnrichmentTask {
  id: string;
  listing: string | Listing;
  property: string | Property;
  task_type: 'verify_imported_facts';
  task_state: 'pending' | 'in_progress' | 'completed' | 'skipped';
  idempotency_key: string;
  fact_fields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  source: 'legacy_backfill' | 'listing_change';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_outbox".
 */
export interface SearchOutbox {
  id: string;
  listing?: (string | null) | Listing;
  event_type: 'upsert' | 'delete';
  outbox_state: 'pending' | 'processing' | 'completed' | 'failed';
  idempotency_key: string;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  attempts: number;
  last_error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realty_cases".
 */
export interface RealtyCase {
  id: number;
  /**
   * Tenant/workspace boundary. Never infer this from a case reference.
   */
  workspace_id: string;
  case_id: string;
  jurisdiction: 'BG' | 'GR';
  case_type:
    | 'buyer_purchase'
    | 'seller_sale'
    | 'tenant_rental'
    | 'landlord_rental'
    | 'short_term_rental'
    | 'property_management';
  asset_kind: 'residential' | 'commercial' | 'land' | 'new_build' | 'mixed_use';
  /**
   * Reference only.
   */
  client_ref: string;
  /**
   * Reference only.
   */
  property_ref?: string | null;
  execution_mode: 'manual' | 'autonomous';
  status: 'active' | 'frozen' | 'closed' | 'cancelled';
  /**
   * Reference only.
   */
  assurance_ref?: string | null;
  /**
   * Reference only.
   */
  mandate_ref: string;
  mandate_version_number: number;
  mandate_digest: string;
  workflow_version: string;
  /**
   * Immutable workflow snapshot captured when the case opens.
   */
  workflow_snapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  workflow_snapshot_digest: string;
  current_phase: string;
  progress_percent: number;
  last_event_sequence: number;
  last_event_id: string;
  last_event_action:
    | 'case_opened'
    | 'step_completed'
    | 'step_not_applicable'
    | 'step_blocked'
    | 'step_reopened'
    | 'mode_changed'
    | 'case_frozen'
    | 'case_resumed'
    | 'case_closed'
    | 'case_cancelled';
  last_event_at: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realty_case_conditions".
 */
export interface RealtyCaseCondition {
  id: number;
  /**
   * Tenant/workspace boundary. Never infer this from a case reference.
   */
  workspace_id: string;
  case: number | RealtyCase;
  condition_id: string;
  condition_type: string;
  due_at: string;
  /**
   * Reference-only JSON. Document content, files, and binary data are prohibited.
   */
  required_evidence_producer_refs:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'open' | 'satisfied' | 'blocked' | 'expired' | 'waived';
  /**
   * Reference-only JSON. Document content, files, and binary data are prohibited.
   */
  evidence_refs:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Reference only.
   */
  authority_ref?: string | null;
  reason_code?: string | null;
  last_event_sequence: number;
  last_event_id: string;
  last_event_action:
    | 'condition_opened'
    | 'condition_satisfied'
    | 'condition_blocked'
    | 'condition_expired'
    | 'condition_waived'
    | 'condition_reopened';
  last_event_at: string;
  /**
   * Reference only.
   */
  last_actor_ref: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realty_case_condition_events".
 */
export interface RealtyCaseConditionEvent {
  id: number;
  /**
   * Tenant/workspace boundary. Never infer this from a case reference.
   */
  workspace_id: string;
  case: number | RealtyCase;
  condition: number | RealtyCaseCondition;
  event_id: string;
  sequence: number;
  action:
    | 'condition_opened'
    | 'condition_satisfied'
    | 'condition_blocked'
    | 'condition_expired'
    | 'condition_waived'
    | 'condition_reopened';
  /**
   * Reference only.
   */
  actor_ref: string;
  executor_kind: 'human' | 'agent';
  /**
   * Reference only.
   */
  assurance_ref?: string | null;
  /**
   * Reference only.
   */
  authority_ref?: string | null;
  reason_code?: string | null;
  /**
   * Reference-only JSON. Document content, files, and binary data are prohibited.
   */
  reference_payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  payload_digest: string;
  idempotency_key: string;
  recorded_at: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realty_case_events".
 */
export interface RealtyCaseEvent {
  id: number;
  /**
   * Tenant/workspace boundary. Never infer this from a case reference.
   */
  workspace_id: string;
  case: number | RealtyCase;
  event_id: string;
  sequence: number;
  action:
    | 'case_opened'
    | 'step_completed'
    | 'step_not_applicable'
    | 'step_blocked'
    | 'step_reopened'
    | 'mode_changed'
    | 'case_frozen'
    | 'case_resumed'
    | 'case_closed'
    | 'case_cancelled';
  step_key?: string | null;
  /**
   * Reference only.
   */
  actor_ref: string;
  executor_kind: 'human' | 'agent';
  /**
   * Reference only.
   */
  assurance_ref?: string | null;
  /**
   * Reference only.
   */
  authority_ref?: string | null;
  reason_code?: string | null;
  /**
   * Reference-only JSON. Document content, files, and binary data are prohibited.
   */
  reference_payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  payload_digest: string;
  idempotency_key: string;
  recorded_at: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realty_case_mandate_versions".
 */
export interface RealtyCaseMandateVersion {
  id: number;
  /**
   * Tenant/workspace boundary. Never infer this from a case reference.
   */
  workspace_id: string;
  case: number | RealtyCase;
  /**
   * Reference only.
   */
  mandate_ref: string;
  version_number: number;
  /**
   * Immutable status at append time; the parent case identifies the current mandate version.
   */
  status: 'active' | 'superseded' | 'revoked' | 'expired';
  /**
   * Reference only.
   */
  granted_by_ref: string;
  signed_at: string;
  expires_at?: string | null;
  /**
   * Reference only.
   */
  signed_evidence_ref: string;
  /**
   * Reference-only JSON. Document content, files, and binary data are prohibited.
   */
  capabilities:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Reference-only JSON. Document content, files, and binary data are prohibited.
   */
  limits?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  mandate_digest: string;
  idempotency_key: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realty_case_evidence".
 */
export interface RealtyCaseEvidence {
  id: number;
  /**
   * Tenant/workspace boundary. Never infer this from a case reference.
   */
  workspace_id: string;
  case: number | RealtyCase;
  source_event?: (number | null) | RealtyCaseEvent;
  /**
   * Reference only.
   */
  evidence_ref: string;
  evidence_type:
    | 'identity_assertion'
    | 'registry_extract'
    | 'financial_confirmation'
    | 'inspection'
    | 'contract'
    | 'communication_receipt'
    | 'provider_receipt'
    | 'document_metadata'
    | 'other';
  producer_kind:
    | 'agency'
    | 'agent'
    | 'bank'
    | 'client'
    | 'counterparty'
    | 'engineer'
    | 'insurer'
    | 'lawyer'
    | 'notary'
    | 'property_manager'
    | 'registry'
    | 'system'
    | 'tax_authority'
    | 'vendor';
  /**
   * Reference only.
   */
  producer_ref?: string | null;
  issued_at?: string | null;
  digest: string;
  /**
   * Encrypted-vault reference only; no document content.
   */
  storage_ref?: string | null;
  mime_type?: string | null;
  retention_class: 'case_file' | 'legal_hold' | 'short_lived';
  verification_status: 'pending' | 'verified' | 'rejected' | 'expired' | 'revoked';
  /**
   * Reference only.
   */
  verification_ref?: string | null;
  /**
   * Reference-only JSON. Document content, files, and binary data are prohibited.
   */
  metadata_refs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realty_case_outbox".
 */
export interface RealtyCaseOutbox {
  id: number;
  /**
   * Tenant/workspace boundary. Never infer this from a case reference.
   */
  workspace_id: string;
  case: number | RealtyCase;
  source_event?: (number | null) | RealtyCaseEvent;
  outbox_id: string;
  idempotency_key: string;
  kind: 'provider_request' | 'communication' | 'calendar_task' | 'webhook' | 'reconciliation';
  /**
   * Provider or channel reference only.
   */
  destination_ref: string;
  /**
   * Reference-only JSON. Document content, files, and binary data are prohibited.
   */
  payload_refs:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  payload_digest: string;
  status: 'pending' | 'leased' | 'delivered' | 'failed' | 'dead_letter' | 'cancelled';
  not_before: string;
  lease_until?: string | null;
  attempt_count: number;
  last_attempt_at?: string | null;
  last_error_code?: string | null;
  delivered_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public_leads".
 */
export interface PublicLead {
  id: number;
  workspace_id: string;
  lead_id: string;
  idempotency_key?: string | null;
  received_at: string;
  source: string;
  intent?: string | null;
  lead_type: string;
  listing_reference?: string | null;
  original_language: string;
  admin_locale: string;
  contact_preference?: string | null;
  assigned_broker?: string | null;
  assignment_method?: string | null;
  contact_fingerprint?: string | null;
  duplicate_status?: string | null;
  possible_duplicate_of?: string | null;
  sla_due_at?: string | null;
  manager_escalation_due_at?: string | null;
  /**
   * The privacy-safe ledger row exactly as the JSONL ledger stores it. Never raw contact data.
   */
  ledger_row:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead_contacts".
 */
export interface LeadContact {
  id: number;
  workspace_id: string;
  subject_type: string;
  subject_id: string;
  stored_at: string;
  algorithm: string;
  iv: string;
  auth_tag: string;
  ciphertext: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "funnel_events".
 */
export interface FunnelEvent {
  id: number;
  event_id: string;
  recorded_at: string;
  type: string;
  path: string;
  locale: string;
  listing_reference?: string | null;
  action?: string | null;
  query?: string | null;
  filters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sort?: string | null;
  page?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provider_connections".
 */
export interface ProviderConnection {
  id: number;
  provider: string;
  status: string;
  connected_by: string;
  account_label?: string | null;
  external_account_id?: string | null;
  scopes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  credential_envelope:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  last_verified_at: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provider_webhook_events".
 */
export interface ProviderWebhookEvent {
  id: number;
  event_id: string;
  provider: string;
  event_type: string;
  external_event_id?: string | null;
  account_id?: string | null;
  received_at: string;
  payload_envelope:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provider_delivery_receipts".
 */
export interface ProviderDeliveryReceipt {
  id: number;
  idempotency_key: string;
  lead_id?: string | null;
  provider: string;
  status: string;
  approved_by: string;
  approved_at: string;
  started_at: string;
  completed_at?: string | null;
  external_message_id?: string | null;
  failure_code?: string | null;
  delivery_envelope:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "viewings".
 */
export interface Viewing {
  id: number;
  viewing_id: string;
  semantic_hash: string;
  lead_id: string;
  listing_reference?: string | null;
  original_language: string;
  admin_locale: string;
  broker: string;
  starts_at: string;
  booked_at: string;
  channel: string;
  status: string;
  follow_up_task_id: string;
  follow_up_owner: string;
  follow_up_status: string;
  follow_up_due_at: string;
  feedback_request_id: string;
  feedback_owner: string;
  feedback_status: string;
  feedback_due_at: string;
  feedback_channel: string;
  calendar_status: string;
  calendar_event_id?: string | null;
  calendar_synced_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent_events".
 */
export interface ConsentEvent {
  id: number;
  event_id: string;
  workspace_id: string;
  lead_id: string;
  recorded_at: string;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seller_pipeline_events".
 */
export interface SellerPipelineEvent {
  id: number;
  event_id: string;
  workspace_id: string;
  lead_id: string;
  recorded_at: string;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'locales';
        value: number | Locale;
      } | null)
    | ({
        relationTo: 'listings';
        value: string | Listing;
      } | null)
    | ({
        relationTo: 'listing_translations';
        value: number | ListingTranslation;
      } | null)
    | ({
        relationTo: 'properties';
        value: string | Property;
      } | null)
    | ({
        relationTo: 'locations';
        value: string | Location;
      } | null)
    | ({
        relationTo: 'listing_enrichment_tasks';
        value: string | ListingEnrichmentTask;
      } | null)
    | ({
        relationTo: 'search_outbox';
        value: string | SearchOutbox;
      } | null)
    | ({
        relationTo: 'media_assets';
        value: number | MediaAsset;
      } | null)
    | ({
        relationTo: 'listing_tours';
        value: number | ListingTour;
      } | null)
    | ({
        relationTo: 'realty_cases';
        value: number | RealtyCase;
      } | null)
    | ({
        relationTo: 'realty_case_conditions';
        value: number | RealtyCaseCondition;
      } | null)
    | ({
        relationTo: 'realty_case_condition_events';
        value: number | RealtyCaseConditionEvent;
      } | null)
    | ({
        relationTo: 'realty_case_events';
        value: number | RealtyCaseEvent;
      } | null)
    | ({
        relationTo: 'realty_case_mandate_versions';
        value: number | RealtyCaseMandateVersion;
      } | null)
    | ({
        relationTo: 'realty_case_evidence';
        value: number | RealtyCaseEvidence;
      } | null)
    | ({
        relationTo: 'realty_case_outbox';
        value: number | RealtyCaseOutbox;
      } | null)
    | ({
        relationTo: 'public_leads';
        value: number | PublicLead;
      } | null)
    | ({
        relationTo: 'lead_contacts';
        value: number | LeadContact;
      } | null)
    | ({
        relationTo: 'funnel_events';
        value: number | FunnelEvent;
      } | null)
    | ({
        relationTo: 'provider_connections';
        value: number | ProviderConnection;
      } | null)
    | ({
        relationTo: 'provider_webhook_events';
        value: number | ProviderWebhookEvent;
      } | null)
    | ({
        relationTo: 'provider_delivery_receipts';
        value: number | ProviderDeliveryReceipt;
      } | null)
    | ({
        relationTo: 'viewings';
        value: number | Viewing;
      } | null)
    | ({
        relationTo: 'consent_events';
        value: number | ConsentEvent;
      } | null)
    | ({
        relationTo: 'seller_pipeline_events';
        value: number | SellerPipelineEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  workspace_ids?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locales_select".
 */
export interface LocalesSelect<T extends boolean = true> {
  code?: T;
  native_name?: T;
  admin_name?: T;
  direction?: T;
  public_enabled?: T;
  indexable?: T;
  fallback_locale?: T;
  reviewer_owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings_select".
 */
export interface ListingsSelect<T extends boolean = true> {
  id?: T;
  cms_status?: T;
  source_locale?: T;
  source_domain?: T;
  source_url?: T;
  facts?:
    | T
    | {
        title?: T;
        h1?: T;
        description?: T;
        location?: T;
        location_native?: T;
        location_legacy?: T;
        municipality?: T;
        municipality_code?: T;
        district?: T;
        district_code?: T;
        region?: T;
        region_id?: T;
        country_code?: T;
        geography_id?: T;
        geography_path?: T;
        settlement_ekatte?: T;
        location_review_status?: T;
        location_precision?: T;
        property_type?: T;
        offer_type?: T;
        listing_status?: T;
        bedrooms?: T;
        bedrooms_not_applicable?: T;
        price_eur?: T;
        price_on_request?: T;
        image_count?: T;
        area_sqm?: T;
        floor?: T;
        total_floors?: T;
        land_area_sqm?: T;
        condition?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        og_title?: T;
        og_description?: T;
        canonical?: T;
        canonical_override?: T;
        robots?: T;
        schema_present?: T;
      };
  workflow?:
    | T
    | {
        availability_verified_at?: T;
        availability_verified_by?: T;
        location_verified_at?: T;
        location_verified_by?: T;
        price_verified_at?: T;
        price_verified_by?: T;
        price_on_request_verified_at?: T;
        price_on_request_verified_by?: T;
        publish_approved?: T;
        publish_approved_at?: T;
        publish_approved_by?: T;
        last_edited_at?: T;
        last_editor?: T;
        last_edit_event?: T;
      };
  property?: T;
  location?: T;
  translations?: T;
  media?: T;
  tour?: T;
  routing?:
    | T
    | {
        target_path?: T;
        target_locale?: T;
        planned_status?: T;
        deployable?: T;
        review_required?: T;
      };
  migration?:
    | T
    | {
        record_id?: T;
        review_state?: T;
        metadata_gaps?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing_translations_select".
 */
export interface ListingTranslationsSelect<T extends boolean = true> {
  listing?: T;
  locale?: T;
  source_locale?: T;
  status?: T;
  translation_state?: T;
  source_hash?: T;
  translated_hash?: T;
  reviewer?: T;
  approved_at?: T;
  direction?: T;
  public_indexable?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  id?: T;
  location?: T;
  property_family?: T;
  property_subtype?: T;
  taxonomy_mapping_version?: T;
  taxonomy_review_status?: T;
  facts?:
    | T
    | {
        legacy_property_type?: T;
        location_id?: T;
        location_label?: T;
        municipality?: T;
        district?: T;
        region_id?: T;
        country_code?: T;
        geography_id?: T;
        geography_path?: T;
        condition?: T;
        construction_status?: T;
        parking_kind?: T;
        living_area_sqm?: T;
        built_area_sqm?: T;
        usable_area_sqm?: T;
        gross_floor_area_sqm?: T;
        land_area_sqm?: T;
        bedrooms_count?: T;
        premises_count?: T;
        hotel_room_count?: T;
        floor_number?: T;
        total_floors?: T;
        storeys_count?: T;
        zoning_status?: T;
        utilities_status?: T;
        road_access_status?: T;
        land_category?: T;
        permanent_use?: T;
        permitted_use?: T;
        public_location_precision?: T;
        primary_area_sqm?: T;
      };
  fact_verification?:
    | T
    | {
        field?: T;
        state?: T;
        source_type?: T;
        source_reference?: T;
        id?: T;
      };
  zero_value_audit?: T;
  legacy_listing_id?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  id?: T;
  label?: T;
  public_location_precision?: T;
  internal_latitude?: T;
  internal_longitude?: T;
  public_latitude?: T;
  public_longitude?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing_enrichment_tasks_select".
 */
export interface ListingEnrichmentTasksSelect<T extends boolean = true> {
  id?: T;
  listing?: T;
  property?: T;
  task_type?: T;
  task_state?: T;
  idempotency_key?: T;
  fact_fields?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_outbox_select".
 */
export interface SearchOutboxSelect<T extends boolean = true> {
  id?: T;
  listing?: T;
  event_type?: T;
  outbox_state?: T;
  idempotency_key?: T;
  payload?: T;
  attempts?: T;
  last_error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_assets_select".
 */
export interface MediaAssetsSelect<T extends boolean = true> {
  url?: T;
  asset_url?: T;
  alt?: T;
  width?: T;
  height?: T;
  kind?: T;
  is_public?: T;
  review_status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing_tours_select".
 */
export interface ListingToursSelect<T extends boolean = true> {
  provider?: T;
  listing_id?: T;
  panorama_url?: T;
  viewer_url?: T;
  thumbnail_url?: T;
  hotspots?:
    | T
    | {
        value?: T;
        id?: T;
      };
  is_public?: T;
  accessibility_caption?: T;
  review_status?: T;
  fallback_gallery?:
    | T
    | {
        url?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realty_cases_select".
 */
export interface RealtyCasesSelect<T extends boolean = true> {
  workspace_id?: T;
  case_id?: T;
  jurisdiction?: T;
  case_type?: T;
  asset_kind?: T;
  client_ref?: T;
  property_ref?: T;
  execution_mode?: T;
  status?: T;
  assurance_ref?: T;
  mandate_ref?: T;
  mandate_version_number?: T;
  mandate_digest?: T;
  workflow_version?: T;
  workflow_snapshot?: T;
  workflow_snapshot_digest?: T;
  current_phase?: T;
  progress_percent?: T;
  last_event_sequence?: T;
  last_event_id?: T;
  last_event_action?: T;
  last_event_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realty_case_conditions_select".
 */
export interface RealtyCaseConditionsSelect<T extends boolean = true> {
  workspace_id?: T;
  case?: T;
  condition_id?: T;
  condition_type?: T;
  due_at?: T;
  required_evidence_producer_refs?: T;
  status?: T;
  evidence_refs?: T;
  authority_ref?: T;
  reason_code?: T;
  last_event_sequence?: T;
  last_event_id?: T;
  last_event_action?: T;
  last_event_at?: T;
  last_actor_ref?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realty_case_condition_events_select".
 */
export interface RealtyCaseConditionEventsSelect<T extends boolean = true> {
  workspace_id?: T;
  case?: T;
  condition?: T;
  event_id?: T;
  sequence?: T;
  action?: T;
  actor_ref?: T;
  executor_kind?: T;
  assurance_ref?: T;
  authority_ref?: T;
  reason_code?: T;
  reference_payload?: T;
  payload_digest?: T;
  idempotency_key?: T;
  recorded_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realty_case_events_select".
 */
export interface RealtyCaseEventsSelect<T extends boolean = true> {
  workspace_id?: T;
  case?: T;
  event_id?: T;
  sequence?: T;
  action?: T;
  step_key?: T;
  actor_ref?: T;
  executor_kind?: T;
  assurance_ref?: T;
  authority_ref?: T;
  reason_code?: T;
  reference_payload?: T;
  payload_digest?: T;
  idempotency_key?: T;
  recorded_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realty_case_mandate_versions_select".
 */
export interface RealtyCaseMandateVersionsSelect<T extends boolean = true> {
  workspace_id?: T;
  case?: T;
  mandate_ref?: T;
  version_number?: T;
  status?: T;
  granted_by_ref?: T;
  signed_at?: T;
  expires_at?: T;
  signed_evidence_ref?: T;
  capabilities?: T;
  limits?: T;
  mandate_digest?: T;
  idempotency_key?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realty_case_evidence_select".
 */
export interface RealtyCaseEvidenceSelect<T extends boolean = true> {
  workspace_id?: T;
  case?: T;
  source_event?: T;
  evidence_ref?: T;
  evidence_type?: T;
  producer_kind?: T;
  producer_ref?: T;
  issued_at?: T;
  digest?: T;
  storage_ref?: T;
  mime_type?: T;
  retention_class?: T;
  verification_status?: T;
  verification_ref?: T;
  metadata_refs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realty_case_outbox_select".
 */
export interface RealtyCaseOutboxSelect<T extends boolean = true> {
  workspace_id?: T;
  case?: T;
  source_event?: T;
  outbox_id?: T;
  idempotency_key?: T;
  kind?: T;
  destination_ref?: T;
  payload_refs?: T;
  payload_digest?: T;
  status?: T;
  not_before?: T;
  lease_until?: T;
  attempt_count?: T;
  last_attempt_at?: T;
  last_error_code?: T;
  delivered_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public_leads_select".
 */
export interface PublicLeadsSelect<T extends boolean = true> {
  workspace_id?: T;
  lead_id?: T;
  idempotency_key?: T;
  received_at?: T;
  source?: T;
  intent?: T;
  lead_type?: T;
  listing_reference?: T;
  original_language?: T;
  admin_locale?: T;
  contact_preference?: T;
  assigned_broker?: T;
  assignment_method?: T;
  contact_fingerprint?: T;
  duplicate_status?: T;
  possible_duplicate_of?: T;
  sla_due_at?: T;
  manager_escalation_due_at?: T;
  ledger_row?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead_contacts_select".
 */
export interface LeadContactsSelect<T extends boolean = true> {
  workspace_id?: T;
  subject_type?: T;
  subject_id?: T;
  stored_at?: T;
  algorithm?: T;
  iv?: T;
  auth_tag?: T;
  ciphertext?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "funnel_events_select".
 */
export interface FunnelEventsSelect<T extends boolean = true> {
  event_id?: T;
  recorded_at?: T;
  type?: T;
  path?: T;
  locale?: T;
  listing_reference?: T;
  action?: T;
  query?: T;
  filters?: T;
  sort?: T;
  page?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provider_connections_select".
 */
export interface ProviderConnectionsSelect<T extends boolean = true> {
  provider?: T;
  status?: T;
  connected_by?: T;
  account_label?: T;
  external_account_id?: T;
  scopes?: T;
  metadata?: T;
  credential_envelope?: T;
  last_verified_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provider_webhook_events_select".
 */
export interface ProviderWebhookEventsSelect<T extends boolean = true> {
  event_id?: T;
  provider?: T;
  event_type?: T;
  external_event_id?: T;
  account_id?: T;
  received_at?: T;
  payload_envelope?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provider_delivery_receipts_select".
 */
export interface ProviderDeliveryReceiptsSelect<T extends boolean = true> {
  idempotency_key?: T;
  lead_id?: T;
  provider?: T;
  status?: T;
  approved_by?: T;
  approved_at?: T;
  started_at?: T;
  completed_at?: T;
  external_message_id?: T;
  failure_code?: T;
  delivery_envelope?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "viewings_select".
 */
export interface ViewingsSelect<T extends boolean = true> {
  viewing_id?: T;
  semantic_hash?: T;
  lead_id?: T;
  listing_reference?: T;
  original_language?: T;
  admin_locale?: T;
  broker?: T;
  starts_at?: T;
  booked_at?: T;
  channel?: T;
  status?: T;
  follow_up_task_id?: T;
  follow_up_owner?: T;
  follow_up_status?: T;
  follow_up_due_at?: T;
  feedback_request_id?: T;
  feedback_owner?: T;
  feedback_status?: T;
  feedback_due_at?: T;
  feedback_channel?: T;
  calendar_status?: T;
  calendar_event_id?: T;
  calendar_synced_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent_events_select".
 */
export interface ConsentEventsSelect<T extends boolean = true> {
  event_id?: T;
  workspace_id?: T;
  lead_id?: T;
  recorded_at?: T;
  payload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seller_pipeline_events_select".
 */
export interface SellerPipelineEventsSelect<T extends boolean = true> {
  event_id?: T;
  workspace_id?: T;
  lead_id?: T;
  recorded_at?: T;
  payload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}