const en = {
  title: "Editorial content",
  new: "Create content",
  empty: "No content is available in your scope.",
  bg: "Bulgarian source text. Translations and indexing require their own approval; these pages remain noindex.",
  kind: "Content type",
  slug: "URL segment",
  pageTitle: "Page title",
  text: "Page text",
  paragraphs: "Separate paragraphs with a blank line. Plain text only.",
  jurisdiction: "Jurisdiction or geographic scope",
  scope: "Scope of professional review",
  save: "Save draft",
  saved: "Content change recorded",
  next: "Open the content workbench to review the exact edition.",
  open: "Open workbench",
  check: "Check action status",
  state: "Publication state",
  draft: "Working edition",
  live: "Published edition",
  preview: "Private draft preview",
  reviews: "Review decisions",
  reviewDate: "Professional review recorded at",
  missingReview: "Professional review has not been recorded for this edition.",
  claims: "Record qualified claim review",
  editorial: "Approve editorial text",
  publish: "Publish reviewed edition",
  withdraw: "Withdraw public page",
  note: "Review evidence or reason",
  expiry: "Approval valid until (UTC)",
  reviewed: "I reviewed this exact edition, its scope and this action.",
  sequence:
    "Qualified claim review creates an immutable reviewed edition. Editorial review and publication then bind that exact edition. Saving a draft leaves the existing published edition unchanged.",
  failed: "This change was not applied. Check your current access, required reviews and values.",
  conflict:
    "This content changed. Compare the current edition with your draft before applying it again.",
  retained: "Your draft is retained. Check the action before retrying.",
  statusMissing: "No completed action was found. Check the workbench before retrying.",
  validation: "Review these details.",
  invalid: "Check this value.",
  area: "Area",
  service: "Service",
  help: "Help or consent terms",
  back: "All content",
  public: "Open published page",
  none: "None",
  until: "Valid until",
};
type Copy = Record<keyof typeof en, string>;
const bg: Copy = {
  title: "Редакционно съдържание",
  new: "Ново съдържание",
  empty: "Няма съдържание в обхвата на правата ви.",
  bg: "Изходен текст на български. Преводът и индексирането изискват отделно одобрение; страниците остават noindex.",
  kind: "Вид съдържание",
  slug: "Сегмент на адреса",
  pageTitle: "Заглавие на страницата",
  text: "Текст на страницата",
  paragraphs: "Разделяйте абзаците с празен ред. Само обикновен текст.",
  jurisdiction: "Юрисдикция или географски обхват",
  scope: "Обхват на професионалния преглед",
  save: "Запазване на чернова",
  saved: "Промяната е записана",
  next: "Отворете съдържанието за преглед на точната версия.",
  open: "Към редактора",
  check: "Проверка на действието",
  state: "Състояние на публикацията",
  draft: "Работна версия",
  live: "Публикувана версия",
  preview: "Частен преглед на черновата",
  reviews: "Решения от преглед",
  reviewDate: "Професионален преглед от",
  missingReview: "За тази версия няма записан професионален преглед.",
  claims: "Запис на квалифициран преглед",
  editorial: "Одобряване на редакционния текст",
  publish: "Публикуване на прегледаната версия",
  withdraw: "Оттегляне на страницата",
  note: "Основание или доказателство за преглед",
  expiry: "Одобрението важи до (UTC)",
  reviewed: "Прегледах тази точна версия, обхвата и действието.",
  sequence:
    "Квалифицираният преглед създава неизменяема прегледана версия. Редакционното одобрение и публикуването се отнасят за нея. Черновата не променя текущата публикация.",
  failed: "Промяната не е приложена. Проверете правата, необходимите прегледи и данните.",
  conflict: "Съдържанието е променено. Сравнете текущата версия с черновата си.",
  retained: "Черновата е запазена. Проверете действието преди нов опит.",
  statusMissing: "Няма завършено действие. Проверете редактора преди нов опит.",
  validation: "Проверете данните.",
  invalid: "Проверете стойността.",
  area: "Район",
  service: "Услуга",
  help: "Помощ или условия за съгласие",
  back: "Всички страници",
  public: "Отваряне на публикацията",
  none: "Няма",
  until: "Важи до",
};
const ru: Copy = {
  title: "Редакционный контент",
  new: "Создать контент",
  empty: "В вашем доступе нет контента.",
  bg: "Исходный текст на болгарском. Переводы и индексация требуют отдельного одобрения; страницы остаются noindex.",
  kind: "Тип контента",
  slug: "Сегмент URL",
  pageTitle: "Заголовок страницы",
  text: "Текст страницы",
  paragraphs: "Разделяйте абзацы пустой строкой. Только обычный текст.",
  jurisdiction: "Юрисдикция или географический охват",
  scope: "Область профессиональной проверки",
  save: "Сохранить черновик",
  saved: "Изменение записано",
  next: "Откройте редактор для проверки точной версии.",
  open: "Открыть редактор",
  check: "Проверить действие",
  state: "Статус публикации",
  draft: "Рабочая версия",
  live: "Опубликованная версия",
  preview: "Закрытый просмотр черновика",
  reviews: "Решения проверки",
  reviewDate: "Профессиональная проверка от",
  missingReview: "Для этой версии профессиональная проверка не записана.",
  claims: "Записать квалифицированную проверку",
  editorial: "Одобрить редакционный текст",
  publish: "Опубликовать проверенную версию",
  withdraw: "Отозвать страницу",
  note: "Основание или доказательство проверки",
  expiry: "Одобрение действует до (UTC)",
  reviewed: "Я проверил точную версию, её область и это действие.",
  sequence:
    "Квалифицированная проверка создаёт неизменяемую проверенную версию. Редакционное одобрение и публикация привязаны к ней. Черновик не меняет существующую публикацию.",
  failed: "Изменение не применено. Проверьте права, обязательные проверки и данные.",
  conflict: "Контент изменился. Сравните текущую версию со своим черновиком.",
  retained: "Черновик сохранён. Проверьте действие перед повтором.",
  statusMissing: "Завершённого действия нет. Проверьте редактор перед повтором.",
  validation: "Проверьте данные.",
  invalid: "Проверьте значение.",
  area: "Район",
  service: "Услуга",
  help: "Помощь или условия согласия",
  back: "Все страницы",
  public: "Открыть публикацию",
  none: "Нет",
  until: "Действует до",
};
export const contentCopy = (locale: string): Copy =>
  locale === "bg" ? bg : locale === "ru" ? ru : en;
