// Staff interface drafts; BG is primary. No public language/indexing approval is implied.
const en = {
  title: "Butler draft assistance",
  source: "Included source",
  evidence: "Generation details",
  excluded:
    "Names, contact details, URLs, documents and other records are excluded. Check the minimized text before requesting a draft.",
  boundary:
    "This is a proposal for human review. Accepting a draft records your review only. Continue in the original inquiry to edit or take an ordinary action.",
  disabled: "Draft generation is unavailable. Continue the manual workflow.",
  task: "Draft task",
  inquiry_summary: "Summarize inquiry",
  reply_draft: "Propose a reply",
  task_draft: "Propose a next action",
  reviewedSource: "I reviewed the included source and its purpose.",
  reviewedDraft: "I checked the draft, source quotes and missing evidence.",
  request: "Request a draft",
  review: "Record review",
  decision: "Review decision",
  accepted: "Accept for manual use",
  rejected: "Reject draft",
  manual: "Open the inquiry",
  runs: "Recent draft requests",
  open: "Open draft status",
  changed:
    "The source changed. This draft cannot be accepted. Review the current inquiry and request a fresh draft.",
  draft: "Proposed text",
  warnings: "Missing or uncertain evidence",
  citations: "Source quotes",
  noOutput:
    "No usable draft is available yet. Refresh this page for the current outcome; your manual work is unaffected.",
  refresh: "Refresh status",
  failed:
    "Draft generation failed. The source record is unchanged; use the manual workflow or make a fresh reviewed request.",
  saved: "Request recorded",
  next: "Open the durable status to inspect the result.",
  check: "Check the current status",
  retained: "Your choices are retained. Review the current source before retrying.",
  status: "State",
  model: "Configured model",
  revision: "Source revision",
  digest: "Source digest",
  validation: "Validation",
  generated: "Generated at",
  costs: "Provider cost (USD micro-units)",
  unknown: "Unknown — reservation retained",
  noRuns: "No drafts recorded for this inquiry.",
  jobs: "Jobs and assistance status",
  queueUnavailable: "Queue status is unavailable; this is not evidence of an empty queue.",
  queueEmpty: "No retained jobs in these queues.",
  liveness:
    "Worker liveness is not instrumented. Queue rows show stored job state, not proof that a worker is currently online.",
  queue: "Queue",
  count: "Retained jobs",
  oldest: "Oldest recorded",
  checked: "Checked at",
  knownCost: "Recorded cost today",
  reservedCost: "Unresolved reservations today",
  limit: "Daily ceiling",
  enabled: "Enabled",
  off: "Disabled",
  denied: "This operation is not available with your current access.",
  operationMissing: "No completed request was found. Inspect recent requests before retrying.",
};
const bg: Record<keyof typeof en, string> = {
  title: "Чернови с Butler",
  source: "Включен източник",
  evidence: "Данни за генерирането",
  excluded:
    "Имена, контакти, URL адреси, документи и други записи са изключени. Проверете ограничените данни преди заявка.",
  boundary:
    "Това е предложение за човешки преглед. Приемането записва само прегледа ви. Продължете в запитването за редакция или обичайно действие.",
  disabled: "Генерирането не е достъпно. Продължете ръчно.",
  task: "Задача за чернова",
  inquiry_summary: "Обобщение на запитване",
  reply_draft: "Предложение за отговор",
  task_draft: "Предложение за следващо действие",
  reviewedSource: "Проверих включения източник и целта.",
  reviewedDraft: "Проверих черновата, цитатите и липсващите данни.",
  request: "Заявка за чернова",
  review: "Запис на прегледа",
  decision: "Решение",
  accepted: "Приемане за ръчно използване",
  rejected: "Отхвърляне",
  manual: "Към запитването",
  runs: "Последни заявки",
  open: "Статус на черновата",
  changed:
    "Източникът е променен. Черновата не може да се приеме. Прегледайте запитването и заявете нова чернова.",
  draft: "Предложен текст",
  warnings: "Липсващи или несигурни данни",
  citations: "Цитати от източника",
  noOutput:
    "Все още няма използваема чернова. Обновете за текущия резултат; ръчната работа е запазена.",
  refresh: "Обновяване",
  failed:
    "Генерирането е неуспешно. Източникът не е променен; продължете ръчно или заявете нова чернова след преглед.",
  saved: "Заявката е записана",
  next: "Отворете статуса за преглед на резултата.",
  check: "Проверка на статуса",
  retained: "Изборът ви е запазен. Проверете текущия източник преди нов опит.",
  status: "Състояние",
  model: "Конфигуриран модел",
  revision: "Версия на източника",
  digest: "Отпечатък на източника",
  validation: "Проверки",
  generated: "Генерирано на",
  costs: "Разход (микроединици USD)",
  unknown: "Неизвестен — резервът се пази",
  noRuns: "Няма чернови за това запитване.",
  jobs: "Задачи и статус на помощта",
  queueUnavailable: "Статусът на опашката не е достъпен; това не доказва празна опашка.",
  queueEmpty: "Няма съхранени задачи в тези опашки.",
  liveness:
    "Няма измерване на текущата работа на процеса. Записите показват съхранен статус, а не че процесът работи в момента.",
  queue: "Опашка",
  count: "Съхранени задачи",
  oldest: "Най-стар запис",
  checked: "Проверено на",
  knownCost: "Записан разход днес",
  reservedCost: "Неизяснен резерв днес",
  limit: "Дневен лимит",
  enabled: "Включено",
  off: "Изключено",
  denied: "Действието не е достъпно с текущите ви права.",
  operationMissing: "Няма завършена заявка. Проверете последните заявки преди нов опит.",
};
const ru: Record<keyof typeof en, string> = {
  title: "Черновики Butler",
  source: "Включённый источник",
  evidence: "Сведения о генерации",
  excluded:
    "Имена, контакты, URL, документы и другие записи исключены. Проверьте ограниченные данные перед запросом.",
  boundary:
    "Это предложение для проверки человеком. Принятие фиксирует только проверку. Для редактирования или обычного действия вернитесь к запросу.",
  disabled: "Генерация недоступна. Продолжите вручную.",
  task: "Задача черновика",
  inquiry_summary: "Обобщить запрос",
  reply_draft: "Предложить ответ",
  task_draft: "Предложить следующее действие",
  reviewedSource: "Я проверил включённый источник и цель.",
  reviewedDraft: "Я проверил черновик, цитаты и недостающие данные.",
  request: "Запросить черновик",
  review: "Записать проверку",
  decision: "Решение",
  accepted: "Принять для ручного использования",
  rejected: "Отклонить",
  manual: "Открыть запрос",
  runs: "Последние черновики",
  open: "Открыть статус",
  changed:
    "Источник изменился. Черновик нельзя принять. Проверьте текущий запрос и запросите новый черновик.",
  draft: "Предложенный текст",
  warnings: "Недостающие или неопределённые данные",
  citations: "Цитаты источника",
  noOutput: "Пригодного черновика пока нет. Обновите статус; ручная работа сохранена.",
  refresh: "Обновить статус",
  failed:
    "Генерация не удалась. Источник не изменён; продолжите вручную или запросите новую проверенную версию.",
  saved: "Запрос записан",
  next: "Откройте сохранённый статус для проверки результата.",
  check: "Проверить статус",
  retained: "Выбор сохранён. Проверьте текущий источник перед повтором.",
  status: "Состояние",
  model: "Настроенная модель",
  revision: "Версия источника",
  digest: "Отпечаток источника",
  validation: "Проверки",
  generated: "Создано",
  costs: "Расход (микроединицы USD)",
  unknown: "Неизвестен — резерв сохранён",
  noRuns: "Для этого запроса черновиков нет.",
  jobs: "Задания и статус помощи",
  queueUnavailable: "Статус очереди недоступен; это не означает, что очередь пуста.",
  queueEmpty: "В этих очередях нет сохранённых заданий.",
  liveness:
    "Работа процесса сейчас не измеряется. Записи отражают сохранённый статус, а не подтверждают доступность процесса.",
  queue: "Очередь",
  count: "Сохранённые задания",
  oldest: "Самая старая запись",
  checked: "Проверено",
  knownCost: "Записанный расход сегодня",
  reservedCost: "Неопределённый резерв сегодня",
  limit: "Дневной лимит",
  enabled: "Включено",
  off: "Выключено",
  denied: "Действие недоступно с текущими правами.",
  operationMissing: "Завершённый запрос не найден. Проверьте последние запросы перед повтором.",
};
export const aiCopy = (locale: string) => (locale === "bg" ? bg : locale === "ru" ? ru : en);
