const en = {
  title: "Explicit capability grants",
  lead: "Grant only the capability and scope this person needs. Affected staff sessions end and must sign in again. Role presets remain unchanged.",
  capability: "Capability",
  scope: "Record scope",
  global: "All records",
  recordId: "Record ID for a scoped grant",
  locale: "Locale restriction",
  allLocales: "All locales",
  expires: "Expiry date, if required",
  reason: "Reason and authorized purpose",
  grant: "Record capability grant",
  revoke: "Revoke this grant",
  existing: "Current staff grants",
  confirmation: "I reviewed the recipient, capability, scope and reason.",
  receipt: "Access change recorded",
  document: "Document",
  listing: "Listing",
  property: "Property",
  case: "Case",
};
export const grantManagementCopy = (locale: string) =>
  locale === "bg"
    ? {
        ...en,
        title: "Изрични права",
        lead: "Предоставете само нужните права и обхват. Сесиите на засегнатия служител се прекратяват и е нужен нов вход. Ролите не се променят.",
        capability: "Право",
        scope: "Обхват",
        global: "Всички записи",
        recordId: "ID на записа за ограничен обхват",
        locale: "Ограничение по език",
        allLocales: "Всички езици",
        expires: "Крайна дата, ако е нужна",
        reason: "Основание и разрешена цел",
        grant: "Предоставете правото",
        revoke: "Отменете това право",
        existing: "Текущи права на служителите",
        confirmation: "Прегледах получателя, правото, обхвата и основанието.",
        receipt: "Промяната на достъпа е записана",
        document: "Документ",
        listing: "Обява",
        property: "Имот",
        case: "Случай",
      }
    : locale === "ru"
      ? {
          ...en,
          title: "Явные права доступа",
          lead: "Предоставляйте только необходимые права и область доступа. Сеансы сотрудника завершаются; потребуется новый вход. Роли не изменяются.",
          capability: "Право",
          scope: "Область доступа",
          global: "Все записи",
          recordId: "ID записи для ограниченного доступа",
          locale: "Ограничение по языку",
          allLocales: "Все языки",
          expires: "Срок действия, если нужен",
          reason: "Основание и разрешённая цель",
          grant: "Предоставить право",
          revoke: "Отозвать это право",
          existing: "Текущие права сотрудников",
          confirmation: "Я проверил получателя, право, область и основание.",
          receipt: "Изменение доступа записано",
          document: "Документ",
          listing: "Объявление",
          property: "Объект",
          case: "Дело",
        }
      : en;
