const en = {
  title: "Save an attachment in the Case",
  lead: "Choose one attachment and its purpose. Import keeps it private and starts a malware check. Acceptance for the stated purpose requires a separate human review.",
  select: "Attachment",
  fileName: "Document filename",
  purpose: "Purpose",
  classification: "Document class",
  reason: "Why this attachment belongs in the Case",
  reviewed:
    "I checked this attachment's association with this Case and participant. Its contents still need review.",
  submit: "Import for scanning",
  documents: "Open Case documents",
  receipt: "Attachment import recorded",
  imported: "Imported attachments",
  pending: "Awaiting malware check",
  clean: "Malware check passed; consult the document's separate review",
  failed: "Malware check failed; file remains quarantined",
  infected: "Unsafe file; quarantined",
  unavailable:
    "Attachment import is not configured. Use the agency's approved document intake process.",
  denied: "Import requires current access to this Case and restricted documents.",
  reauth: "Confirm your sign-in to import or review attachments",
  closed: "This Case is closed. New imports require the Case to be reopened.",
  limit:
    "PDF, JPEG, PNG or WebP, up to 20 MB. A sender's filename and file type are unverified metadata.",
  service_agreement: "Service agreement",
  express_start: "Express start instruction",
  case_check: "Case check evidence",
  process_policy: "Process policy evidence",
  case_completion: "Agency outcome evidence",
  identity: "Identity",
  titleDocument: "Title / ownership evidence",
  financial: "Financial",
  contract: "Contract",
  property: "Property",
  other: "Other",
};
const bg: typeof en = {
  title: "Запазване на прикачен файл в делото",
  lead: "Изберете един файл и предназначението му. Импортът го запазва поверително и започва антивирусна проверка. Приемането за посочената цел изисква отделен преглед от служител.",
  select: "Прикачен файл",
  fileName: "Име на документа",
  purpose: "Предназначение",
  classification: "Клас на документа",
  reason: "Защо този файл принадлежи към делото",
  reviewed:
    "Проверих връзката на този файл с делото и участника. Съдържанието му подлежи на отделен преглед.",
  submit: "Импорт за сканиране",
  documents: "Отворете документите на делото",
  receipt: "Импортът е записан",
  imported: "Импортирани файлове",
  pending: "Очаква антивирусна проверка",
  clean: "Антивирусната проверка е успешна; вижте отделния преглед на документа",
  failed: "Антивирусната проверка не завърши; файлът остава под карантина",
  infected: "Небезопасен файл; под карантина",
  unavailable:
    "Импортът на прикачени файлове не е настроен. Използвайте одобрения процес на агенцията за приемане на документи.",
  denied: "Импортът изисква текущ достъп до делото и поверителните документи.",
  reauth: "Потвърдете входа си за импорт или преглед на файлове",
  closed: "Делото е приключено. За нов импорт първо го отворете отново.",
  limit:
    "PDF, JPEG, PNG или WebP, до 20 MB. Името и типът на файла от подателя са непроверени метаданни.",
  service_agreement: "Договор за услуга",
  express_start: "Изрично указание за начало",
  case_check: "Проверка по делото",
  process_policy: "Доказателство за процесна политика",
  case_completion: "Доказателство за резултата на агенцията",
  identity: "Самоличност",
  titleDocument: "Собственост",
  financial: "Финансов",
  contract: "Договор",
  property: "Имот",
  other: "Друго",
};
const ru: typeof en = {
  title: "Сохранить вложение в дело",
  lead: "Выберите один файл и его назначение. Импорт сохраняет его в закрытом доступе и запускает антивирусную проверку. Принятие для указанной цели требует отдельной проверки сотрудником.",
  select: "Вложение",
  fileName: "Имя документа",
  purpose: "Назначение",
  classification: "Класс документа",
  reason: "Почему вложение относится к этому делу",
  reviewed: "Я проверил связь вложения с делом и участником. Его содержание ещё требует проверки.",
  submit: "Импортировать для сканирования",
  documents: "Открыть документы дела",
  receipt: "Импорт вложения записан",
  imported: "Импортированные вложения",
  pending: "Ожидает антивирусной проверки",
  clean: "Антивирусная проверка пройдена; см. отдельную проверку документа",
  failed: "Антивирусная проверка не завершилась; файл остаётся в карантине",
  infected: "Небезопасный файл; в карантине",
  unavailable:
    "Импорт вложений не настроен. Используйте утверждённый процесс приёма документов агентства.",
  denied: "Для импорта нужен действующий доступ к делу и закрытым документам.",
  reauth: "Подтвердите вход для импорта или проверки вложений",
  closed: "Дело закрыто. Для нового импорта его нужно открыть повторно.",
  limit:
    "PDF, JPEG, PNG или WebP, до 20 МБ. Имя и тип файла от отправителя — непроверенные метаданные.",
  service_agreement: "Договор на услуги",
  express_start: "Указание о начале работ",
  case_check: "Проверка по делу",
  process_policy: "Подтверждение процессной политики",
  case_completion: "Подтверждение результата агентства",
  identity: "Удостоверение личности",
  titleDocument: "Право собственности",
  financial: "Финансовый",
  contract: "Договор",
  property: "Недвижимость",
  other: "Другое",
};
export const attachmentCopy = (locale: string) =>
  locale === "bg" ? bg : locale === "ru" ? ru : en;
