const en = {
  search: "Find a Case by reference or title",
  searchAction: "Find Case",
  next: "Next page",
  title: "Incoming email",
  lead: "Review untrusted incoming mail. A sender address or reply token does not prove identity or grant access.",
  empty: "No incoming emails.",
  waiting: "Receipts awaiting retrieval",
  from: "Claimed sender",
  subject: "Subject",
  body: "Plain-text message",
  noText:
    "No plain-text content. Assignment is unavailable; review through your approved mail process.",
  omitted: "HTML was omitted. Remote images and links were not fetched.",
  attachments: "Attachments — metadata only; unavailable until separate scanning and review",
  auth: "Provider authentication hints — not proof of the person's identity",
  select: "Choose a Case to review",
  choose: "Open Case context",
  case: "Case",
  party: "Current Case participant identified by your review",
  reason: "Reason and evidence for your decision",
  reviewed:
    "I reviewed the complete message and independently verified the Case and participant for assignment.",
  assign: "Record in Case — staff only",
  reject: "Reject from triage",
  triage: "Needs human review",
  assigned: "Recorded in Case — staff only",
  rejected: "Rejected from triage",
  receipt: "Decision recorded",
  error: "Decision not saved. Reload the current record, check your access and review again.",
  suggestion: "Possible Case from reply address — requires independent verification",
  back: "Back to incoming email",
  caseLink: "Open Case",
  review: "Review email",
  boundary: "This decision neither sends a reply nor gives the sender portal access.",
  state: "Status",
};
const bg: typeof en = {
  search: "Търсене на дело по номер или заглавие",
  searchAction: "Търсене на дело",
  next: "Следваща страница",
  title: "Входящи имейли",
  lead: "Прегледайте непроверените входящи писма. Адресът на подателя и кодът за отговор не доказват самоличност и не дават достъп.",
  empty: "Няма входящи писма.",
  waiting: "Получени събития, чакащи изтегляне",
  from: "Заявен подател",
  subject: "Тема",
  body: "Текст на писмото",
  noText:
    "Няма обикновен текст. Свързването е недостъпно; проверете писмото чрез одобрения процес за поща.",
  omitted: "HTML е пропуснат. Външни изображения и връзки не са изтегляни.",
  attachments: "Прикачени файлове — само метаданни; недостъпни до отделно сканиране и преглед",
  auth: "Данни за удостоверяване от доставчика — не доказват самоличност",
  select: "Изберете дело за преглед",
  choose: "Отворете контекста на делото",
  case: "Дело",
  party: "Текущ участник в делото, установен при прегледа",
  reason: "Причина и доказателства за решението",
  reviewed: "Прегледах цялото писмо и независимо проверих делото и участника за свързване.",
  assign: "Запис в делото — само за служители",
  reject: "Отхвърляне на писмото",
  triage: "Изисква човешки преглед",
  assigned: "Записано в делото — само за служители",
  rejected: "Отхвърлено",
  receipt: "Решението е записано",
  error: "Решението не е запазено. Заредете текущия запис, проверете достъпа и прегледайте отново.",
  suggestion: "Възможно дело по адреса за отговор — изисква независима проверка",
  back: "Към входящите писма",
  caseLink: "Отворете делото",
  review: "Преглед на писмото",
  boundary: "Решението не изпраща отговор и не дава достъп до портала.",
  state: "Състояние",
};
const ru: typeof en = {
  search: "Поиск дела по номеру или названию",
  searchAction: "Найти дело",
  next: "Следующая страница",
  title: "Входящие письма",
  lead: "Проверьте непроверенные входящие письма. Адрес отправителя и код ответа не подтверждают личность и не дают доступа.",
  empty: "Входящих писем нет.",
  waiting: "Полученные события ожидают загрузки",
  from: "Заявленный отправитель",
  subject: "Тема",
  body: "Текст письма",
  noText:
    "Обычного текста нет. Привязка недоступна; проверьте письмо через утверждённый почтовый процесс.",
  omitted: "HTML пропущен. Внешние изображения и ссылки не загружались.",
  attachments: "Вложения — только метаданные; недоступны до отдельной проверки",
  auth: "Данные проверки провайдера — не подтверждение личности",
  select: "Выберите дело для проверки",
  choose: "Открыть контекст дела",
  case: "Дело",
  party: "Текущий участник дела, установленный при проверке",
  reason: "Основание и доказательства решения",
  reviewed: "Я проверил всё письмо и независимо подтвердил дело и участника для привязки.",
  assign: "Записать в дело — только сотрудникам",
  reject: "Отклонить письмо",
  triage: "Нужна проверка сотрудника",
  assigned: "Записано в дело — только сотрудникам",
  rejected: "Отклонено",
  receipt: "Решение записано",
  error:
    "Решение не сохранено. Загрузите актуальную запись, проверьте доступ и повторите проверку.",
  suggestion: "Возможное дело по адресу ответа — нужна независимая проверка",
  back: "К входящим письмам",
  caseLink: "Открыть дело",
  review: "Проверить письмо",
  boundary: "Решение не отправляет ответ и не предоставляет доступ в кабинет.",
  state: "Статус",
};
export const inboundCopy = (locale: string) => (locale === "bg" ? bg : locale === "ru" ? ru : en);
