const en = {
  title: "Participants and access",
  lead: "You can ask the agency to invite or remove a participant. A request does not change access until an authorized staff member approves it.",
  staffLead:
    "Review client requests and manage access to this case. Invitation approval does not replace recipient acceptance.",
  approvedHint:
    "An approved invitation must also be accepted by its recipient before access begins.",
  invitationExpiry: "Invitation expires",
  roster: "Current participants",
  requests: "Access requests",
  invite: "Request an invitation",
  remove: "Request removal",
  revoke: "Revoke case access",
  email: "Recipient email",
  name: "Recipient name",
  role: "Requested role",
  reason: "Reason",
  target: "Participant",
  decision: "Decision",
  outcome: "Outcome shown to the requester",
  expires: "Access expires (Europe/Sofia)",
  expiryHint:
    "Required for specialists. This controls access duration; the invitation itself expires after 72 hours.",
  approve: "Approve",
  decline: "Decline",
  withdraw: "Withdraw request",
  save: "Record decision",
  pendingInvites: "Pending invitations",
  noExpiry: "No scheduled access expiry",
  back: "Open case",
  refresh: "Refresh status",
  empty: "No requests yet",
  requested: "Requested change",
  noAccess: "No new access has been granted.",
  roles: {
    buyer: "Buyer",
    seller: "Seller",
    tenant: "Tenant",
    landlord: "Landlord",
    collaborator: "Collaborator",
    adviser: "Adviser",
    guest: "Guest",
    specialist: "Specialist",
  },
  states: {
    pending: "Pending review",
    approved: "Approved",
    declined: "Declined",
    withdrawn: "Withdrawn",
    active: "Active",
    revoked: "Revoked",
    expired: "Expired",
    scheduled: "Scheduled",
  },
};
const bg: typeof en = {
  title: "Участници и достъп",
  lead: "Можете да поискате от агенцията да покани или премахне участник. Заявката не променя достъпа, докато упълномощен служител не я одобри.",
  staffLead:
    "Преглеждайте заявките на клиентите и управлявайте достъпа до случая. Одобрението на поканата не заменя приемането от получателя.",
  approvedHint: "Одобрената покана трябва да бъде приета от получателя, преди достъпът да започне.",
  invitationExpiry: "Поканата изтича",
  roster: "Текущи участници",
  requests: "Заявки за достъп",
  invite: "Заявка за покана",
  remove: "Заявка за премахване",
  revoke: "Отнемане на достъпа до случая",
  email: "Имейл на получателя",
  name: "Име на получателя",
  role: "Заявена роля",
  reason: "Причина",
  target: "Участник",
  decision: "Решение",
  outcome: "Резултат, видим за заявителя",
  expires: "Достъпът изтича (Europe/Sofia)",
  expiryHint:
    "Задължително за специалисти. Това е срокът на достъпа; самата покана изтича след 72 часа.",
  approve: "Одобряване",
  decline: "Отказ",
  withdraw: "Оттегляне на заявката",
  save: "Записване на решението",
  pendingInvites: "Чакащи покани",
  noExpiry: "Без насрочен срок на достъпа",
  back: "Отваряне на случая",
  refresh: "Обновяване на статуса",
  empty: "Все още няма заявки",
  requested: "Заявена промяна",
  noAccess: "Не е предоставен нов достъп.",
  roles: {
    buyer: "Купувач",
    seller: "Продавач",
    tenant: "Наемател",
    landlord: "Наемодател",
    collaborator: "Сътрудник",
    adviser: "Съветник",
    guest: "Гост",
    specialist: "Специалист",
  },
  states: {
    pending: "Очаква преглед",
    approved: "Одобрена",
    declined: "Отказана",
    withdrawn: "Оттеглена",
    active: "Активен",
    revoked: "Отнет",
    expired: "Изтекъл",
    scheduled: "Насрочен",
  },
};
const ru: typeof en = {
  title: "Участники и доступ",
  lead: "Вы можете попросить агентство пригласить или удалить участника. Запрос не меняет доступ, пока уполномоченный сотрудник не одобрит его.",
  staffLead:
    "Проверяйте запросы клиентов и управляйте доступом к делу. Одобрение приглашения не заменяет принятие получателем.",
  approvedHint: "Одобренное приглашение должно быть принято получателем до начала доступа.",
  invitationExpiry: "Приглашение истекает",
  roster: "Текущие участники",
  requests: "Запросы доступа",
  invite: "Запросить приглашение",
  remove: "Запросить удаление",
  revoke: "Отозвать доступ к делу",
  email: "Email получателя",
  name: "Имя получателя",
  role: "Запрашиваемая роль",
  reason: "Причина",
  target: "Участник",
  decision: "Решение",
  outcome: "Результат, видимый заявителю",
  expires: "Доступ истекает (Europe/Sofia)",
  expiryHint: "Обязательно для специалистов. Это срок доступа; само приглашение действует 72 часа.",
  approve: "Одобрить",
  decline: "Отклонить",
  withdraw: "Отозвать запрос",
  save: "Записать решение",
  pendingInvites: "Ожидающие приглашения",
  noExpiry: "Срок окончания доступа не задан",
  back: "Открыть дело",
  refresh: "Обновить статус",
  empty: "Запросов пока нет",
  requested: "Запрошенное изменение",
  noAccess: "Новый доступ не предоставлен.",
  roles: {
    buyer: "Покупатель",
    seller: "Продавец",
    tenant: "Арендатор",
    landlord: "Арендодатель",
    collaborator: "Соучастник",
    adviser: "Советник",
    guest: "Гость",
    specialist: "Специалист",
  },
  states: {
    pending: "Ожидает проверки",
    approved: "Одобрен",
    declined: "Отклонён",
    withdrawn: "Отозван",
    active: "Активен",
    revoked: "Отозван",
    expired: "Истёк",
    scheduled: "Запланирован",
  },
};
export const caseAccessCopy = (locale: string) =>
  locale === "bg" ? bg : locale === "ru" ? ru : en;
