export const workflowTypes = {
  emailDraft: "case.email.draft",
  emailApprove: "case.email.approve",
  create: "case.create_from_inquiry",
  next: "case.next_action",
  brief: "case.brief.revise",
  acknowledge: "case.brief.acknowledge",
  sellerBind: "case.seller.bind",
  ownerAcknowledge: "case.owner_preview.acknowledge",
  proposalRequest: "case.proposal.request",
  stage: "case.stage",
  disposition: "case.disposition",
  handover: "case.handover",
  interest: "case.interest.add",
  feedback: "case.interest.respond",
  message: "case.message.post",
  note: "case.message.post",
  request: "appointment.request",
  arrange: "appointment.arrange",
  appointment: "appointment.respond",
} as const;
export type WorkflowCommand = keyof typeof workflowTypes;
export const workflowFields: Record<WorkflowCommand, readonly string[]> = {
  emailDraft: ["subscriptionId", "subject", "body"],
  emailApprove: ["messageId", "messageVersion", "reviewHash", "reviewed"],
  create: ["kind", "title", "nextAction", "dueAt", "requirements", "preferences"],
  next: ["nextAction", "dueAt", "clientSummary"],
  brief: ["requirements", "preferences"],
  acknowledge: ["briefId", "reviewed"],
  sellerBind: ["instructionId", "reviewed", "reason"],
  ownerAcknowledge: ["reference", "previewHash", "reviewed"],
  proposalRequest: ["interestId", "reviewed"],
  stage: [
    "stage",
    "reason",
    "completionEvidenceId",
    "outcome",
    "retention",
    "aftercare",
    "handover",
  ],
  disposition: [
    "state",
    "reason",
    "waitingOn",
    "reviewAt",
    "outcome",
    "retention",
    "aftercare",
    "nextAction",
    "dueAt",
  ],
  handover: ["action", "receiverId", "reason", "reviewed", "snapshotHash"],
  interest: ["reference", "explanation"],
  feedback: ["state", "reason"],
  message: ["body", "reviewed"],
  note: ["body"],
  request: ["interestId", "preferredWindow", "participantPartyId"],
  arrange: [
    "action",
    "startsAt",
    "endsAt",
    "bufferMinutes",
    "propertyAccessConfirmed",
    "externalBusyChecked",
    "accessNotes",
  ],
  appointment: ["state", "reason"],
};
export const workflowScope = (command: WorkflowCommand, id: string) => `workflow.${command}.${id}`;
export const workflowStatus = (
  context: "staff" | "client",
  locale: string,
  command: WorkflowCommand,
  id: string,
  key: string,
) =>
  `/${locale}/${context === "staff" ? "cases" : "overview"}/operations?command=${command}&id=${encodeURIComponent(id)}&key=${encodeURIComponent(key)}`;
