// Private workspace copy; translated drafts require human review before catalog adoption.
const en = {
  cases: "Cases",
  proposals: "Proposals",
  documents: "Documents",
  prepareProposal: "Prepare a proposal",
  overview: "My cases",
  empty: "No cases are available to this account.",
  bounded: "Showing up to 50 recently updated cases you can access.",
  create: "Create a case",
  createLead:
    "Link this inquiry and its stated party explicitly. Seller authority remains self-declared. Requirements are recorded as the broker's interpretation until reviewed.",
  title: "Case title (visible to participants)",
  kind: "Purpose",
  buyer: "Buying",
  tenant: "Renting",
  seller: "Selling",
  landlord: "Letting",
  next: "Next internal action",
  due: "Next action due (UTC)",
  clientSummary: "Client-visible next action summary",
  requirements: "Requirements to review",
  preferences: "Preferences to review",
  brief: "Requirements",
  revise: "Record a new requirements revision",
  draftBrief: "Broker interpretation · client agreement has not been recorded",
  agreedBrief: "Client acknowledgment is recorded for this requirements revision",
  needsReview: "Requirements under review",
  tasks: "Open follow-up tasks",
  noTasks: "No open tasks are visible in this case for your current access.",
  moreTasks: "Open task list",
  nextSave: "Record next action",
  owned: "Accountable broker",
  noAction: "No client action summary has been recorded.",
  participants: "Current participants",
  authority: "Authority",
  interests: "Properties",
  addInterest: "Suggest a property",
  reference: "Listing reference",
  explanation: "Fit and known trade-offs (visible to participants)",
  noInterests: "No properties have been suggested yet.",
  stale: "The listing has changed since this assessment. Review current facts before deciding.",
  shortlist: "Shortlist",
  decline: "Decline",
  suggested: "Suggested",
  shortlisted: "Shortlisted",
  declined: "Declined",
  viewing_requested: "Viewing requested",
  viewed: "Viewed",
  proposal: "Proposal",
  unavailable: "Unavailable",
  feedback: "Feedback or reason",
  respond: "Record feedback",
  messages: "Conversation",
  message: "Message",
  internal: "Internal note · staff only",
  post: "Post in this case",
  note: "Save internal note",
  reviewPost:
    "I reviewed the audience and exact message. Make this available in the client workspace.",
  messageNote:
    "In-app messages are available in this case. Email delivery and read receipts are not implied.",
  noMessages: "No messages are available to this account in this case.",
  shared: "Case participants",
  appointments: "Appointments",
  calendar: "Calendar",
  request: "Request a viewing",
  preferredWindow: "Preferred window (not a confirmed booking)",
  participant: "Participating client",
  noAppointments: "No appointments are available in this scope.",
  calendarBounded: "Showing up to 100 recently updated appointments you can access.",
  requested: "Requested",
  proposed: "Proposed",
  confirmed: "Confirmed",
  reschedule_requested: "Change requested · existing confirmation remains in force",
  completed: "Completed",
  cancelled: "Cancelled",
  no_show: "No-show recorded",
  arrangement: "Arrange appointment",
  start: "Start in Sofia with UTC offset",
  end: "End in Sofia with UTC offset",
  offsetHint:
    "Use YYYY-MM-DDTHH:mm+03:00 in summer or +02:00 in winter. Invalid and ambiguous times need the correct explicit offset.",
  buffer: "Travel buffer before and after (minutes)",
  access: "I confirmed property access for this appointment",
  external: "I checked external busy periods for the host",
  logistics: "Private meeting/access instructions",
  action: "Action",
  propose: "Propose these times",
  confirm: "Confirm this arrangement",
  change: "Record appointment change",
  reason: "Reason or factual outcome",
  reschedule: "Request a different time",
  cancel: "Cancel appointment",
  complete: "Record completed attendance",
  noShow: "Record checked no-show",
  download: "Download calendar file",
  calendarNote:
    "The calendar file reflects the recorded arrangement. It does not send an invitation or confirm attendance.",
  confirmedTime: "Confirmed arrangement",
  previousTime: "Previous arrangement",
  proposedTime: "Proposed arrangement",
  requestNote: "Your preferred window is a request. Wait for an explicit confirmation.",
  policyNote:
    "Confirmation requires current listing availability, active participants, approved Sofia service hours, manual access/external-busy checks and free resources. No external calendar sync is claimed.",
  status: "Action status",
  statusAbsent: "No confirmed result was found. Check the current record before trying again.",
  statusFailed: "The action was not applied. Review the current record before retrying.",
  statusSaved: "The action was recorded.",
  statusUnknown:
    "The result is not confirmed. Keep this reference and check again before retrying.",
  back: "Open current record",
  saved: "Change recorded",
  nextStep: "Open the record to see its current state.",
  denied: "Your current access does not allow this action.",
  validation: "Review the highlighted details.",
  invalid: "Check this value.",
  conflict:
    "The record changed. Compare the current record with your retained draft before submitting a new action.",
  transition: "This step is not available. Check the current state and required evidence.",
  calendarConflict:
    "Another appointment already occupies this host or property's buffered interval. Choose another time.",
  scope: "Your current case access controls every record and action shown here.",
  requirementMessage:
    "Request a change to requirements in the conversation. This creates a visible request without silently rewriting the agreed record.",
};
type Copy = { [K in keyof typeof en]: string };
const bg: Copy = {
  ...en,
  cases: "Случаи",
  proposals: "Предложения",
  documents: "Документи",
  prepareProposal: "Подготовка на предложение",
  overview: "Моите случаи",
  empty: "Няма достъпни случаи за този профил.",
  bounded: "Показани са до 50 достъпни наскоро обновени случая.",
  create: "Създаване на случай",
  title: "Заглавие на случая (видимо за участниците)",
  kind: "Цел",
  buyer: "Покупка",
  tenant: "Наемане",
  seller: "Продажба",
  landlord: "Отдаване",
  next: "Следващо вътрешно действие",
  due: "Срок на действието (UTC)",
  clientSummary: "Следващо действие, видимо за клиента",
  requirements: "Изисквания за преглед",
  preferences: "Предпочитания за преглед",
  brief: "Изисквания",
  revise: "Нова версия на изискванията",
  draftBrief: "Интерпретация на брокера · няма записано съгласие на клиента",
  agreedBrief: "Има записано потвърждение от клиента за тази версия на изискванията",
  needsReview: "Изискванията са в процес на преглед",
  tasks: "Отворени последващи задачи",
  noTasks: "Няма отворени задачи, видими за текущия ви достъп по този случай.",
  moreTasks: "Отваряне на списъка със задачи",
  nextSave: "Запис на следващо действие",
  owned: "Отговорен брокер",
  noAction: "Няма записано следващо действие за клиента.",
  participants: "Текущи участници",
  authority: "Представителна власт",
  interests: "Имоти",
  addInterest: "Предлагане на имот",
  reference: "Номер на обявата",
  explanation: "Съответствие и известни компромиси (видими за участниците)",
  noInterests: "Все още няма предложени имоти.",
  stale: "Обявата е променена след тази оценка. Прегледайте текущите факти.",
  shortlist: "В краткия списък",
  decline: "Отказ",
  suggested: "Предложен",
  shortlisted: "В краткия списък",
  declined: "Отказан",
  viewing_requested: "Поискан оглед",
  viewed: "Разгледан",
  proposal: "Оферта",
  unavailable: "Недостъпен",
  feedback: "Обратна връзка или причина",
  respond: "Запис на обратна връзка",
  messages: "Разговор",
  message: "Съобщение",
  internal: "Вътрешна бележка · само за екипа",
  post: "Публикуване в случая",
  note: "Запазване на вътрешна бележка",
  reviewPost: "Прегледах аудиторията и точния текст. Да стане видимо в клиентския профил.",
  noMessages: "Няма достъпни съобщения по този случай.",
  shared: "Участници в случая",
  appointments: "Срещи",
  calendar: "Календар",
  request: "Заявка за оглед",
  preferredWindow: "Предпочитан период (не е потвърдена среща)",
  participant: "Участващ клиент",
  noAppointments: "Няма достъпни срещи.",
  calendarBounded: "Показани са до 100 достъпни наскоро обновени срещи.",
  requested: "Заявена",
  proposed: "Предложена",
  confirmed: "Потвърдена",
  reschedule_requested: "Поискана промяна · потвърденият час остава в сила",
  completed: "Завършена",
  cancelled: "Отменена",
  no_show: "Записано неявяване",
  arrangement: "Организиране на среща",
  start: "Начало в София с UTC отместване",
  end: "Край в София с UTC отместване",
  buffer: "Време за път преди и след (минути)",
  access: "Потвърдих достъпа до имота",
  external: "Проверих външните ангажименти на домакина",
  logistics: "Лични инструкции за среща и достъп",
  action: "Действие",
  propose: "Предлагане на часове",
  confirm: "Потвърждаване на срещата",
  change: "Запис на промяна",
  reason: "Причина или фактически резултат",
  reschedule: "Искане на друг час",
  cancel: "Отмяна на срещата",
  complete: "Запис на проведена среща",
  noShow: "Запис на проверено неявяване",
  download: "Изтегляне на календарен файл",
  confirmedTime: "Потвърден час",
  previousTime: "Предишна уговорка",
  proposedTime: "Предложен час",
  requestNote: "Предпочитаният период е заявка. Изчакайте изрично потвърждение.",
  status: "Статус на действието",
  back: "Отваряне на текущия запис",
  saved: "Промяната е записана",
  nextStep: "Отворете записа за текущото състояние.",
  denied: "Нямате достъп за това действие.",
  validation: "Прегледайте отбелязаните полета.",
  invalid: "Проверете тази стойност.",
  conflict: "Записът е променен. Сравнете го със запазената чернова преди ново действие.",
  transition: "Действието не е налично. Проверете състоянието и нужните доказателства.",
  calendarConflict: "Друг ангажимент заема този интервал за брокера или имота. Изберете друг час.",
  scope: "Текущият ви достъп определя видимите записи и действия.",
  requirementMessage:
    "Поискайте промяна на изискванията в разговора. Това не променя автоматично предишните уговорки.",
};
const ru: Copy = {
  ...en,
  cases: "Дела",
  proposals: "Предложения",
  documents: "Документы",
  prepareProposal: "Подготовить предложение",
  overview: "Мои дела",
  empty: "Нет доступных дел.",
  create: "Создать дело",
  title: "Название дела (видно участникам)",
  kind: "Цель",
  buyer: "Покупка",
  tenant: "Аренда",
  seller: "Продажа",
  landlord: "Сдача в аренду",
  next: "Следующее внутреннее действие",
  due: "Срок действия (UTC)",
  clientSummary: "Следующее действие для клиента",
  requirements: "Требования для проверки",
  preferences: "Предпочтения для проверки",
  brief: "Требования",
  revise: "Записать новую версию требований",
  draftBrief: "Интерпретация брокера · согласие клиента не записано",
  agreedBrief: "Подтверждение клиента записано для этой версии требований",
  needsReview: "Требования на рассмотрении",
  tasks: "Открытые задачи по делу",
  noTasks: "Нет открытых задач, доступных вам по этому делу.",
  moreTasks: "Открыть список задач",
  nextSave: "Записать следующее действие",
  owned: "Ответственный брокер",
  noAction: "Следующее действие для клиента не записано.",
  participants: "Текущие участники",
  authority: "Полномочия",
  interests: "Объекты",
  addInterest: "Предложить объект",
  reference: "Номер объявления",
  explanation: "Соответствие и известные компромиссы (видны участникам)",
  noInterests: "Объекты ещё не предложены.",
  stale: "Объявление изменилось. Проверьте актуальные факты перед решением.",
  shortlist: "В избранное",
  decline: "Отклонить",
  suggested: "Предложен",
  shortlisted: "В избранном",
  declined: "Отклонён",
  viewing_requested: "Просмотр запрошен",
  viewed: "Просмотрен",
  proposal: "Предложение",
  unavailable: "Недоступен",
  feedback: "Отзыв или причина",
  respond: "Записать отзыв",
  messages: "Разговор",
  message: "Сообщение",
  internal: "Внутренняя заметка · только сотрудникам",
  post: "Опубликовать в деле",
  note: "Сохранить внутреннюю заметку",
  reviewPost:
    "Я проверил аудиторию и точный текст. Сделать сообщение доступным в кабинете клиента.",
  noMessages: "Нет доступных сообщений по этому делу.",
  shared: "Участники дела",
  appointments: "Встречи",
  calendar: "Календарь",
  request: "Запросить просмотр",
  preferredWindow: "Предпочтительное время (не подтверждённая встреча)",
  participant: "Участвующий клиент",
  noAppointments: "Нет доступных встреч.",
  calendarBounded: "Показано до 100 доступных недавно обновлённых встреч.",
  requested: "Запрошена",
  proposed: "Предложена",
  confirmed: "Подтверждена",
  reschedule_requested: "Запрошено изменение · прежнее время остаётся в силе",
  completed: "Завершена",
  cancelled: "Отменена",
  no_show: "Записано неявление",
  arrangement: "Организация встречи",
  start: "Начало в Софии со смещением UTC",
  end: "Окончание в Софии со смещением UTC",
  buffer: "Время на дорогу до и после (минуты)",
  access: "Доступ к объекту подтверждён",
  external: "Я проверил внешние занятые интервалы ведущего",
  logistics: "Личные инструкции по встрече и доступу",
  action: "Действие",
  propose: "Предложить это время",
  confirm: "Подтвердить встречу",
  change: "Записать изменение",
  reason: "Причина или фактический результат",
  reschedule: "Запросить другое время",
  cancel: "Отменить встречу",
  complete: "Записать проведённую встречу",
  noShow: "Записать проверенное неявление",
  download: "Скачать файл календаря",
  confirmedTime: "Подтверждённое время",
  previousTime: "Прежняя договорённость",
  proposedTime: "Предложенное время",
  requestNote: "Предпочтительное время — запрос. Дождитесь явного подтверждения.",
  status: "Статус действия",
  back: "Открыть текущую запись",
  saved: "Изменение записано",
  nextStep: "Откройте запись для текущего состояния.",
  denied: "Нет доступа для этого действия.",
  validation: "Проверьте выделенные поля.",
  invalid: "Проверьте это значение.",
  conflict: "Запись изменилась. Сравните её с сохранённым черновиком перед новым действием.",
  transition: "Действие недоступно. Проверьте состояние и необходимые доказательства.",
  calendarConflict: "Этот интервал брокера или объекта уже занят. Выберите другое время.",
  scope: "Текущий доступ определяет видимые записи и действия.",
  requirementMessage:
    "Запросите изменение требований в разговоре. Это не изменяет прежние договорённости автоматически.",
};
export function caseCopy(locale: string): Copy {
  return locale === "bg" ? bg : locale === "ru" ? ru : en;
}
