const en = {
  title: "Case email",
  draft: "New email draft",
  recipient: "Recipient",
  recipients: "Recipients (up to 10)",
  separateDrafts:
    "Each selected recipient gets a separate draft to review and approve. Other recipients are not added to its address fields.",
  subject: "Subject",
  body: "Message",
  save: "Save draft for review",
  review: "Review exact email",
  from: "From",
  reply: "Reply address",
  channel: "Email · no attachments",
  calendar: "Calendar attachment (optional)",
  noCalendar: "No calendar attachment",
  calendarReview: "Calendar invitation or cancellation",
  calendarBoundary:
    "This file contains the committed time only. Sending it does not confirm attendance.",
  calendarRaw: "Inspect exact calendar file",
  calendarQueueReview:
    "I checked the recipient, complete message and calendar invitation or cancellation above",
  queue: "Approve and queue email",
  reviewed: "I checked the recipient, subject and complete message above",
  disabled:
    "Email sending is not enabled. You can prepare drafts; sending will remain unavailable until the service is configured.",
  noRecipients:
    "No eligible recipient. A current case participant needs a verified email address and recorded service-message eligibility.",
  empty: "No email drafts yet.",
  history: "Drafts and delivery",
  immutable:
    "Saved drafts keep their exact recipient and text. To change them, create a new draft. Approval queues only the email shown here.",
  draftState: "Draft — not sent",
  approved: "Approved",
  queued: "Queued — not sent yet",
  attempting: "Sending — awaiting provider response",
  provider_accepted: "Accepted by provider — delivery not confirmed",
  delivered: "Delivery reported by provider",
  bounced: "Bounced — delivery failed",
  failed: "Not delivered",
  outcome_unknown: "Result unknown — requires reconciliation before any further send",
  blocked: "Approval unavailable. Refresh the case to review its current information.",
  back: "Back to case",
  limited: "Showing the latest 50 email records.",
};
const bg: typeof en = {
  title: "Имейл по случая",
  draft: "Нов имейл — чернова",
  recipient: "Получател",
  recipients: "Получатели (до 10)",
  separateDrafts:
    "За всеки избран получател се създава отделна чернова за преглед и одобрение. Другите получатели не се добавят в адресните полета.",
  subject: "Тема",
  body: "Съобщение",
  save: "Запази за преглед",
  review: "Преглед на точния имейл",
  from: "От",
  reply: "Адрес за отговор",
  channel: "Имейл · без приложения",
  calendar: "Календарен файл (незадължително)",
  noCalendar: "Без календарен файл",
  calendarReview: "Покана или отмяна в календара",
  calendarBoundary: "Файлът съдържа само потвърдения час. Изпращането не потвърждава присъствие.",
  calendarRaw: "Преглед на точния календарен файл",
  calendarQueueReview: "Проверих получателя, цялото писмо и календарната покана или отмяна по-горе",
  queue: "Одобри и постави в опашката",
  reviewed: "Проверих получателя, темата и цялото съобщение по-горе",
  disabled:
    "Изпращането на имейли не е активирано. Можете да подготвяте чернови; изпращането изисква конфигурирана услуга.",
  noRecipients:
    "Няма допустим получател. Необходим е текущ участник с потвърден имейл и записано основание за служебни съобщения.",
  empty: "Все още няма чернови.",
  history: "Чернови и доставка",
  immutable:
    "Запазените чернови запазват точния получател и текст. За промяна създайте нова чернова. Одобрението се отнася само за показания имейл.",
  draftState: "Чернова — не е изпратена",
  approved: "Одобрен",
  queued: "В опашката — още не е изпратен",
  attempting: "Изпращане — изчаква се отговор",
  provider_accepted: "Приет от доставчика — доставката не е потвърдена",
  delivered: "Доставчикът отчете доставка",
  bounced: "Върнат — не е доставен",
  failed: "Не е доставен",
  outcome_unknown: "Неизвестен резултат — необходима е проверка преди следващо изпращане",
  blocked: "Одобрението е недостъпно. Обновете случая и прегледайте текущите данни.",
  back: "Обратно към случая",
  limited: "Показани са последните 50 имейла.",
};
const ru: typeof en = {
  title: "Письма по делу",
  draft: "Новый черновик письма",
  recipient: "Получатель",
  recipients: "Получатели (до 10)",
  separateDrafts:
    "Для каждого выбранного получателя создаётся отдельный черновик для проверки и утверждения. Остальные получатели не добавляются в адресные поля.",
  subject: "Тема",
  body: "Сообщение",
  save: "Сохранить для проверки",
  review: "Проверка точного письма",
  from: "Отправитель",
  reply: "Адрес для ответа",
  channel: "Email · без вложений",
  calendar: "Файл календаря (необязательно)",
  noCalendar: "Без файла календаря",
  calendarReview: "Приглашение или отмена в календаре",
  calendarBoundary: "Файл содержит только подтверждённое время. Отправка не подтверждает участие.",
  calendarRaw: "Проверить точный файл календаря",
  calendarQueueReview:
    "Я проверил получателя, всё письмо и календарное приглашение или отмену выше",
  queue: "Утвердить и поставить в очередь",
  reviewed: "Я проверил получателя, тему и полный текст выше",
  disabled:
    "Отправка писем не включена. Можно подготовить черновики; для отправки требуется настроенная служба.",
  noRecipients:
    "Нет доступного получателя. Нужен действующий участник дела с подтверждённым email и записанным основанием для служебных сообщений.",
  empty: "Черновиков пока нет.",
  history: "Черновики и доставка",
  immutable:
    "Черновик сохраняет точного получателя и текст. Для изменений создайте новый черновик. Утверждение относится только к показанному письму.",
  draftState: "Черновик — не отправлен",
  approved: "Утверждено",
  queued: "В очереди — ещё не отправлено",
  attempting: "Отправка — ожидается ответ провайдера",
  provider_accepted: "Принято провайдером — доставка не подтверждена",
  delivered: "Провайдер сообщил о доставке",
  bounced: "Возврат — доставка не удалась",
  failed: "Не доставлено",
  outcome_unknown: "Результат неизвестен — нужна сверка перед дальнейшей отправкой",
  blocked: "Утверждение недоступно. Обновите дело и проверьте актуальные данные.",
  back: "Вернуться к делу",
  limited: "Показаны последние 50 писем.",
};
export const caseEmailCopy = (locale: string) => (locale === "bg" ? bg : locale === "ru" ? ru : en);
