// Draft private-workspace copy. Human language acceptance is tracked separately.
const en = {
  title: "Case continuity",
  stage: "Change case stage",
  target: "Next stage",
  recordStage: "Record stage change",
  reason: "Reason",
  outcome: "Recorded outcome",
  evidence: "Reviewed completion document version ID",
  retention: "Retention disposition",
  aftercare: "Aftercare disposition",
  handoverStatus: "Property handover status",
  disposition: "Pause, reopen or close",
  state: "Case disposition",
  pause: "Paused",
  active: "Active",
  closed: "Closed",
  waiting: "Waiting for",
  reviewAt: "Review date (UTC)",
  next: "Next action when reopening",
  due: "Next action due (UTC)",
  recordDisposition: "Record disposition",
  handover: "Broker handover",
  receiver: "Receiving broker",
  review:
    "I reviewed the open commitments, recent communications, appointments, restricted documents and outstanding approvals.",
  request: "Request handover",
  accept: "Accept case and commitments",
  cancel: "Cancel pending handover",
  boundary:
    "The last accepted broker stays recorded until the receiver accepts. Work without an active broker enters agency coverage. Existing appointments retain their named host. Closeout requires every open task, appointment and proposal to be resolved individually.",
  completionNote:
    "Completion records an agency outcome. It requires current case review, exact-party agreement, reviewed completion evidence, the applicable listing status, handover, retention and aftercare. It does not certify legal completion.",
  history: "Recorded history",
  openTasks: "Open tasks",
  appointments: "Active appointments",
  proposals: "Open proposals",
  documents: "Restricted document records",
  approvals: "Pending proposal approvals",
  messages: "Recent messages (up to 20)",
  acknowledge: "Acknowledge this requirements revision",
  ackCheck: "I reviewed this exact requirements revision and acknowledge it as the current brief.",
  requestProposal: "Request proposal preparation",
  requestCheck:
    "Ask my broker to prepare terms for this property. This does not accept a price or create a legal commitment.",
  stageBlocked: "Stages require recorded evidence; a selection alone cannot establish it.",
  noReceivers: "No other active broker with case access is available.",
  pending: "A handover is awaiting the named receiver's acceptance.",
  back: "Open case",
};
type Copy = { [K in keyof typeof en]: string };
const bg: Copy = {
  ...en,
  title: "Продължаване на случая",
  stage: "Промяна на етапа",
  target: "Следващ етап",
  recordStage: "Запис на етапа",
  reason: "Причина",
  outcome: "Записан резултат",
  disposition: "Пауза, подновяване или приключване",
  state: "Състояние на случая",
  pause: "На пауза",
  active: "Активен",
  closed: "Приключен",
  handover: "Предаване на брокер",
  boundary:
    "Последният потвърден брокер остава записан до приемане от получателя. Работа без активен брокер влиза в дежурната опашка. Срещите запазват посочения домакин. Приключването изисква всяка отворена задача, среща и предложение да бъдат уредени поотделно.",
  receiver: "Приемащ брокер",
  request: "Искане за предаване",
  accept: "Приемане на случая и ангажиментите",
  cancel: "Отказ от предаването",
  history: "История",
  acknowledge: "Потвърждение на тази версия на изискванията",
  ackCheck: "Прегледах точно тази версия на изискванията и я потвърждавам като текуща.",
  requestProposal: "Искане за подготовка на предложение",
  requestCheck:
    "Моля брокера да подготви условия за този имот. Това не е приемане на цена или правен ангажимент.",
  back: "Отваряне на случая",
};
const ru: Copy = {
  ...en,
  title: "Продолжение дела",
  stage: "Изменить этап",
  target: "Следующий этап",
  recordStage: "Записать этап",
  reason: "Причина",
  outcome: "Записанный результат",
  disposition: "Приостановить, возобновить или закрыть",
  state: "Состояние дела",
  pause: "Приостановлено",
  active: "Активно",
  closed: "Закрыто",
  handover: "Передача брокеру",
  boundary:
    "Последний подтверждённый брокер остаётся в записи до принятия дела получателем. Работа без активного брокера попадает в очередь подхвата. Встречи сохраняют указанного ведущего. Перед закрытием нужно отдельно урегулировать каждую открытую задачу, встречу и предложение.",
  receiver: "Принимающий брокер",
  request: "Запросить передачу",
  accept: "Принять дело и обязательства",
  cancel: "Отменить передачу",
  history: "История",
  acknowledge: "Подтвердить эту версию требований",
  ackCheck: "Я проверил именно эту версию требований и подтверждаю её как текущую.",
  requestProposal: "Запросить подготовку предложения",
  requestCheck:
    "Прошу брокера подготовить условия по этому объекту. Это не принятие цены и не юридическое обязательство.",
  back: "Открыть дело",
};
export const lifecycleCopy = (locale: string): Copy =>
  locale === "bg" ? bg : locale === "ru" ? ru : en;
