const en = {
  privacy: "Personal data requests",
  preferences: "Contact and subscription preferences",
  operations: "Privacy review",
  lead: "Request access, correction or another action for your own information. A receipt confirms that your request was received. A person reviews its scope and the applicable policy; receipt does not mean data has been erased.",
  type: "Request type",
  scope: "What you want reviewed",
  scopeHelp:
    "Describe the scope briefly. Do not enter identity documents, financial records or another person's private information here.",
  confirm: "This request concerns my own information.",
  submit: "Send privacy request",
  history: "Your requests",
  empty: "No requests have been recorded.",
  owner: "Responsible person",
  due: "Reviewed response date",
  awaiting: "Awaiting human assessment under the approved policy",
  receipt: "Change recorded",
  error: "The change could not be confirmed. Review the current state before trying again.",
  conflict: "This record changed. Refresh and review the current version.",
  contacts: "Contact routes",
  verified: "Verified",
  unverified: "Not verified",
  contactLead:
    "Contact verification, service preferences, search alerts and marketing are separate. Changing a service preference does not opt you into optional messages.",
  language: "Preferred language",
  timezone: "Timezone",
  channel: "Preferred service channel",
  window: "Preferred contact times",
  save: "Save service preferences",
  email: "Email",
  phone: "Phone",
  optional: "Optional messages",
  noTerms: "Opt-in is unavailable until reviewed terms are published in this language.",
  noContact:
    "A verified email route is required. Confirm a new sign-in link for your current account first.",
  reverify: "Verify current email",
  terms: "Reviewed terms",
  optIn: "Opt in separately",
  consent: "I have read these terms and choose this purpose separately.",
  frequency: "Frequency",
  daily: "Daily digest",
  weekly: "Weekly digest",
  query: "Search words",
  searchPurpose: "Property purpose",
  sale: "Buy",
  rent: "Rent",
  maxPrice: "Maximum price in EUR (optional)",
  pause: "Pause",
  editSearch: "Edit saved search",
  saveSearch: "Save search preferences",
  resume: "Resume",
  withdraw: "Unsubscribe",
  none: "No optional subscriptions.",
  staffLead:
    "Review each request under the approved policy. Record the owner, reviewed due date and evidence. These controls record a human decision; they do not erase data or export records automatically.",
  state: "Next state",
  policy: "Approved policy reference",
  identity: "I reviewed identity and the stated scope.",
  hold: "Legal hold reason",
  disposition: "Hold / retention disposition",
  resolved: "A qualified reviewer has resolved any blocking hold for this action.",
  completion: "Completion evidence and downstream changes",
  rejection: "Reason for refusal",
  reviewed: "I reviewed the policy, scope, owner, due condition and evidence for this transition.",
  record: "Record human review",
  back: "Account",
  privacyLink: "Personal data requests",
  prefsLink: "Preferences",
};
const bg: typeof en = {
  ...en,
  privacy: "Искания за лични данни",
  preferences: "Предпочитания за контакт и абонаменти",
  operations: "Преглед на искания за лични данни",
  lead: "Поискайте достъп, корекция или друго действие за собствените си данни. Разписката потвърждава получаването. Човек преглежда обхвата и приложимата политика; получаването не означава изтриване.",
  type: "Вид искане",
  scope: "Какво да бъде прегледано",
  scopeHelp:
    "Опишете обхвата накратко. Не въвеждайте документи за самоличност, финансови записи или чужди лични данни.",
  confirm: "Искането се отнася до собствените ми данни.",
  submit: "Изпратете искането",
  history: "Вашите искания",
  empty: "Няма записани искания.",
  owner: "Отговорно лице",
  due: "Прегледана дата за отговор",
  awaiting: "Очаква човешка оценка по одобрената политика",
  receipt: "Промяната е записана",
  error: "Промяната не е потвърдена. Проверете текущото състояние преди нов опит.",
  conflict: "Записът е променен. Обновете и прегледайте текущата версия.",
  contacts: "Начини за контакт",
  verified: "Потвърден",
  unverified: "Непотвърден",
  contactLead:
    "Потвърждаването на контакт, служебните предпочитания, известията за търсене и маркетингът са отделни. Предпочитанието за контакт не е съгласие за незадължителни съобщения.",
  language: "Предпочитан език",
  timezone: "Часова зона",
  channel: "Предпочитан служебен канал",
  window: "Предпочитано време за контакт",
  save: "Запазете предпочитанията",
  email: "Имейл",
  phone: "Телефон",
  optional: "Незадължителни съобщения",
  noTerms: "Абонирането не е налично без публикувани прегледани условия на този език.",
  noContact: "Нужен е потвърден имейл. Потвърдете нова връзка за вход за текущия профил.",
  reverify: "Потвърдете текущия имейл",
  terms: "Прегледани условия",
  optIn: "Абонирайте се отделно",
  consent: "Прочетох условията и избирам тази цел отделно.",
  frequency: "Честота",
  daily: "Ежедневно обобщение",
  weekly: "Седмично обобщение",
  query: "Думи за търсене",
  searchPurpose: "Цел",
  sale: "Покупка",
  rent: "Наем",
  maxPrice: "Максимална цена в EUR (по избор)",
  pause: "Пауза",
  editSearch: "Променете запазеното търсене",
  saveSearch: "Запазете предпочитанията за търсене",
  resume: "Възобновете",
  withdraw: "Отпишете се",
  none: "Няма незадължителни абонаменти.",
  staffLead:
    "Прегледайте искането по одобрената политика. Запишете отговорник, прегледан срок и доказателства. Контролите записват човешко решение; не изтриват или експортират данни автоматично.",
  state: "Следващо състояние",
  policy: "Препратка към одобрена политика",
  identity: "Прегледах самоличността и заявения обхват.",
  hold: "Причина за задържане",
  disposition: "Решение за задържане / съхранение",
  resolved: "Компетентен преглеждащ е разрешил всяко задържане, което блокира действието.",
  completion: "Доказателства за изпълнение и последващи промени",
  rejection: "Причина за отказ",
  reviewed: "Прегледах политиката, обхвата, отговорника, срока и доказателствата за прехода.",
  record: "Запишете човешкия преглед",
  back: "Профил",
  privacyLink: "Искания за лични данни",
  prefsLink: "Предпочитания",
};
const names: Record<string, [string, string]> = {
  access: ["Access", "Достъп"],
  export: ["Export", "Експорт"],
  correction: ["Correction", "Корекция"],
  deletion: ["Deletion", "Изтриване"],
  restriction: ["Restriction", "Ограничаване"],
  objection: ["Objection", "Възражение"],
  received: ["Received", "Получено"],
  verifying: ["Identity/scope review", "Преглед на самоличност и обхват"],
  in_progress: ["In progress", "В процес"],
  on_legal_hold: ["Held for policy review", "Задържано за преглед по политика"],
  completed: ["Human completion recorded", "Записано човешко изпълнение"],
  rejected: ["Refused with a recorded reason", "Отказано със записана причина"],
  search_alerts: ["Saved-search alerts", "Известия за запазено търсене"],
  marketing: ["Marketing messages", "Маркетингови съобщения"],
  service_updates: ["Necessary service updates", "Необходими служебни съобщения"],
  active: ["Active", "Активен"],
  paused: ["Paused", "На пауза"],
  withdrawn: ["Unsubscribed", "Отписан"],
  pending_verification: ["Awaiting verification", "Очаква потвърждение"],
};
export const privacyCopy = (locale: string) => (locale === "bg" ? bg : en);
export const privacyLabel = (locale: string, value: string) =>
  names[value]?.[locale === "bg" ? 1 : 0] ?? value;
