// Staff-only copy. BG and RU are drafts for human language review; never public/indexable.
const en = {
  today: "Today",
  inbox: "Inbox",
  tasks: "Tasks",
  contacts: "Contacts",
  unassigned: "Unassigned",
  mine: "Mine",
  all: "Open inquiries",
  awaiting: "Awaiting client",
  review: "Needs review",
  due: "My overdue commitments",
  mineInquiries: "My open inquiries",
  queueNote:
    "These queues show inquiries and follow-up tasks you can access. Other work is shown in its own workspace.",
  empty: "No matching items in this queue.",
  noContacts: "No contacts linked to inquiries you can access.",
  previous: "Previous page",
  next: "Next page",
  owner: "Accountable owner",
  coverage: "Coverage queue",
  state: "Status",
  received: "Received",
  followUp: "Follow-up",
  noDate: "No date recorded",
  noOwner: "No named owner",
  reference: "Reference",
  details: "Details",
  submitted: "Original inquiry",
  preferredLocale: "Preferred language",
  contact: "Contact",
  channel: "Preferred channel",
  noContact: "No linked contact",
  contactScope:
    "Only inquiries you can access are shown here. Verified contact details do not establish authority to act.",
  methods: "Contact methods",
  linkedInquiries: "Related inquiries",
  activity: "Recent activity",
  actor: "Recorded by",
  revision: "Revision",
  accept: "Accept and assign to me",
  acceptLead:
    "Accept responsibility and record your next internal follow-up. This does not record a response to the client.",
  nextAction: "Next action",
  dueAt: "Follow-up time (UTC)",
  utcHint: "Enter a date and time in UTC. Your chosen time is stored with the commitment.",
  reason: "Reason",
  duplicateOfInquiryId: "Original inquiry ID (for duplicate review)",
  duplicateHint:
    "Open the original inquiry and use its ID. Both inquiries must be accessible to you.",
  disposition: "Record a disposition",
  dispositionLead:
    "Review states keep the request visible. Resolution requires every open task to be completed or explicitly cancelled.",
  taskChange: "Update task",
  note: "Outcome, dependency or cancellation reason",
  followUpAt: "Dependency review time (UTC)",
  guardedTask: "Completion needs the evidence and controls in the workspace that owns this task.",
  purpose: "Purpose",
  outcome: "Recorded outcome",
  dependency: "Waiting on",
  changeSaved: "Change recorded",
  nextStep: "Open the updated record to continue.",
  openRecord: "Open updated record",
  statusLink: "Check this action",
  statusTitle: "Action status",
  statusMissing:
    "No completed action was found. Return to the record and check its current state before submitting again.",
  statusSucceeded: "This action was recorded successfully.",
  statusFailed: "This action was not applied. Return to the record to review and correct it.",
  statusPending:
    "The action has not reached a confirmed outcome. Keep this reference and check again before retrying.",
  validation: "Review the highlighted details.",
  invalid: "Check this value.",
  conflict:
    "This record changed. Compare the latest version with your draft before applying it again.",
  denied: "Your current access does not allow this action.",
  unavailable: "This action is not available in the current state.",
  commitments: "Resolve the open follow-up tasks before closing this inquiry.",
  sessionEnded: "Your session ended. Sign in again before continuing.",
  unknown: "We could not confirm the result. Check the action status before trying again.",
  form: {
    errorSummary: "There is a problem",
    pending: "Recording…",
    reapply: "Apply my reviewed changes",
    yourValue: "Your draft",
    latestValue: "Latest value",
    revision: "Revision",
    reference: "Reference",
    recordedAt: "Recorded at",
    unknown: "Result not confirmed",
    draftRetained: "Your draft is retained. Check the action status before trying again.",
  },
  states: {
    received: "Received",
    assigned: "Assigned",
    awaiting_client: "Awaiting client",
    linked_to_case: "Linked to case",
    resolved_without_case: "Resolved without case",
    suspected_spam: "Suspected spam",
    duplicate_candidate: "Possible duplicate",
    contact_unreachable: "Contact unreachable",
    open: "Open",
    in_progress: "In progress",
    waiting: "Waiting",
    done: "Done",
    cancelled: "Cancelled",
  },
  purposes: {
    question: "Question",
    callback: "Callback",
    viewing_request: "Viewing request",
    seller_consultation: "Seller consultation",
    landlord_consultation: "Landlord consultation",
    service_consultation: "Service consultation",
  },
  events: {
    "work.inquiry.accepted": "Responsibility accepted and follow-up recorded",
    "work.inquiry.triaged": "Inquiry disposition updated",
    "inquiry.received": "Inquiry received",
  },
};
type Copy = {
  [K in keyof typeof en]: (typeof en)[K] extends string
    ? string
    : { [S in keyof (typeof en)[K]]: string };
};
const bg: Copy = {
  today: "Днес",
  inbox: "Входящи",
  tasks: "Задачи",
  contacts: "Контакти",
  unassigned: "Неразпределени",
  mine: "Мои",
  all: "Отворени запитвания",
  awaiting: "Изчакват клиент",
  review: "За преглед",
  due: "Моите просрочени ангажименти",
  mineInquiries: "Моите отворени запитвания",
  queueNote:
    "Тук са запитванията и последващите задачи, до които имате достъп. Останалата работа е в съответните раздели.",
  empty: "Няма съответстващи записи.",
  noContacts: "Няма контакти към достъпни за вас запитвания.",
  previous: "Предишна страница",
  next: "Следваща страница",
  owner: "Отговорник",
  coverage: "Дежурен екип",
  state: "Статус",
  received: "Получено",
  followUp: "Следващо действие",
  noDate: "Няма записана дата",
  noOwner: "Няма определен отговорник",
  reference: "Номер",
  details: "Подробности",
  submitted: "Оригинално запитване",
  preferredLocale: "Предпочитан език",
  contact: "Контакт",
  channel: "Предпочитан канал",
  noContact: "Няма свързан контакт",
  contactScope:
    "Показани са само достъпните за вас запитвания. Потвърденият контакт не означава представителна власт.",
  methods: "Начини за контакт",
  linkedInquiries: "Свързани запитвания",
  activity: "Последни действия",
  actor: "Записано от",
  revision: "Версия",
  accept: "Приемам отговорността",
  acceptLead:
    "Поемете запитването и запишете следващото вътрешно действие. Това не отбелязва отговор до клиента.",
  nextAction: "Следващо действие",
  dueAt: "Срок за действие (UTC)",
  utcHint: "Въведете дата и час в UTC. Избраният час се записва към ангажимента.",
  reason: "Причина",
  duplicateOfInquiryId: "ID на първоначалното запитване (при дубликат)",
  duplicateHint:
    "Отворете първоначалното запитване и използвайте неговия ID. Трябва да имате достъп и до двете.",
  disposition: "Запис на решение",
  dispositionLead:
    "Запитванията за преглед остават видими. За приключване завършете или изрично отменете всички отворени задачи.",
  taskChange: "Обновяване на задача",
  note: "Резултат, зависимост или причина за отмяна",
  followUpAt: "Час за преглед на зависимостта (UTC)",
  guardedTask:
    "Завършването изисква доказателствата и проверките в раздела, който управлява тази задача.",
  purpose: "Цел",
  outcome: "Записан резултат",
  dependency: "Изчаква",
  changeSaved: "Промяната е записана",
  nextStep: "Отворете обновения запис, за да продължите.",
  openRecord: "Отваряне на обновения запис",
  statusLink: "Проверка на действието",
  statusTitle: "Статус на действието",
  statusMissing:
    "Няма намерено завършено действие. Проверете текущото състояние на записа преди ново изпращане.",
  statusSucceeded: "Действието е записано успешно.",
  statusFailed: "Действието не е приложено. Върнете се към записа за преглед и корекция.",
  statusPending:
    "Резултатът още не е потвърден. Запазете номера и проверете отново преди повторен опит.",
  validation: "Прегледайте отбелязаните полета.",
  invalid: "Проверете тази стойност.",
  conflict: "Записът е променен. Сравнете новата версия с черновата преди повторно прилагане.",
  denied: "Текущият ви достъп не позволява това действие.",
  unavailable: "Действието не е налично в текущото състояние.",
  commitments: "Приключете отворените задачи преди затваряне на запитването.",
  sessionEnded: "Сесията е изтекла. Влезте отново.",
  unknown: "Не можем да потвърдим резултата. Проверете статуса преди повторен опит.",
  form: {
    errorSummary: "Има проблем",
    pending: "Записване…",
    reapply: "Прилагане на прегледаните промени",
    yourValue: "Вашата чернова",
    latestValue: "Последна стойност",
    revision: "Версия",
    reference: "Номер",
    recordedAt: "Записано на",
    unknown: "Непотвърден резултат",
    draftRetained: "Черновата е запазена. Проверете статуса преди повторен опит.",
  },
  states: {
    received: "Получено",
    assigned: "Разпределено",
    awaiting_client: "Изчаква клиент",
    linked_to_case: "Свързано със случай",
    resolved_without_case: "Приключено без случай",
    suspected_spam: "Предполагаем спам",
    duplicate_candidate: "Възможен дубликат",
    contact_unreachable: "Недостъпен контакт",
    open: "Отворена",
    in_progress: "В процес",
    waiting: "Изчаква",
    done: "Завършена",
    cancelled: "Отменена",
  },
  purposes: {
    question: "Въпрос",
    callback: "Обратно обаждане",
    viewing_request: "Заявка за оглед",
    seller_consultation: "Консултация за продавач",
    landlord_consultation: "Консултация за наемодател",
    service_consultation: "Консултация за услуга",
  },
  events: {
    "work.inquiry.accepted": "Отговорността е приета и е записана следваща задача",
    "work.inquiry.triaged": "Решението по запитването е обновено",
    "inquiry.received": "Запитването е получено",
  },
};
const ru: Copy = {
  today: "Сегодня",
  inbox: "Входящие",
  tasks: "Задачи",
  contacts: "Контакты",
  unassigned: "Без исполнителя",
  mine: "Мои",
  all: "Открытые обращения",
  awaiting: "Ожидают клиента",
  review: "На проверке",
  due: "Мои просроченные обязательства",
  mineInquiries: "Мои открытые обращения",
  queueNote:
    "Здесь показаны доступные вам обращения и последующие задачи. Остальная работа находится в соответствующих разделах.",
  empty: "Нет подходящих записей.",
  noContacts: "Нет контактов по доступным вам обращениям.",
  previous: "Предыдущая страница",
  next: "Следующая страница",
  owner: "Ответственный",
  coverage: "Дежурная команда",
  state: "Статус",
  received: "Получено",
  followUp: "Следующее действие",
  noDate: "Дата не указана",
  noOwner: "Ответственный не назначен",
  reference: "Номер",
  details: "Подробности",
  submitted: "Исходное обращение",
  preferredLocale: "Предпочитаемый язык",
  contact: "Контакт",
  channel: "Предпочитаемый канал",
  noContact: "Нет связанного контакта",
  contactScope:
    "Показаны только доступные вам обращения. Подтверждение контакта не даёт полномочий действовать от имени клиента.",
  methods: "Способы связи",
  linkedInquiries: "Связанные обращения",
  activity: "Последние действия",
  actor: "Записал",
  revision: "Версия",
  accept: "Принять и назначить себе",
  acceptLead:
    "Примите ответственность и запишите следующий внутренний шаг. Это не отмечает ответ клиенту.",
  nextAction: "Следующее действие",
  dueAt: "Срок следующего действия (UTC)",
  utcHint: "Введите дату и время в UTC. Выбранное время сохранится в задаче.",
  reason: "Причина",
  duplicateOfInquiryId: "ID исходного обращения (для дубликата)",
  duplicateHint:
    "Откройте исходное обращение и используйте его ID. Вам должны быть доступны обе записи.",
  disposition: "Записать решение",
  dispositionLead:
    "Обращения на проверке остаются видимыми. Перед закрытием завершите или явно отмените все открытые задачи.",
  taskChange: "Обновить задачу",
  note: "Результат, зависимость или причина отмены",
  followUpAt: "Время проверки зависимости (UTC)",
  guardedTask:
    "Завершение требует доказательств и проверок в разделе, который управляет этой задачей.",
  purpose: "Цель",
  outcome: "Записанный результат",
  dependency: "Ожидается",
  changeSaved: "Изменение записано",
  nextStep: "Откройте обновлённую запись, чтобы продолжить.",
  openRecord: "Открыть обновлённую запись",
  statusLink: "Проверить действие",
  statusTitle: "Статус действия",
  statusMissing:
    "Завершённое действие не найдено. Проверьте текущее состояние записи перед повторной отправкой.",
  statusSucceeded: "Действие успешно записано.",
  statusFailed: "Действие не применено. Вернитесь к записи для проверки и исправления.",
  statusPending:
    "Результат ещё не подтверждён. Сохраните номер и проверьте ещё раз перед повтором.",
  validation: "Проверьте выделенные поля.",
  invalid: "Проверьте это значение.",
  conflict:
    "Запись изменилась. Сравните последнюю версию с черновиком перед повторным применением.",
  denied: "Ваш текущий доступ не позволяет это действие.",
  unavailable: "Действие недоступно в текущем состоянии.",
  commitments: "Завершите открытые задачи перед закрытием обращения.",
  sessionEnded: "Сессия завершена. Войдите снова.",
  unknown: "Не удалось подтвердить результат. Проверьте статус перед повтором.",
  form: {
    errorSummary: "Возникла проблема",
    pending: "Запись…",
    reapply: "Применить проверенные изменения",
    yourValue: "Ваш черновик",
    latestValue: "Последнее значение",
    revision: "Версия",
    reference: "Номер",
    recordedAt: "Записано",
    unknown: "Результат не подтверждён",
    draftRetained: "Черновик сохранён. Проверьте статус перед повтором.",
  },
  states: {
    received: "Получено",
    assigned: "Назначено",
    awaiting_client: "Ожидает клиента",
    linked_to_case: "Связано с делом",
    resolved_without_case: "Закрыто без дела",
    suspected_spam: "Возможный спам",
    duplicate_candidate: "Возможный дубликат",
    contact_unreachable: "Контакт недоступен",
    open: "Открыта",
    in_progress: "В работе",
    waiting: "Ожидает",
    done: "Завершена",
    cancelled: "Отменена",
  },
  purposes: {
    question: "Вопрос",
    callback: "Обратный звонок",
    viewing_request: "Запрос просмотра",
    seller_consultation: "Консультация продавца",
    landlord_consultation: "Консультация арендодателя",
    service_consultation: "Консультация по услуге",
  },
  events: {
    "work.inquiry.accepted": "Ответственность принята и следующий шаг записан",
    "work.inquiry.triaged": "Решение по обращению обновлено",
    "inquiry.received": "Обращение получено",
  },
};
export function workCopy(locale: string): Copy {
  return locale === "bg" ? bg : locale === "ru" ? ru : en;
}
export type WorkCopy = Copy;
