// Staff-only copy. BG and RU are drafts for human language review; never public/indexable.
const en = {
  today: "Today",
  inbox: "Inquiries",
  tasks: "Tasks",
  contacts: "Contacts",
  unassigned: "Unassigned",
  mine: "Mine",
  all: "Open inquiries",
  awaiting: "Awaiting client",
  review: "Needs review",
  due: "My overdue tasks",
  mineInquiries: "My open inquiries",
  queueNote:
    "These lists show the work you can access: inquiries, tasks, key returns, viewings, Cases, listings, translations and delivery problems. Each record opens in its own workspace.",
  empty: "No matching items in this queue.",
  noContacts: "No contacts linked to inquiries you can access.",
  previous: "Previous page",
  next: "Next page",
  owner: "Accountable owner",
  coverage: "Coverage queue",
  state: "Status",
  received: "Received",
  followUp: "Follow-up",
  nextReview: "Next review",
  noDate: "No date recorded",
  noOwner: "No named owner",
  details: "Details",
  submitted: "Original inquiry",
  preferredLocale: "Preferred language",
  contact: "Contact",
  channel: "Preferred channel",
  noContact: "No linked contact",
  contactScope:
    "Only inquiries you can access are shown here. Verified contact details do not establish authority to act.",
  methods: "Contact methods",
  linkedInquiries: "Related inquiries",
  activity: "Recent activity",
  actor: "Recorded by",
  revision: "Revision",
  accept: "Accept and assign to me",
  acceptLead:
    "Accept responsibility and record your next internal follow-up. This does not record a response to the client.",
  nextAction: "Next action",
  dueAt: "Follow-up time (UTC)",
  utcHint: "Enter a date and time in UTC. Your chosen time is stored with the commitment.",
  reason: "Reason",
  duplicateOfInquiryId: "Original inquiry ID (for duplicate review)",
  duplicateHint:
    "Open the original inquiry and use its ID. Both inquiries must be accessible to you.",
  disposition: "Record a disposition",
  dispositionLead:
    "Review states keep the request visible. Resolution requires every open task to be completed or explicitly cancelled.",
  taskChange: "Update task",
  note: "Outcome, dependency or cancellation reason",
  followUpAt: "Dependency review time (UTC)",
  guardedTask: "Completion needs the evidence and controls in the workspace that owns this task.",
  purpose: "Purpose",
  outcome: "Recorded outcome",
  dependency: "Waiting on",
  changeSaved: "Change recorded",
  nextStep: "Open the updated record to continue.",
  openRecord: "Open updated record",
  statusLink: "Check this action",
  statusTitle: "Action status",
  statusMissing:
    "No completed action was found. Return to the record and check its current state before submitting again.",
  statusSucceeded: "This action was recorded successfully.",
  statusFailed: "This action was not applied. Return to the record to review and correct it.",
  statusPending:
    "The action has not reached a confirmed outcome. Keep this reference and check again before retrying.",
  validation: "Review the highlighted details.",
  invalid: "Check this value.",
  // Stable server reason keys (server.validation.work.handover.dueAt.*).
  reasons: {
    future_required: "Choose a time in the future.",
    after_deadline:
      "This time is after the deadline promised to the client. Choose an earlier time.",
    invalid_local_time:
      "This time does not exist in Europe/Sofia (the clocks move forward). Choose another time.",
    ambiguous_local_time:
      "This time occurs twice in Europe/Sofia (the clocks move back). Choose another time.",
  } as Record<string, string>,
  conflict:
    "This record changed. Compare the latest version with your draft before applying it again.",
  denied: "Your current access does not allow this action.",
  unavailable: "This action is not available in the current state.",
  commitments: "Resolve the open follow-up tasks before closing this inquiry.",
  sessionEnded: "Your session ended. Sign in again before continuing.",
  unknown: "We could not confirm the result. Check the action status before trying again.",
  form: {
    errorSummary: "There is a problem",
    pending: "Recording…",
    reapply: "Apply my reviewed changes",
    yourValue: "Your draft",
    latestValue: "Latest value",
    revision: "Revision",
    reference: "Reference",
    recordedAt: "Recorded at",
    unknown: "Result not confirmed",
    draftRetained: "Your draft is retained. Check the action status before trying again.",
  },
  states: {
    received: "Received",
    assigned: "Assigned",
    awaiting_client: "Awaiting client",
    linked_to_case: "Linked to case",
    resolved_without_case: "Resolved without case",
    suspected_spam: "Suspected spam",
    duplicate_candidate: "Possible duplicate",
    contact_unreachable: "Contact unreachable",
    open: "Open",
    in_progress: "In progress",
    waiting: "Waiting",
    done: "Done",
    cancelled: "Cancelled",
  },
  purposes: {
    question: "Question",
    callback: "Callback",
    viewing_request: "Viewing request",
    seller_consultation: "Seller consultation",
    landlord_consultation: "Landlord consultation",
    service_consultation: "Service consultation",
  },
  events: {
    "work.inquiry.accepted": "Responsibility accepted and follow-up recorded",
    "work.inquiry.triaged": "Inquiry disposition updated",
    "inquiry.received": "Inquiry received",
  },
  // O02 queue (Figma 11:4257, O02MINE 66:34585, O02UNCLAIMED 66:34531).
  scopes: {
    all: "All",
    unassigned: "Unclaimed",
    mine: "Mine",
    awaiting: "Awaiting client",
    review: "Needs review",
  },
  scopeLeads: {
    all: "Choose a conversation and take on the next action.",
    unassigned: "Conversations that are definitely unclaimed.",
    mine: "Conversations you are accountable for.",
    awaiting: "Conversations waiting for the client to reply.",
    review:
      "Conversations held for review: suspected spam, a possible duplicate or an unreachable contact.",
  },
  scopeEmpty: {
    all: "No open conversations",
    unassigned: "No confirmed unclaimed conversations",
    mine: "No conversations are assigned to you",
    awaiting: "No conversations are waiting for the client",
    review: "No conversations are held for review",
  },
  scopeEmptyNotes: {
    all: "Only open inquiries you can access are shown here.",
    unassigned:
      "An unclear owner does not make a conversation free. Check coverage before you take one on.",
    mine: "Conversations you accept appear here.",
    awaiting: "Only open inquiries you can access are shown here.",
    review: "Only open inquiries you can access are shown here.",
  },
  queue: {
    views: "Inquiry views",
    list: "Conversations",
    pages: "Queue pages",
    open: "Open a conversation to see its context, owner and next action.",
    back: "Back to inquiries",
    skip: "Skip to the conversation",
    checkCoverage: "Check coverage",
    failed: "The queue could not be loaded",
    failedNote: "This does not mean there are no inquiries. Try again in a moment.",
    retry: "Try again",
    pageEmpty: "There are no conversations on this page.",
    firstPage: "Back to the first page",
    search: "Search conversations",
    searchHint: "Part of a name, or a full phone number or email address.",
    searchSubmit: "Search",
    searchBlank: "Enter a name, phone number or email address to search.",
    searchShort: "Enter at least 2 characters.",
    searchLong: "Enter at most 120 characters.",
    searchFailed: "The search could not be completed. The queue is unchanged; try again.",
    results: "Search results",
    noResults: "No conversation matches this search.",
    clearSearch: "Back to the queue",
    receivedAgo: "Received {age}",
  },
};
type Copy = {
  [K in keyof typeof en]: (typeof en)[K] extends string
    ? string
    : { [S in keyof (typeof en)[K]]: string };
};
const bg: Copy = {
  today: "Днес",
  inbox: "Запитвания",
  tasks: "Задачи",
  contacts: "Контакти",
  unassigned: "Неразпределени",
  mine: "Мои",
  all: "Отворени запитвания",
  awaiting: "Изчакват клиент",
  review: "За преглед",
  due: "Моите просрочени задачи",
  mineInquiries: "Моите отворени запитвания",
  queueNote:
    "Тук е работата, до която имате достъп: запитвания, задачи, връщане на ключове, огледи, случаи, обяви, преводи и проблеми с доставката. Всеки запис се отваря в своя раздел.",
  empty: "Няма съответстващи записи.",
  noContacts: "Няма контакти към достъпни за вас запитвания.",
  previous: "Предишна страница",
  next: "Следваща страница",
  owner: "Отговорник",
  coverage: "Дежурен екип",
  state: "Статус",
  received: "Получено",
  followUp: "Следващо действие",
  nextReview: "Следващ преглед",
  noDate: "Няма записана дата",
  noOwner: "Няма определен отговорник",
  details: "Подробности",
  submitted: "Оригинално запитване",
  preferredLocale: "Предпочитан език",
  contact: "Контакт",
  channel: "Предпочитан канал",
  noContact: "Няма свързан контакт",
  contactScope:
    "Показани са само достъпните за вас запитвания. Потвърденият контакт не означава представителна власт.",
  methods: "Начини за контакт",
  linkedInquiries: "Свързани запитвания",
  activity: "Последни действия",
  actor: "Записано от",
  revision: "Версия",
  accept: "Приемам отговорността",
  acceptLead:
    "Поемете запитването и запишете следващото вътрешно действие. Това не отбелязва отговор до клиента.",
  nextAction: "Следващо действие",
  dueAt: "Срок за действие (UTC)",
  utcHint: "Въведете дата и час в UTC. Избраният час се записва към ангажимента.",
  reason: "Причина",
  duplicateOfInquiryId: "ID на първоначалното запитване (при дубликат)",
  duplicateHint:
    "Отворете първоначалното запитване и използвайте неговия ID. Трябва да имате достъп и до двете.",
  disposition: "Запис на решение",
  dispositionLead:
    "Запитванията за преглед остават видими. За приключване завършете или изрично отменете всички отворени задачи.",
  taskChange: "Обновяване на задача",
  note: "Резултат, зависимост или причина за отмяна",
  followUpAt: "Час за преглед на зависимостта (UTC)",
  guardedTask:
    "Завършването изисква доказателствата и проверките в раздела, който управлява тази задача.",
  purpose: "Цел",
  outcome: "Записан резултат",
  dependency: "Изчаква",
  changeSaved: "Промяната е записана",
  nextStep: "Отворете обновения запис, за да продължите.",
  openRecord: "Отваряне на обновения запис",
  statusLink: "Проверка на действието",
  statusTitle: "Статус на действието",
  statusMissing:
    "Няма намерено завършено действие. Проверете текущото състояние на записа преди ново изпращане.",
  statusSucceeded: "Действието е записано успешно.",
  statusFailed: "Действието не е приложено. Върнете се към записа за преглед и корекция.",
  statusPending:
    "Резултатът още не е потвърден. Запазете номера и проверете отново преди повторен опит.",
  validation: "Прегледайте отбелязаните полета.",
  invalid: "Проверете тази стойност.",
  reasons: {
    future_required: "Изберете час в бъдещето.",
    after_deadline: "Този час е след срока, обещан на клиента. Изберете по-ранен час.",
    invalid_local_time:
      "Този час не съществува в Europe/Sofia (часовникът се мести напред). Изберете друг час.",
    ambiguous_local_time:
      "Този час се повтаря в Europe/Sofia (часовникът се мести назад). Изберете друг час.",
  } as Record<string, string>,
  conflict: "Записът е променен. Сравнете новата версия с черновата преди повторно прилагане.",
  denied: "Текущият ви достъп не позволява това действие.",
  unavailable: "Действието не е налично в текущото състояние.",
  commitments: "Приключете отворените задачи преди затваряне на запитването.",
  sessionEnded: "Сесията е изтекла. Влезте отново.",
  unknown: "Не можем да потвърдим резултата. Проверете статуса преди повторен опит.",
  form: {
    errorSummary: "Има проблем",
    pending: "Записване…",
    reapply: "Прилагане на прегледаните промени",
    yourValue: "Вашата чернова",
    latestValue: "Последна стойност",
    revision: "Версия",
    reference: "Номер",
    recordedAt: "Записано на",
    unknown: "Непотвърден резултат",
    draftRetained: "Черновата е запазена. Проверете статуса преди повторен опит.",
  },
  states: {
    received: "Получено",
    assigned: "Разпределено",
    awaiting_client: "Изчаква клиент",
    linked_to_case: "Свързано със случай",
    resolved_without_case: "Приключено без случай",
    suspected_spam: "Предполагаем спам",
    duplicate_candidate: "Възможен дубликат",
    contact_unreachable: "Недостъпен контакт",
    open: "Отворена",
    in_progress: "В процес",
    waiting: "Изчаква",
    done: "Завършена",
    cancelled: "Отменена",
  },
  purposes: {
    question: "Въпрос",
    callback: "Обратно обаждане",
    viewing_request: "Заявка за оглед",
    seller_consultation: "Консултация за продавач",
    landlord_consultation: "Консултация за наемодател",
    service_consultation: "Консултация за услуга",
  },
  events: {
    "work.inquiry.accepted": "Отговорността е приета и е записана следваща задача",
    "work.inquiry.triaged": "Решението по запитването е обновено",
    "inquiry.received": "Запитването е получено",
  },
  scopes: {
    all: "Всички",
    unassigned: "Непоети",
    mine: "Мои",
    awaiting: "Изчакват клиент",
    review: "За преглед",
  },
  scopeLeads: {
    all: "Изберете разговор и поемете следващото действие.",
    unassigned: "Разговори, които със сигурност са свободни.",
    mine: "Разговори, за които отговаряте вие.",
    awaiting: "Разговори, в които чакаме отговор от клиента.",
    review: "Разговори за преглед: предполагаем спам, възможен дубликат или недостъпен контакт.",
  },
  scopeEmpty: {
    all: "Няма отворени разговори",
    unassigned: "Няма потвърдени непоети разговори",
    mine: "Нямате поети разговори",
    awaiting: "Няма разговори, които чакат клиента",
    review: "Няма разговори за преглед",
  },
  scopeEmptyNotes: {
    all: "Тук се показват само отворените запитвания, до които имате достъп.",
    unassigned:
      "Неясният отговорник не означава свободен разговор. Проверете заместването, преди да го поемете.",
    mine: "Разговорите, които поемете, ще се появят тук.",
    awaiting: "Тук се показват само отворените запитвания, до които имате достъп.",
    review: "Тук се показват само отворените запитвания, до които имате достъп.",
  },
  queue: {
    views: "Изгледи на запитванията",
    list: "Разговори",
    pages: "Страници на опашката",
    open: "Отворете разговор, за да видите контекста, отговорника и следващото действие.",
    back: "Обратно към запитванията",
    skip: "Към разговора",
    checkCoverage: "Проверка на заместването",
    failed: "Опашката не можа да се зареди",
    failedNote: "Това не означава, че няма запитвания. Опитайте отново след малко.",
    retry: "Опитайте отново",
    pageEmpty: "На тази страница няма разговори.",
    firstPage: "Към първата страница",
    search: "Търсене в разговори",
    searchHint: "Част от име или пълен телефон или имейл.",
    searchSubmit: "Търсене",
    searchBlank: "Въведете име, телефон или имейл за търсене.",
    searchShort: "Въведете поне 2 знака.",
    searchLong: "Въведете най-много 120 знака.",
    searchFailed: "Търсенето не беше изпълнено. Опашката е непроменена; опитайте отново.",
    results: "Резултати от търсенето",
    noResults: "Няма разговор, който отговаря на търсенето.",
    clearSearch: "Обратно към опашката",
    receivedAgo: "Получено {age}",
  },
};
const ru: Copy = {
  today: "Сегодня",
  inbox: "Запросы",
  tasks: "Задачи",
  contacts: "Контакты",
  unassigned: "Без исполнителя",
  mine: "Мои",
  all: "Открытые обращения",
  awaiting: "Ожидают клиента",
  review: "На проверке",
  due: "Мои просроченные задачи",
  mineInquiries: "Мои открытые обращения",
  queueNote:
    "Здесь работа, к которой у вас есть доступ: обращения, задачи, возвраты ключей, показы, дела, объявления, переводы и проблемы доставки. Каждая запись открывается в своём разделе.",
  empty: "Нет подходящих записей.",
  noContacts: "Нет контактов по доступным вам обращениям.",
  previous: "Предыдущая страница",
  next: "Следующая страница",
  owner: "Ответственный",
  coverage: "Дежурная команда",
  state: "Статус",
  received: "Получено",
  followUp: "Следующее действие",
  nextReview: "Следующая проверка",
  noDate: "Дата не указана",
  noOwner: "Ответственный не назначен",
  details: "Подробности",
  submitted: "Исходное обращение",
  preferredLocale: "Предпочитаемый язык",
  contact: "Контакт",
  channel: "Предпочитаемый канал",
  noContact: "Нет связанного контакта",
  contactScope:
    "Показаны только доступные вам обращения. Подтверждение контакта не даёт полномочий действовать от имени клиента.",
  methods: "Способы связи",
  linkedInquiries: "Связанные обращения",
  activity: "Последние действия",
  actor: "Записал",
  revision: "Версия",
  accept: "Принять и назначить себе",
  acceptLead:
    "Примите ответственность и запишите следующий внутренний шаг. Это не отмечает ответ клиенту.",
  nextAction: "Следующее действие",
  dueAt: "Срок следующего действия (UTC)",
  utcHint: "Введите дату и время в UTC. Выбранное время сохранится в задаче.",
  reason: "Причина",
  duplicateOfInquiryId: "ID исходного обращения (для дубликата)",
  duplicateHint:
    "Откройте исходное обращение и используйте его ID. Вам должны быть доступны обе записи.",
  disposition: "Записать решение",
  dispositionLead:
    "Обращения на проверке остаются видимыми. Перед закрытием завершите или явно отмените все открытые задачи.",
  taskChange: "Обновить задачу",
  note: "Результат, зависимость или причина отмены",
  followUpAt: "Время проверки зависимости (UTC)",
  guardedTask:
    "Завершение требует доказательств и проверок в разделе, который управляет этой задачей.",
  purpose: "Цель",
  outcome: "Записанный результат",
  dependency: "Ожидается",
  changeSaved: "Изменение записано",
  nextStep: "Откройте обновлённую запись, чтобы продолжить.",
  openRecord: "Открыть обновлённую запись",
  statusLink: "Проверить действие",
  statusTitle: "Статус действия",
  statusMissing:
    "Завершённое действие не найдено. Проверьте текущее состояние записи перед повторной отправкой.",
  statusSucceeded: "Действие успешно записано.",
  statusFailed: "Действие не применено. Вернитесь к записи для проверки и исправления.",
  statusPending:
    "Результат ещё не подтверждён. Сохраните номер и проверьте ещё раз перед повтором.",
  validation: "Проверьте выделенные поля.",
  invalid: "Проверьте это значение.",
  reasons: {
    future_required: "Выберите время в будущем.",
    after_deadline: "Это время позже срока, обещанного клиенту. Выберите более раннее время.",
    invalid_local_time:
      "Такого времени нет в Europe/Sofia (часы переводятся вперёд). Выберите другое время.",
    ambiguous_local_time:
      "Это время повторяется в Europe/Sofia (часы переводятся назад). Выберите другое время.",
  } as Record<string, string>,
  conflict:
    "Запись изменилась. Сравните последнюю версию с черновиком перед повторным применением.",
  denied: "Ваш текущий доступ не позволяет это действие.",
  unavailable: "Действие недоступно в текущем состоянии.",
  commitments: "Завершите открытые задачи перед закрытием обращения.",
  sessionEnded: "Сессия завершена. Войдите снова.",
  unknown: "Не удалось подтвердить результат. Проверьте статус перед повтором.",
  form: {
    errorSummary: "Возникла проблема",
    pending: "Запись…",
    reapply: "Применить проверенные изменения",
    yourValue: "Ваш черновик",
    latestValue: "Последнее значение",
    revision: "Версия",
    reference: "Номер",
    recordedAt: "Записано",
    unknown: "Результат не подтверждён",
    draftRetained: "Черновик сохранён. Проверьте статус перед повтором.",
  },
  states: {
    received: "Получено",
    assigned: "Назначено",
    awaiting_client: "Ожидает клиента",
    linked_to_case: "Связано с делом",
    resolved_without_case: "Закрыто без дела",
    suspected_spam: "Возможный спам",
    duplicate_candidate: "Возможный дубликат",
    contact_unreachable: "Контакт недоступен",
    open: "Открыта",
    in_progress: "В работе",
    waiting: "Ожидает",
    done: "Завершена",
    cancelled: "Отменена",
  },
  purposes: {
    question: "Вопрос",
    callback: "Обратный звонок",
    viewing_request: "Запрос просмотра",
    seller_consultation: "Консультация продавца",
    landlord_consultation: "Консультация арендодателя",
    service_consultation: "Консультация по услуге",
  },
  events: {
    "work.inquiry.accepted": "Ответственность принята и следующий шаг записан",
    "work.inquiry.triaged": "Решение по обращению обновлено",
    "inquiry.received": "Обращение получено",
  },
  scopes: {
    all: "Все",
    unassigned: "Свободные",
    mine: "Мои",
    awaiting: "Ожидают клиента",
    review: "На проверке",
  },
  scopeLeads: {
    all: "Выберите разговор и возьмите на себя следующее действие.",
    unassigned: "Разговоры, которые точно никто не взял.",
    mine: "Разговоры, за которые отвечаете вы.",
    awaiting: "Разговоры, в которых ждём ответа клиента.",
    review: "Разговоры на проверке: возможный спам, возможный дубликат или недоступный контакт.",
  },
  scopeEmpty: {
    all: "Нет открытых разговоров",
    unassigned: "Нет подтверждённых свободных разговоров",
    mine: "Вам не назначено ни одного разговора",
    awaiting: "Нет разговоров, ожидающих клиента",
    review: "Нет разговоров на проверке",
  },
  scopeEmptyNotes: {
    all: "Здесь показаны только открытые запросы, доступные вам.",
    unassigned:
      "Неясный ответственный не означает, что разговор свободен. Проверьте замещение, прежде чем взять его.",
    mine: "Разговоры, которые вы примете, появятся здесь.",
    awaiting: "Здесь показаны только открытые запросы, доступные вам.",
    review: "Здесь показаны только открытые запросы, доступные вам.",
  },
  queue: {
    views: "Виды списка запросов",
    list: "Разговоры",
    pages: "Страницы очереди",
    open: "Откройте разговор, чтобы увидеть контекст, ответственного и следующее действие.",
    back: "Назад к запросам",
    skip: "К разговору",
    checkCoverage: "Проверить замещение",
    failed: "Не удалось загрузить очередь",
    failedNote: "Это не значит, что запросов нет. Попробуйте ещё раз чуть позже.",
    retry: "Попробовать ещё раз",
    pageEmpty: "На этой странице нет разговоров.",
    firstPage: "К первой странице",
    search: "Поиск по разговорам",
    searchHint: "Часть имени или полный телефон или email.",
    searchSubmit: "Найти",
    searchBlank: "Введите имя, телефон или email для поиска.",
    searchShort: "Введите не менее 2 символов.",
    searchLong: "Введите не более 120 символов.",
    searchFailed: "Поиск не выполнен. Очередь не изменилась; попробуйте ещё раз.",
    results: "Результаты поиска",
    noResults: "Ни один разговор не подходит под поиск.",
    clearSearch: "Назад к очереди",
    receivedAgo: "Получено {age}",
  },
};
export function workCopy(locale: string): Copy {
  return locale === "bg" ? bg : locale === "ru" ? ru : en;
}
export type WorkCopy = Copy;
