import { renderAdminWorkspace } from "./admin-workflows.mjs";
import { PAYLOAD_ADMIN_ROLES } from "./payload-admin-auth.mjs";

const TEAM_COPY = {
  bg: {
    documentTitle: "Екип · MS Realty",
    title: "Екип и достъп",
    intro: "Управлявай хората, ролите и работните пространства от едно място.",
    created: "Операторът е създаден и трябва да смени паролата си при първото влизане.",
    updated: "Достъпът на оператора е обновен.",
    profileUpdated: "Профилът е обновен.",
    error: "Промяната не беше запазена. Провери данните и опитай отново.",
    newOperator: "Добави човек",
    operators: "Хора и достъп",
    empty: "Още няма оператори.",
    name: "Име",
    email: "Имейл",
    password: "Временна парола",
    passwordHint: "Поне 12 знака. Човекът ще я смени при първото влизане.",
    role: "Роля",
    workspaces: "Работни пространства",
    workspacesHint: "Остави празно за пълен достъп на администратор или въведи идентификатори със запетая.",
    fullAccess: "Всички работни пространства",
    noWorkspace: "Няма зададено работно пространство",
    current: "Ти",
    firstLogin: "Изисква смяна на паролата",
    create: "Създай профил",
    creating: "Създаване…",
    save: "Запази достъпа",
    saving: "Запазване…",
    saved: "Запазено",
    saveFailed: "Промяната не беше запазена.",
    edit: "Редактирай",
    roleNames: { admin: "Администратор", broker: "Брокер", editor: "Редактор", translator: "Преводач" },
  },
  ru: {
    documentTitle: "Команда · MS Realty",
    title: "Команда и доступ",
    intro: "Управляйте людьми, ролями и рабочими пространствами в одном месте.",
    created: "Оператор создан и должен сменить пароль при первом входе.",
    updated: "Доступ оператора обновлён.",
    profileUpdated: "Профиль обновлён.",
    error: "Изменение не сохранено. Проверьте данные и попробуйте снова.",
    newOperator: "Добавить человека",
    operators: "Люди и доступ",
    empty: "Операторов пока нет.",
    name: "Имя",
    email: "Почта",
    password: "Временный пароль",
    passwordHint: "Не менее 12 знаков. Пользователь сменит его при первом входе.",
    role: "Роль",
    workspaces: "Рабочие пространства",
    workspacesHint: "Оставьте пустым для полного доступа администратора или укажите идентификаторы через запятую.",
    fullAccess: "Все рабочие пространства",
    noWorkspace: "Рабочее пространство не назначено",
    current: "Вы",
    firstLogin: "Требуется смена пароля",
    create: "Создать профиль",
    creating: "Создание…",
    save: "Сохранить доступ",
    saving: "Сохранение…",
    saved: "Сохранено",
    saveFailed: "Изменение не сохранено.",
    edit: "Редактировать",
    roleNames: { admin: "Администратор", broker: "Брокер", editor: "Редактор", translator: "Переводчик" },
  },
  en: {
    documentTitle: "Team · MS Realty",
    title: "Team & access",
    intro: "Manage people, roles and workspace access in one place.",
    created: "The operator was created and must change their password on first sign-in.",
    updated: "The operator access was updated.",
    profileUpdated: "The profile was updated.",
    error: "The change was not saved. Check the details and try again.",
    newOperator: "Add person",
    operators: "People & access",
    empty: "No operators yet.",
    name: "Name",
    email: "Email",
    password: "Temporary password",
    passwordHint: "At least 12 characters. The person will replace it on first sign-in.",
    role: "Role",
    workspaces: "Workspaces",
    workspacesHint: "Leave blank for administrator-wide access or enter comma-separated identifiers.",
    fullAccess: "All workspaces",
    noWorkspace: "No workspace assigned",
    current: "You",
    firstLogin: "Password change required",
    create: "Create profile",
    creating: "Creating…",
    save: "Save access",
    saving: "Saving…",
    saved: "Saved",
    saveFailed: "The change was not saved.",
    edit: "Edit",
    roleNames: { admin: "Administrator", broker: "Broker", editor: "Editor", translator: "Translator" },
  },
};

export function renderAdminTeamPayload({
  registry,
  requestedLocale = "en",
  operators = [],
  currentOperatorId = "",
  notice = null,
} = {}) {
  const workspace = renderAdminWorkspace({ registry, requestedLocale });
  const copy = TEAM_COPY[workspace.locale] || TEAM_COPY.en;
  const currentId = String(currentOperatorId ?? "");
  const rows = operators.map((operator) => {
    const workspaceIds = Array.isArray(operator.workspace_ids) ? operator.workspace_ids.map(String).filter(Boolean) : [];
    return {
      ...operator,
      workspace_ids: workspaceIds,
      is_current: String(operator.id ?? "") === currentId,
      full_workspace_access: operator.role === "admin" && workspaceIds.length === 0,
    };
  });
  return {
    kind: "admin_team",
    status: 200,
    locale: workspace.locale,
    lang: workspace.lang,
    dir: workspace.dir,
    path: "/admin/team",
    canonical: "/admin/team",
    indexable: false,
    metadata: { title: copy.documentTitle, description: copy.intro },
    workspace,
    operators: rows,
    team: { copy, roles: PAYLOAD_ADMIN_ROLES, notice },
  };
}
