const en = {
  media: "Listing media",
  documents: "Private property documents",
  caseDocuments: "Restricted case documents",
  backCase: "Back to case",
  service_agreement: "Service agreement",
  express_start: "Express start instruction",
  case_check: "Restricted case check",
  process_policy: "Approved process policy evidence",
  case_completion: "Agency outcome evidence",
  back: "Back to listing",
  upload: "Upload a file",
  file: "Choose a file",
  kind: "Image type",
  photo: "Photograph",
  floor_plan: "Floor plan",
  render: "Render",
  imageLimit:
    "JPEG, PNG or WebP. Maximum 25 MB. Originals remain private. A clean scan, safe derivative and human rights/privacy review are required before publication.",
  documentLimit:
    "PDF, JPEG, PNG or WebP. Maximum 20 MB. These files are internal evidence. A malware scan, review for the named purpose and professional validation are separate checks.",
  submit: "Upload and scan",
  resume: "Continue upload",
  retry: "Retry scan",
  refresh: "Refresh status",
  scan: "Malware scan",
  processing: "Safe image processing",
  review: "Human review",
  rights: "Usage rights",
  pending: "Pending",
  clean: "Clean",
  infected: "Unsafe — quarantined",
  failed: "Could not complete — quarantined",
  ready: "Ready",
  approved: "Approved for the stated scope",
  rejected: "Rejected",
  cleared: "Cleared for the stated use",
  restricted: "Restricted",
  unknown: "Not reviewed",
  private: "Private",
  public_candidate: "Publication candidate",
  audience: "Audience",
  reviewAction: "Record review",
  original: "Download private original",
  preview: "Metadata-stripped preview",
  rightsHolder: "Rights holder",
  rightsReference: "Rights evidence / permission reference",
  caption: "Visible caption",
  altText: "Image description",
  modification: "Image modification",
  disclosure: "Visible modification disclosure",
  privacy:
    "I reviewed private addresses, people, documents and location details in the visible image.",
  rightsCheck: "I reviewed the stated usage rights and permission evidence.",
  decision: "Decision",
  approve: "Approve as a public candidate",
  reject: "Reject / withdraw public permission",
  none: "None",
  retouched: "Retouched",
  virtually_staged: "Virtually staged",
  renovation_render: "Renovation render",
  redrawn_plan: "Redrawn plan",
  up: "Move earlier",
  down: "Move later",
  hide: "Hide from next gallery",
  show: "Include in next gallery",
  hidden: "Hidden placement",
  purpose: "Purpose",
  seller_authority: "Seller authority evidence",
  seller_instruction: "Signed seller instructions",
  property_evidence: "Property evidence",
  other: "Other",
  classification: "Document class",
  identity: "Identity",
  title: "Title / ownership evidence",
  financial: "Financial",
  contract: "Contract",
  property: "Property",
  replace: "Replace with a new version",
  note: "Review note and scope",
  accepted_for_purpose: "Accepted for the named purpose",
  needs_replacement: "Needs replacement",
  reviewed_with_open_questions: "Reviewed with open questions",
  expiry: "Expiry date, if applicable",
  documentCheck:
    "I reviewed this exact version for the stated purpose. This records my review, not legal verification.",
  saved: "Saved. The current scan and review states are shown below.",
  error: "The result could not be confirmed. Refresh and check the current item before retrying.",
  conflict: "This item changed. Refresh and review the latest version before trying again.",
  unavailable:
    "The storage or scanner is unavailable. Files remain private; retry after the service is available.",
  expired: "Upload permission expired. Start a new upload.",
  empty: "No files have been added.",
  denied:
    "You do not have the capability to add or review documents. An access manager can grant it explicitly.",
  version: "Version",
  state: "Upload and review state",
  uploading: "Awaiting upload",
  selected: "Selected",
  uploaded: "Received; awaiting sealing",
  sealed: "Sealed; awaiting scan",
  scanning: "Scanning / awaiting scanner",
  ready_for_review: "Ready for scoped human review",
  reviewed: "Human review recorded",
  superseded: "Replaced by a newer version",
  expiredDocument: "Expired",
  permission:
    "Publication eligibility is separate from being live. Freeze and review a new listing revision to use gallery changes.",
  orderTitle: "Media and order",
  orderLead: "Put the photos in the order you want, then save the order.",
  photoMeta: "Listing {reference} · Photo {n} of {total}",
  allPhotos: "All {total} photos",
  showPhoto: "Show photo {n}",
  firstAlready: "Already the first photo",
  lastAlready: "Already the last photo",
  moveUp: "Move up",
  moveDown: "Move down",
  noPreview: "No preview until the scan and safe processing finish.",
  photoChecks: "Checks and rights for this photo",
  reviewOrder: "Review the new order",
  reviewLead: "{reference} · Photo order → new draft. Photo {n} moves one place {direction}.",
  directionUp: "up",
  directionDown: "down",
  coverBefore: "Before · cover {n}",
  coverAfter: "After · cover {n}",
  before: "Before",
  proposal: "Proposal",
  unchanged: "Unchanged",
  unchangedDetail: "Original files and rights; publishing needs its own review",
  saveOrder: "Save the order",
  cancel: "Cancel",
  close: "Close",
  orderSaved: "The new order is saved",
  orderSavedDetail:
    "{reference} · The draft gallery now has this photo in place {n} of {total}. The public listing has not changed.",
  toTask: "Back to the current task",
};
type FileCopy = typeof en;
const bg: FileCopy = {
  ...en,
  media: "Медия за обявата",
  documents: "Поверителни документи за имота",
  caseDocuments: "Ограничени документи по случая",
  backCase: "Назад към случая",
  service_agreement: "Договор за услуга",
  express_start: "Изрично искане за начало",
  case_check: "Ограничена проверка по случая",
  process_policy: "Доказателство за одобрен процес",
  case_completion: "Доказателство за резултата по случая",
  back: "Назад към обявата",
  upload: "Качване на файл",
  file: "Изберете файл",
  kind: "Вид изображение",
  photo: "Снимка",
  floor_plan: "План",
  render: "Визуализация",
  imageLimit:
    "JPEG, PNG или WebP, до 25 MB. Оригиналите остават поверителни. Преди публикуване са нужни чисто сканиране, безопасно изображение и човешки преглед на правата и личните данни.",
  documentLimit:
    "PDF, JPEG, PNG или WebP, до 20 MB. Файловете са вътрешни доказателства. Сканирането за зловреден код, прегледът за целта и професионалната проверка са отделни стъпки.",
  submit: "Качване и сканиране",
  resume: "Продължете качването",
  retry: "Повторете сканирането",
  refresh: "Обновете състоянието",
  scan: "Сканиране за зловреден код",
  processing: "Безопасна обработка",
  review: "Човешки преглед",
  rights: "Права за използване",
  pending: "Предстои",
  clean: "Чисто",
  infected: "Опасно — под карантина",
  failed: "Не е завършено — под карантина",
  ready: "Готово",
  approved: "Одобрено за посочения обхват",
  rejected: "Отхвърлено",
  cleared: "Уредени за посочената употреба",
  restricted: "Ограничени",
  unknown: "Непрегледано",
  private: "Поверително",
  public_candidate: "Кандидат за публикуване",
  audience: "Достъп",
  reviewAction: "Запишете прегледа",
  original: "Изтеглете поверителния оригинал",
  preview: "Преглед без метаданни",
  rightsHolder: "Носител на правата",
  rightsReference: "Доказателство за права / разрешение",
  caption: "Видим надпис",
  altText: "Описание на изображението",
  modification: "Промяна на изображението",
  disclosure: "Видимо описание на промяната",
  privacy:
    "Прегледах адресите, хората, документите и данните за местоположението във видимото изображение.",
  rightsCheck: "Прегледах посочените права и доказателството за разрешение.",
  decision: "Решение",
  approve: "Одобрете за публичен кандидат",
  reject: "Отхвърлете / оттеглете разрешението",
  none: "Няма",
  retouched: "Ретуширано",
  virtually_staged: "Виртуално обзаведено",
  renovation_render: "Визуализация на ремонт",
  redrawn_plan: "Пречертан план",
  up: "Преместете по-рано",
  down: "Преместете по-късно",
  hide: "Скрийте от следващата галерия",
  show: "Включете в следващата галерия",
  hidden: "Скрито място",
  purpose: "Цел",
  seller_authority: "Доказателство за правомощия на продавача",
  seller_instruction: "Подписани указания на продавача",
  property_evidence: "Доказателства за имота",
  other: "Друго",
  classification: "Вид документ",
  identity: "Самоличност",
  title: "Собственост",
  financial: "Финансов",
  contract: "Договор",
  property: "Имот",
  replace: "Заменете с нова версия",
  note: "Бележка и обхват на прегледа",
  accepted_for_purpose: "Приет за посочената цел",
  needs_replacement: "Нужна е замяна",
  reviewed_with_open_questions: "Прегледан с отворени въпроси",
  expiry: "Крайна дата, ако е приложима",
  documentCheck:
    "Прегледах точно тази версия за посочената цел. Това записва моя преглед, а не правна проверка.",
  saved: "Записано. Текущите състояния на сканиране и преглед са показани по-долу.",
  error: "Резултатът не е потвърден. Обновете и проверете състоянието, преди да опитате отново.",
  conflict: "Има промяна. Обновете и прегледайте новата версия преди повторен опит.",
  unavailable:
    "Хранилището или скенерът не е достъпен. Файловете остават поверителни; опитайте след възстановяване на услугата.",
  expired: "Разрешението за качване изтече. Започнете ново качване.",
  empty: "Няма добавени файлове.",
  denied:
    "Нямате право да добавяте или преглеждате документи. Мениджърът по достъпа може да го предостави изрично.",
  version: "Версия",
  state: "Състояние на качване и преглед",
  uploading: "Очаква се качване",
  selected: "Избрано",
  uploaded: "Получено; очаква се запечатване",
  sealed: "Запечатано; очаква се сканиране",
  scanning: "Сканиране / изчакване на скенера",
  ready_for_review: "Готово за целеви човешки преглед",
  reviewed: "Записан човешки преглед",
  superseded: "Заменено с по-нова версия",
  expiredDocument: "Изтекло",
  permission:
    "Готовността за публикуване не означава, че медията е на сайта. Подгответе и прегледайте нова версия на обявата, за да използвате промените в галерията.",
  orderTitle: "Медии и подредба",
  orderLead: "Подредете снимките в желания ред и запазете подредбата.",
  photoMeta: "Имот {reference} · Снимка {n} от {total}",
  allPhotos: "Всички {total} снимки",
  showPhoto: "Покажете снимка {n}",
  firstAlready: "Вече е първа снимка",
  lastAlready: "Вече е последна снимка",
  moveUp: "Преместете нагоре",
  moveDown: "Преместете надолу",
  noPreview: "Няма преглед, докато сканирането и безопасната обработка не завършат.",
  photoChecks: "Проверки и права за снимката",
  reviewOrder: "Преглед на новата подредба",
  reviewLead:
    "{reference} · Подредба на снимките → нова чернова. Снимка {n} се премества една позиция {direction}.",
  directionUp: "нагоре",
  directionDown: "надолу",
  coverBefore: "Преди · корица №{n}",
  coverAfter: "След · корица №{n}",
  before: "Преди",
  proposal: "Предложение",
  unchanged: "Непроменено",
  unchangedDetail: "Оригиналните файлове и права; публикуването изисква отделен преглед",
  saveOrder: "Запишете подредбата",
  cancel: "Отказ",
  close: "Затваряне",
  orderSaved: "Новата подредба е записана",
  orderSavedDetail:
    "{reference} · В черновата галерия снимката вече е на място {n} от {total}. Публичната обява не е променена.",
  toTask: "Към текущата задача",
};
const ru: FileCopy = {
  media: "Медиа объявления",
  documents: "Конфиденциальные документы по объекту",
  caseDocuments: "Документы сделки с ограниченным доступом",
  backCase: "Назад к сделке",
  service_agreement: "Договор об услугах",
  express_start: "Явная просьба начать работу",
  case_check: "Проверка по сделке с ограниченным доступом",
  process_policy: "Подтверждение утверждённого процесса",
  case_completion: "Подтверждение результата по сделке",
  back: "Назад к объявлению",
  upload: "Загрузка файла",
  file: "Выберите файл",
  kind: "Тип изображения",
  photo: "Фотография",
  floor_plan: "Планировка",
  render: "Визуализация",
  imageLimit:
    "JPEG, PNG или WebP, до 25 МБ. Оригиналы остаются конфиденциальными. Перед публикацией нужны чистая проверка на вредоносный код, безопасная копия и проверка прав и личных данных человеком.",
  documentLimit:
    "PDF, JPEG, PNG или WebP, до 20 МБ. Это внутренние подтверждающие файлы. Проверка на вредоносный код, проверка для указанной цели и профессиональная проверка — отдельные шаги.",
  submit: "Загрузить и проверить",
  resume: "Продолжить загрузку",
  retry: "Повторить проверку",
  refresh: "Обновить состояние",
  scan: "Проверка на вредоносный код",
  processing: "Безопасная обработка",
  review: "Проверка человеком",
  rights: "Права на использование",
  pending: "Ожидает",
  clean: "Чисто",
  infected: "Опасно — в карантине",
  failed: "Не завершено — в карантине",
  ready: "Готово",
  approved: "Одобрено для указанного объёма",
  rejected: "Отклонено",
  cleared: "Подтверждены для указанного использования",
  restricted: "Ограничены",
  unknown: "Не проверено",
  private: "Конфиденциально",
  public_candidate: "Кандидат на публикацию",
  audience: "Доступ",
  reviewAction: "Записать проверку",
  original: "Скачать конфиденциальный оригинал",
  preview: "Просмотр без метаданных",
  rightsHolder: "Правообладатель",
  rightsReference: "Подтверждение прав / разрешения",
  caption: "Видимая подпись",
  altText: "Описание изображения",
  modification: "Изменение изображения",
  disclosure: "Видимое описание изменения",
  privacy:
    "Я проверил(а) адреса, людей, документы и данные о местоположении на видимом изображении.",
  rightsCheck: "Я проверил(а) указанные права и подтверждение разрешения.",
  decision: "Решение",
  approve: "Одобрить как кандидата на публикацию",
  reject: "Отклонить / отозвать разрешение",
  none: "Нет",
  retouched: "Отретушировано",
  virtually_staged: "Виртуально обставлено",
  renovation_render: "Визуализация ремонта",
  redrawn_plan: "Перерисованная планировка",
  up: "Переместить раньше",
  down: "Переместить позже",
  hide: "Скрыть из следующей галереи",
  show: "Включить в следующую галерею",
  hidden: "Скрытое место",
  purpose: "Цель",
  seller_authority: "Подтверждение полномочий продавца",
  seller_instruction: "Подписанные указания продавца",
  property_evidence: "Подтверждения по объекту",
  other: "Другое",
  classification: "Тип документа",
  identity: "Личность",
  title: "Право собственности",
  financial: "Финансовый",
  contract: "Договор",
  property: "Объект",
  replace: "Заменить новой версией",
  note: "Заметка и объём проверки",
  accepted_for_purpose: "Принят для указанной цели",
  needs_replacement: "Нужна замена",
  reviewed_with_open_questions: "Проверен, есть открытые вопросы",
  expiry: "Срок действия, если есть",
  documentCheck:
    "Я проверил(а) именно эту версию для указанной цели. Это запись моей проверки, а не юридическая проверка.",
  saved: "Сохранено. Текущие состояния проверки показаны ниже.",
  error:
    "Результат не подтверждён. Обновите страницу и проверьте состояние перед повторной попыткой.",
  conflict:
    "Здесь есть изменения. Обновите страницу и проверьте новую версию перед повторной попыткой.",
  unavailable:
    "Хранилище или сканер недоступны. Файлы остаются конфиденциальными; повторите попытку после восстановления сервиса.",
  expired: "Разрешение на загрузку истекло. Начните новую загрузку.",
  empty: "Файлы ещё не добавлены.",
  denied:
    "У вас нет права добавлять или проверять документы. Менеджер доступа может выдать его явно.",
  version: "Версия",
  state: "Состояние загрузки и проверки",
  uploading: "Ожидает загрузки",
  selected: "Выбрано",
  uploaded: "Получено; ожидает запечатывания",
  sealed: "Запечатано; ожидает проверки",
  scanning: "Проверка / ожидание сканера",
  ready_for_review: "Готово к проверке человеком",
  reviewed: "Проверка человеком записана",
  superseded: "Заменено более новой версией",
  expiredDocument: "Истёк",
  permission:
    "Готовность к публикации не означает, что медиа уже на сайте. Подготовьте и проверьте новую версию объявления, чтобы использовать изменения галереи.",
  orderTitle: "Медиа и порядок",
  orderLead: "Расставьте фотографии в нужном порядке и сохраните порядок.",
  photoMeta: "Объект {reference} · Фото {n} из {total}",
  allPhotos: "Все фото: {total}",
  showPhoto: "Показать фото {n}",
  firstAlready: "Уже первое фото",
  lastAlready: "Уже последнее фото",
  moveUp: "Переместить выше",
  moveDown: "Переместить ниже",
  noPreview: "Просмотра нет, пока не завершены проверка и безопасная обработка.",
  photoChecks: "Проверки и права на это фото",
  reviewOrder: "Проверка нового порядка",
  reviewLead:
    "{reference} · Порядок фото → новый черновик. Фото {n} перемещается на одно место {direction}.",
  directionUp: "выше",
  directionDown: "ниже",
  coverBefore: "До · обложка №{n}",
  coverAfter: "После · обложка №{n}",
  before: "До",
  proposal: "Предложение",
  unchanged: "Без изменений",
  unchangedDetail: "Исходные файлы и права; публикация требует отдельной проверки",
  saveOrder: "Сохранить порядок",
  cancel: "Отмена",
  close: "Закрыть",
  orderSaved: "Новый порядок сохранён",
  orderSavedDetail:
    "{reference} · В черновой галерее это фото теперь на месте {n} из {total}. Публичное объявление не изменилось.",
  toTask: "К текущей задаче",
};
export const filesCopy = (locale: string): FileCopy =>
  locale === "bg" ? bg : locale === "ru" ? ru : en;
/** Fills `{name}` placeholders; values are already display text. */
export function fillCopy(template: string, values: Record<string, string | number>) {
  return template.replace(/\{(\w+)\}/g, (match, key: string) =>
    key in values ? String(values[key]) : match,
  );
}
export function fileLabel(copy: FileCopy, value: string) {
  return value === "expired" ? copy.expiredDocument : (copy[value as keyof FileCopy] ?? value);
}
export function fileError(copy: FileCopy, code: string | undefined) {
  return code === "REVISION_CONFLICT"
    ? copy.conflict
    : code === "DEPENDENCY_UNAVAILABLE"
      ? copy.unavailable
      : copy.error;
}
