const en = {
  title: "Document requests",
  create: "Request a document",
  empty: "No document requests.",
  purpose: "Why this document is needed",
  instructions: "What to provide",
  alternatives: "Acceptable alternatives",
  recipient: "Recipient",
  policy: "Approved process policy",
  name: "Request title",
  classification: "Document class",
  types: "Allowed file types",
  limit: "Maximum bytes",
  expires: "Request expires (Europe/Sofia)",
  audience:
    "Visible only to the named recipient and authorized agency reviewers. Case participation does not share this file with other participants.",
  upload: "Upload and scan",
  file: "Choose a file",
  review: "Record review",
  internal: "Internal review note — agency staff only",
  outcome: "Outcome shown to the recipient",
  confirm: "I reviewed this exact version for the stated purpose.",
  cancel: "Cancel request and file access",
  refresh: "Refresh status",
  back: "Open case",
  pending: "No file supplied yet",
  cancelled: "This request was cancelled. File access has ended.",
  expired: "This request has expired. Ask your broker to review what is still needed.",
  safety:
    "Upload, malware scan, review for the stated purpose and professional validation are separate steps. Leaving this page does not promise a background upload.",
  saved: "File transfer is recorded. The scan and review states below are authoritative.",
  failed:
    "The result could not be confirmed. Check current status before retrying. File selection must be repeated after a failed transfer.",
  processing: "The file is being processed. Refresh to read the current scan state.",
  unavailable:
    "No new upload is currently permitted. Contact the responsible broker if you need help.",
  requests: "Open document requests",
  download: "Download current permitted file",
  current: "Open current record",
};
const bg: typeof en = {
  ...en,
  title: "Заявки за документи",
  create: "Поискване на документ",
  empty: "Няма заявки за документи.",
  purpose: "Защо е необходим документът",
  instructions: "Какво да предоставите",
  alternatives: "Допустими алтернативи",
  recipient: "Получател",
  policy: "Одобрена процесна политика",
  name: "Заглавие на заявката",
  classification: "Вид документ",
  types: "Допустими файлове",
  limit: "Максимален размер в байтове",
  expires: "Срок на заявката (Europe/Sofia)",
  audience:
    "Видимо само за посочения получател и оправомощените проверяващи от агенцията. Участието в случая не споделя файла с останалите участници.",
  upload: "Качване и проверка",
  file: "Избор на файл",
  review: "Запис на прегледа",
  internal: "Вътрешна бележка — само за служители",
  outcome: "Резултат, видим за получателя",
  confirm: "Прегледах точно тази версия за посочената цел.",
  cancel: "Отмяна на заявката и достъпа до файла",
  refresh: "Обновяване на състоянието",
  back: "Отваряне на случая",
  pending: "Още няма предоставен файл",
  cancelled: "Заявката е отменена. Достъпът до файла е прекратен.",
  expired: "Срокът е изтекъл. Свържете се с брокера за преглед на необходимото.",
  safety:
    "Качването, проверката за зловреден код, прегледът за целта и професионалната проверка са отделни стъпки. Напускането на страницата не гарантира качване във фонов режим.",
  saved: "Предаването е записано. Текущите състояния на проверката и прегледа са показани по-долу.",
  failed:
    "Резултатът не е потвърден. Проверете състоянието преди нов опит. След неуспешно предаване изберете файла отново.",
  processing: "Файлът се обработва. Обновете за текущото състояние.",
  unavailable: "В момента не е разрешено ново качване. При нужда се свържете с брокера.",
  requests: "Отваряне на заявките за документи",
  download: "Изтегляне на текущия разрешен файл",
  current: "Отваряне на текущия запис",
};
const ru: typeof en = {
  ...en,
  title: "Запросы документов",
  create: "Запросить документ",
  empty: "Нет запросов документов.",
  purpose: "Для чего нужен документ",
  instructions: "Что предоставить",
  alternatives: "Допустимые альтернативы",
  recipient: "Получатель",
  policy: "Утверждённая политика процесса",
  name: "Название запроса",
  classification: "Класс документа",
  types: "Допустимые типы файлов",
  limit: "Максимальный размер в байтах",
  expires: "Срок запроса (Europe/Sofia)",
  audience:
    "Доступ только у указанного получателя и уполномоченных сотрудников агентства. Участие в деле не открывает файл другим участникам.",
  upload: "Загрузить и проверить",
  file: "Выбрать файл",
  review: "Записать результат проверки",
  internal: "Внутренняя заметка — только сотрудники",
  outcome: "Результат для получателя",
  confirm: "Я проверил именно эту версию для указанной цели.",
  cancel: "Отменить запрос и доступ к файлу",
  refresh: "Обновить статус",
  back: "Открыть дело",
  pending: "Файл ещё не предоставлен",
  cancelled: "Запрос отменён. Доступ к файлу прекращён.",
  expired: "Срок запроса истёк. Обсудите с брокером, что ещё нужно.",
  safety:
    "Передача файла, антивирусная проверка, проверка для указанной цели и профессиональное заключение — отдельные этапы. Уход со страницы не гарантирует фоновую загрузку.",
  saved: "Передача записана. Текущие статусы проверки показаны ниже.",
  failed:
    "Результат не подтверждён. Проверьте статус перед повтором. После неудачной передачи файл нужно выбрать заново.",
  processing: "Файл обрабатывается. Обновите страницу для текущего статуса.",
  unavailable: "Новая загрузка сейчас недоступна. При необходимости обратитесь к брокеру.",
  requests: "Открыть запросы документов",
  download: "Скачать текущий разрешённый файл",
  current: "Открыть текущую запись",
};
export const documentRequestCopy = (locale: string) =>
  locale === "bg" ? bg : locale === "ru" ? ru : en;
