import type { PublicLocale } from "@/i18n/config";

// Interface labels only; local facts and guide prose require the CMS's human decisions.
type Row = readonly [string, string, string, string, string, string, string];
const rows = {
  sale: ["Продажба", "For sale", "Продажа", "Zum Kauf", "Te koop", "Πώληση", "למכירה"],
  long_term_rent: [
    "Дългосрочен наем",
    "Long-term rent",
    "Долгосрочная аренда",
    "Langzeitmiete",
    "Langdurige huur",
    "Μακροχρόνια μίσθωση",
    "שכירות לטווח ארוך",
  ],
  title: [
    "За района",
    "About the area",
    "О районе",
    "Über die Region",
    "Over de omgeving",
    "Για την περιοχή",
    "על האזור",
  ],
  headline: [
    "Изберете място за Вашето ежедневие.",
    "Choose a place for everyday life.",
    "Выберите место для повседневной жизни.",
    "Wählen Sie einen Ort für Ihren Alltag.",
    "Kies een plek voor het dagelijks leven.",
    "Επιλέξτε έναν τόπο για την καθημερινότητά σας.",
    "בחרו מקום לחיי היומיום.",
  ],
  intro: [
    "Разгледайте публикуваните имоти и одобрената информация за местата. Обсъдете местоположението и ежедневните си нужди с екипа.",
    "Explore published properties and approved place guides. Discuss the location and your everyday needs with the team.",
    "Посмотрите опубликованные объекты и одобренные сведения о местах. Обсудите расположение и повседневные потребности с командой.",
    "Entdecken Sie veröffentlichte Immobilien und freigegebene Ortsinformationen. Besprechen Sie Lage und Alltagsbedürfnisse mit dem Team.",
    "Bekijk gepubliceerde woningen en goedgekeurde plaatsinformatie. Bespreek de locatie en uw dagelijkse behoeften met het team.",
    "Δείτε δημοσιευμένα ακίνητα και εγκεκριμένες πληροφορίες τόπων. Συζητήστε την τοποθεσία και τις καθημερινές σας ανάγκες με την ομάδα.",
    "עיינו בנכסים שפורסמו ובמידע מאושר על המקומות. שוחחו עם הצוות על המיקום ועל הצרכים היומיומיים שלכם.",
  ],
  contact: [
    "Свържете се с нас",
    "Contact us",
    "Свяжитесь с нами",
    "Kontaktieren Sie uns",
    "Neem contact op",
    "Επικοινωνήστε μαζί μας",
    "צרו קשר",
  ],
  source: [
    "Прочетете одобрената информация на български",
    "Read approved information in Bulgarian",
    "Прочитать одобренную информацию на болгарском",
    "Freigegebene Informationen auf Bulgarisch lesen",
    "Lees goedgekeurde informatie in het Bulgaars",
    "Διαβάστε εγκεκριμένες πληροφορίες στα βουλγαρικά",
    "קראו מידע מאושר בבולגרית",
  ],
  browse: [
    "Разгледайте имотите",
    "Explore properties",
    "Посмотрите объекты",
    "Immobilien ansehen",
    "Bekijk woningen",
    "Δείτε τα ακίνητα",
    "עיינו בנכסים",
  ],
  everyday: [
    "Опознайте района през Вашето ежедневие",
    "Explore the area through your everyday needs",
    "Узнайте район через повседневные потребности",
    "Lernen Sie die Region für Ihren Alltag kennen",
    "Leer de omgeving kennen vanuit uw dagelijks leven",
    "Γνωρίστε την περιοχή μέσα από τις καθημερινές σας ανάγκες",
    "הכירו את האזור דרך הצרכים היומיומיים שלכם",
  ],
  places: [
    "Местата и одобрените справочници",
    "Places and approved guides",
    "Места и одобренные справочники",
    "Orte und freigegebene Ratgeber",
    "Plaatsen en goedgekeurde gidsen",
    "Τόποι και εγκεκριμένοι οδηγοί",
    "מקומות ומדריכים מאושרים",
  ],
  placesHint: [
    "Изберете място в търсенето или прочетете одобрената информация",
    "Choose a place in search or read approved information",
    "Выберите место в поиске или прочитайте одобренные сведения",
    "Wählen Sie einen Ort in der Suche oder lesen Sie freigegebene Informationen",
    "Kies een plaats bij het zoeken of lees goedgekeurde informatie",
    "Επιλέξτε τόπο στην αναζήτηση ή διαβάστε εγκεκριμένες πληροφορίες",
    "בחרו מקום בחיפוש או קראו מידע מאושר",
  ],
  access: [
    "Достъп и ежедневни нужди",
    "Access and everyday needs",
    "Доступ и повседневные потребности",
    "Zugang und Alltagsbedürfnisse",
    "Bereikbaarheid en dagelijkse behoeften",
    "Πρόσβαση και καθημερινές ανάγκες",
    "גישה וצרכים יומיומיים",
  ],
  accessHint: [
    "Обсъдете транспорт, паркиране и достъп с екипа",
    "Discuss transport, parking and access with the team",
    "Обсудите транспорт, парковку и доступ с командой",
    "Besprechen Sie Verkehr, Parken und Zugang mit dem Team",
    "Bespreek vervoer, parkeren en toegang met het team",
    "Συζητήστε μεταφορές, στάθμευση και πρόσβαση με την ομάδα",
    "שוחחו עם הצוות על תחבורה, חניה וגישה",
  ],
  visit: [
    "Вижте мястото лично",
    "See the place in person",
    "Посмотрите место лично",
    "Sehen Sie den Ort persönlich",
    "Bekijk de plek zelf",
    "Δείτε τον τόπο από κοντά",
    "ראו את המקום בעצמכם",
  ],
  visitHint: [
    "Изберете конкретен имот и изпратете предпочитан час за оглед",
    "Choose a property and send your preferred viewing time",
    "Выберите объект и отправьте предпочтительное время просмотра",
    "Wählen Sie eine Immobilie und senden Sie Ihren Besichtigungsterminwunsch",
    "Kies een woning en stuur uw gewenste bezichtigingstijd",
    "Επιλέξτε ακίνητο και στείλτε την προτιμώμενη ώρα επίσκεψης",
    "בחרו נכס ושלחו את מועד הביקור המועדף עליכם",
  ],
  guides: [
    "Одобрена информация",
    "Approved information",
    "Одобренная информация",
    "Freigegebene Informationen",
    "Goedgekeurde informatie",
    "Εγκεκριμένες πληροφορίες",
    "מידע מאושר",
  ],
  inventory: [
    "Публикувани имоти по местоположение",
    "Published properties by location",
    "Опубликованные объекты по местоположению",
    "Veröffentlichte Immobilien nach Ort",
    "Gepubliceerde woningen per plaats",
    "Δημοσιευμένα ακίνητα ανά τοποθεσία",
    "נכסים שפורסמו לפי מיקום",
  ],
  noGuides: [
    "Одобрена информация за районите все още не е достъпна.",
    "Approved area information is not available yet.",
    "Одобренная информация о районах пока недоступна.",
    "Freigegebene Ortsinformationen sind noch nicht verfügbar.",
    "Goedgekeurde gebiedsinformatie is nog niet beschikbaar.",
    "Δεν υπάρχουν ακόμη εγκεκριμένες πληροφορίες περιοχών.",
    "מידע מאושר על האזורים עדיין אינו זמין.",
  ],
  noTranslation: [
    "Одобрен превод все още не е достъпен.",
    "An approved translation is not available yet.",
    "Одобренный перевод пока недоступен.",
    "Eine freigegebene Übersetzung ist noch nicht verfügbar.",
    "Een goedgekeurde vertaling is nog niet beschikbaar.",
    "Δεν υπάρχει ακόμη εγκεκριμένη μετάφραση.",
    "תרגום מאושר עדיין אינו זמין.",
  ],
  noInventory: [
    "В момента няма публикувани имоти за това местоположение.",
    "There are currently no published properties for this location.",
    "Для этого места сейчас нет опубликованных объектов.",
    "Für diesen Ort sind derzeit keine Immobilien veröffentlicht.",
    "Er zijn momenteel geen gepubliceerde woningen voor deze plaats.",
    "Δεν υπάρχουν δημοσιευμένα ακίνητα για αυτή την τοποθεσία αυτή τη στιγμή.",
    "כרגע אין נכסים שפורסמו במיקום זה.",
  ],
  noLocations: [
    "В момента няма публикувани имоти, от които да покажем местоположения.",
    "There are currently no published properties from which to show locations.",
    "Сейчас нет опубликованных объектов, по которым можно показать места.",
    "Derzeit sind keine Immobilien veröffentlicht, deren Orte wir anzeigen können.",
    "Er zijn momenteel geen gepubliceerde woningen om plaatsen bij te tonen.",
    "Δεν υπάρχουν δημοσιευμένα ακίνητα από τα οποία να εμφανιστούν τοποθεσίες.",
    "כרגע אין נכסים שפורסמו שניתן להציג מהם מיקומים.",
  ],
  noBinding: [
    "За тази страница няма потвърдена връзка с местоположение в търсенето.",
    "This guide has no confirmed link to a search location.",
    "У этой страницы нет подтвержденной связи с местом в поиске.",
    "Dieser Ratgeber ist keinem bestätigten Suchort zugeordnet.",
    "Deze gids heeft geen bevestigde koppeling met een zoeklocatie.",
    "Αυτός ο οδηγός δεν έχει επιβεβαιωμένη σύνδεση με τοποθεσία αναζήτησης.",
    "למדריך זה אין קישור מאושר למיקום בחיפוש.",
  ],
  scope: [
    "Обхват на прегледа",
    "Review scope",
    "Область проверки",
    "Prüfumfang",
    "Reikwijdte van beoordeling",
    "Πεδίο ελέγχου",
    "היקף הבדיקה",
  ],
  readGuide: [
    "Прочетете справочника",
    "Read the guide",
    "Прочитайте справочник",
    "Ratgeber lesen",
    "Lees de gids",
    "Διαβάστε τον οδηγό",
    "קראו את המדריך",
  ],
  photograph: [
    "Снимка от публикуван имот",
    "Photograph from a published property",
    "Фото из опубликованного объекта",
    "Foto einer veröffentlichten Immobilie",
    "Foto van een gepubliceerde woning",
    "Φωτογραφία από δημοσιευμένο ακίνητο",
    "תמונה מנכס שפורסם",
  ],
  noPhotograph: [
    "Няма достъпна одобрена снимка от текущите имоти.",
    "No approved photograph is available from current properties.",
    "Среди текущих объектов нет доступного одобренного фото.",
    "Für aktuelle Immobilien ist kein freigegebenes Foto verfügbar.",
    "Er is geen goedgekeurde foto beschikbaar van huidige woningen.",
    "Δεν υπάρχει διαθέσιμη εγκεκριμένη φωτογραφία από τα τρέχοντα ακίνητα.",
    "אין תמונה מאושרת זמינה מהנכסים הנוכחיים.",
  ],
  contents: [
    "В този справочник",
    "In this guide",
    "В этом справочнике",
    "In diesem Ratgeber",
    "In deze gids",
    "Σε αυτόν τον οδηγό",
    "במדריך זה",
  ],
  section: ["Раздел", "Section", "Раздел", "Abschnitt", "Onderdeel", "Ενότητα", "סעיף"],
  refresh: [
    "Опитайте отново",
    "Try again",
    "Попробуйте снова",
    "Erneut versuchen",
    "Probeer opnieuw",
    "Δοκιμάστε ξανά",
    "נסו שוב",
  ],
  settlement: [
    "Населено място",
    "Locality",
    "Населённый пункт",
    "Ortschaft",
    "Plaats",
    "Οικισμός",
    "יישוב",
  ],
  municipality: [
    "Община",
    "Municipality",
    "Муниципалитет",
    "Gemeinde",
    "Gemeente",
    "Δήμος",
    "רשות מקומית",
  ],
  district: ["Област", "District", "Область", "Bezirk", "District", "Περιφέρεια", "מחוז"],
  neighborhood: [
    "Квартал",
    "Neighbourhood",
    "Квартал",
    "Stadtviertel",
    "Buurt",
    "Γειτονιά",
    "שכונה",
  ],
  country: ["Държава", "Country", "Страна", "Land", "Land", "Χώρα", "מדינה"],
} satisfies Record<string, Row>;
const locales = ["bg", "en", "ru", "de", "nl", "el", "he"] as const;
export function areaCopy(locale: PublicLocale) {
  const index = locales.indexOf(locale);
  return Object.fromEntries(Object.entries(rows).map(([key, row]) => [key, row[index]])) as {
    [K in keyof typeof rows]: string;
  };
}
