import type { PublicLocale } from "@/i18n/config";

const labels = {
  title: [
    "Сравнете важните разлики",
    "Compare the important differences",
    "Сравните важные различия",
    "Wichtige Unterschiede vergleichen",
    "Vergelijk de belangrijke verschillen",
    "Συγκρίνετε τις σημαντικές διαφορές",
    "השוו את ההבדלים החשובים",
  ],
  lead: [
    "Фактите идват от текущите обяви; неизвестното е обозначено.",
    "Facts come from current listings; unknown information is marked.",
    "Данные взяты из текущих объявлений; неизвестное отмечено.",
    "Die Angaben stammen aus aktuellen Angeboten; Unbekanntes ist gekennzeichnet.",
    "Feiten komen uit actuele advertenties; onbekende informatie is aangegeven.",
    "Τα στοιχεία προέρχονται από τις τρέχουσες αγγελίες· οι άγνωστες πληροφορίες επισημαίνονται.",
    "הנתונים מגיעים מהמודעות העדכניות; מידע לא ידוע מסומן.",
  ],
  selected: [
    "Сравнявани имоти",
    "Properties compared",
    "Сравниваемые объекты",
    "Verglichene Immobilien",
    "Vergeleken woningen",
    "Ακίνητα προς σύγκριση",
    "נכסים בהשוואה",
  ],
  property: ["Имот", "Property", "Объект", "Immobilie", "Woning", "Ακίνητο", "נכס"],
  price: [
    "Обявена цена",
    "Listed price",
    "Цена в объявлении",
    "Angebotspreis",
    "Advertentieprijs",
    "Τιμή αγγελίας",
    "מחיר במודעה",
  ],
  location: ["Район", "Location", "Район", "Lage", "Locatie", "Περιοχή", "מיקום"],
  lift: ["Асансьор", "Elevator", "Лифт", "Aufzug", "Lift", "Ανελκυστήρας", "מעלית"],
  availability: [
    "Наличност",
    "Availability",
    "Доступность",
    "Verfügbarkeit",
    "Beschikbaarheid",
    "Διαθεσιμότητα",
    "זמינות",
  ],
  total: [
    "Обща цена",
    "Total price",
    "Полная цена",
    "Gesamtpreis",
    "Totale prijs",
    "Συνολική τιμή",
    "מחיר כולל",
  ],
  yes: ["Да", "Yes", "Да", "Ja", "Ja", "Ναι", "כן"],
  no: ["Не", "No", "Нет", "Nein", "Nee", "Όχι", "לא"],
  collective: [
    "Обсъди избора с брокер",
    "Discuss this selection with a broker",
    "Обсудить выбор с брокером",
    "Auswahl mit einem Makler besprechen",
    "Bespreek deze selectie met een makelaar",
    "Συζητήστε την επιλογή με έναν μεσίτη",
    "דברו על הבחירה עם מתווך",
  ],
  change: [
    "Промени избора",
    "Change selection",
    "Изменить выбор",
    "Auswahl ändern",
    "Selectie wijzigen",
    "Αλλαγή επιλογής",
    "שינוי הבחירה",
  ],
  blocked: [
    "Прегледайте или премахнете недостъпните имоти, преди да изпратите запитване за целия избор.",
    "Review or remove unavailable properties before sending an inquiry about the whole selection.",
    "Проверьте или удалите недоступные объекты перед отправкой запроса обо всём выборе.",
    "Prüfen oder entfernen Sie nicht verfügbare Immobilien, bevor Sie eine Anfrage zur gesamten Auswahl senden.",
    "Controleer of verwijder niet-beschikbare woningen voordat u over de hele selectie een aanvraag verstuurt.",
    "Ελέγξτε ή αφαιρέστε τα μη διαθέσιμα ακίνητα πριν στείλετε αίτημα για ολόκληρη την επιλογή.",
    "בדקו או הסירו נכסים שאינם זמינים לפני שליחת פנייה לגבי הבחירה כולה.",
  ],
  empty: [
    "Изберете до три имота, за да сравните важните факти.",
    "Choose up to three properties to compare their important facts.",
    "Выберите до трёх объектов для сравнения важных данных.",
    "Wählen Sie bis zu drei Immobilien, um wichtige Angaben zu vergleichen.",
    "Kies maximaal drie woningen om belangrijke feiten te vergelijken.",
    "Επιλέξτε έως τρία ακίνητα για να συγκρίνετε τα σημαντικά στοιχεία.",
    "בחרו עד שלושה נכסים להשוואת הנתונים החשובים.",
  ],
  correction: [
    "Проверете избора в адреса: нужни са до три различни валидни референции. Премахнете запис, за да коригирате избора.",
    "Review the selection in this address: use up to three distinct valid references. Remove an entry to correct the selection.",
    "Проверьте выбор в адресе: нужны до трёх разных действительных референций. Удалите запись, чтобы исправить выбор.",
    "Prüfen Sie die Auswahl in dieser Adresse: Verwenden Sie bis zu drei unterschiedliche gültige Referenzen. Entfernen Sie einen Eintrag zur Korrektur.",
    "Controleer de selectie in dit adres: gebruik maximaal drie verschillende geldige referenties. Verwijder een item om de selectie te corrigeren.",
    "Ελέγξτε την επιλογή στη διεύθυνση: χρησιμοποιήστε έως τρεις διαφορετικούς έγκυρους κωδικούς. Αφαιρέστε μια εγγραφή για διόρθωση.",
    "בדקו את הבחירה בכתובת: השתמשו בעד שלושה מספרי נכס תקינים ושונים. הסירו רשומה כדי לתקן את הבחירה.",
  ],
  clear: [
    "Изчисти избора",
    "Clear selection",
    "Очистить выбор",
    "Auswahl leeren",
    "Selectie wissen",
    "Εκκαθάριση επιλογής",
    "ניקוי הבחירה",
  ],
} as const;
const locales = ["bg", "en", "ru", "de", "nl", "el", "he"] as const;
export type CompareCopy = { [K in keyof typeof labels]: string };
export function compareCopy(locale: PublicLocale): CompareCopy {
  const index = locales.indexOf(locale);
  return Object.fromEntries(
    Object.entries(labels).map(([key, values]) => [key, values[index]]),
  ) as CompareCopy;
}
