import type { PublicLocale } from "@/i18n/config";

// Interface copy only. Listing prose always comes from an approved locale manifest.
// These new dictionaries have not received human indexing approval.
const locales = ["bg", "en", "ru", "de", "nl", "el", "he"] as const;
type Row = readonly [string, string, string, string, string, string, string];
const rows = {
  usable: [
    "Използваема площ",
    "Usable area",
    "Полезная площадь",
    "Nutzfläche",
    "Bruikbare oppervlakte",
    "Χρησιμοποιήσιμη επιφάνεια",
    "שטח שימושי",
  ],
  propertyType: [
    "Вид имот",
    "Property type",
    "Тип объекта",
    "Immobilienart",
    "Woningtype",
    "Τύπος ακινήτου",
    "סוג הנכס",
  ],
  anyType: [
    "Всички видове",
    "Any type",
    "Все типы",
    "Alle Arten",
    "Alle typen",
    "Όλοι οι τύποι",
    "כל הסוגים",
  ],
  apartment: [
    "Апартамент",
    "Apartment",
    "Квартира",
    "Wohnung",
    "Appartement",
    "Διαμέρισμα",
    "דירה",
  ],
  house: ["Къща", "House", "Дом", "Haus", "Huis", "Σπίτι", "בית"],
  plot: ["Парцел", "Plot", "Участок", "Grundstück", "Perceel", "Οικόπεδο", "מגרש"],
  commercial: [
    "Търговски имот",
    "Commercial property",
    "Коммерческий объект",
    "Gewerbeimmobilie",
    "Bedrijfspand",
    "Επαγγελματικό ακίνητο",
    "נכס מסחרי",
  ],
  hotel: ["Хотел", "Hotel", "Отель", "Hotel", "Hotel", "Ξενοδοχείο", "מלון"],
  development: [
    "Проект",
    "Development",
    "Проект",
    "Bauprojekt",
    "Bouwproject",
    "Έργο ανάπτυξης",
    "פרויקט",
  ],
  other: [
    "Друг вид",
    "Other type",
    "Другой тип",
    "Andere Art",
    "Ander type",
    "Άλλος τύπος",
    "סוג אחר",
  ],
  areaBasis: [
    "Основа на площта",
    "Area basis",
    "Вид площади",
    "Flächenart",
    "Oppervlaktebasis",
    "Βάση επιφάνειας",
    "סוג השטח",
  ],
  living: [
    "Жилищна площ",
    "Living area",
    "Жилая площадь",
    "Wohnfläche",
    "Woonoppervlakte",
    "Ωφέλιμη επιφάνεια",
    "שטח מגורים",
  ],
  built: [
    "Застроена площ",
    "Built area",
    "Застроенная площадь",
    "Bebaute Fläche",
    "Bebouwde oppervlakte",
    "Δομημένη επιφάνεια",
    "שטח בנוי",
  ],
  gross_floor: [
    "Разгъната застроена площ",
    "Gross floor area",
    "Общая площадь этажей",
    "Bruttogeschossfläche",
    "Bruto vloeroppervlakte",
    "Μικτή επιφάνεια ορόφων",
    "שטח קומות ברוטו",
  ],
  total: [
    "Обща площ",
    "Total area",
    "Общая площадь",
    "Gesamtfläche",
    "Totale oppervlakte",
    "Συνολική επιφάνεια",
    "שטח כולל",
  ],
  land: [
    "Площ на земята",
    "Land area",
    "Площадь земли",
    "Grundstücksfläche",
    "Grondoppervlakte",
    "Επιφάνεια γης",
    "שטח הקרקע",
  ],
  minArea: [
    "Минимална площ (m²)",
    "Minimum area (m²)",
    "Минимальная площадь (m²)",
    "Mindestfläche (m²)",
    "Minimumoppervlakte (m²)",
    "Ελάχιστη επιφάνεια (m²)",
    "שטח מינימום (m²)",
  ],
  maxArea: [
    "Максимална площ (m²)",
    "Maximum area (m²)",
    "Максимальная площадь (m²)",
    "Höchstfläche (m²)",
    "Maximumoppervlakte (m²)",
    "Μέγιστη επιφάνεια (m²)",
    "שטח מקסימום (m²)",
  ],
  factSource: [
    "Източник на данните",
    "Fact source",
    "Источник данных",
    "Datenquelle",
    "Gegevensbron",
    "Πηγή στοιχείων",
    "מקור הפרטים",
  ],
  imported: [
    "Внесени данни",
    "Imported data",
    "Импортированные данные",
    "Importierte Daten",
    "Geïmporteerde gegevens",
    "Εισαγόμενα στοιχεία",
    "נתונים שיובאו",
  ],
  owner_supplied: [
    "Данни от собственика",
    "Owner supplied",
    "От собственника",
    "Eigentümerangabe",
    "Door eigenaar verstrekt",
    "Από τον ιδιοκτήτη",
    "נמסרו בידי הבעלים",
  ],
  broker_verified: [
    "Прегледано от агенцията",
    "Agency reviewed",
    "Проверено агентством",
    "Von der Agentur geprüft",
    "Door het kantoor beoordeeld",
    "Ελεγμένο από το γραφείο",
    "נבדקו בידי הסוכנות",
  ],
  calculated: [
    "Изчислено",
    "Calculated",
    "Рассчитано",
    "Berechnet",
    "Berekend",
    "Υπολογισμένο",
    "מחושב",
  ],
  partial: [
    "Показаните резултати може да са непълни. Опитайте отново.",
    "These results may be incomplete. Try again.",
    "Результаты могут быть неполными. Попробуйте снова.",
    "Die Ergebnisse können unvollständig sein. Versuchen Sie es erneut.",
    "De resultaten kunnen onvolledig zijn. Probeer opnieuw.",
    "Τα αποτελέσματα μπορεί να είναι ελλιπή. Δοκιμάστε ξανά.",
    "ייתכן שהתוצאות חלקיות. נסו שוב.",
  ],
  properties: ["Имоти", "Properties", "Недвижимость", "Immobilien", "Woningen", "Ακίνητα", "נכסים"],
  buy: ["Купете", "Buy", "Купить", "Kaufen", "Kopen", "Αγορά", "קנייה"],
  rent: [
    "Наемете дългосрочно",
    "Long-term rent",
    "Долгосрочная аренда",
    "Langfristig mieten",
    "Langdurig huren",
    "Μακροχρόνια μίσθωση",
    "שכירות לטווח ארוך",
  ],
  sell: [
    "Обсъдете продажба",
    "Discuss selling",
    "Обсудить продажу",
    "Verkauf besprechen",
    "Verkoop bespreken",
    "Συζήτηση πώλησης",
    "בירור מכירה",
  ],
  let: [
    "Обсъдете отдаване под наем",
    "Discuss letting",
    "Обсудить сдачу в аренду",
    "Vermietung besprechen",
    "Verhuur bespreken",
    "Συζήτηση εκμίσθωσης",
    "בירור השכרה",
  ],
  intro: [
    "Разгледайте публикуваните имоти или изпратете запитване до MS Realty.",
    "Browse published properties or send an inquiry to MS Realty.",
    "Посмотрите опубликованные объекты или отправьте запрос в MS Realty.",
    "Entdecken Sie veröffentlichte Immobilien oder senden Sie MS Realty eine Anfrage.",
    "Bekijk gepubliceerde woningen of stuur MS Realty een aanvraag.",
    "Δείτε δημοσιευμένα ακίνητα ή στείλτε ερώτημα στη MS Realty.",
    "עיינו בנכסים שפורסמו או שלחו פנייה ל־MS Realty.",
  ],
  search: [
    "Търсете имоти",
    "Search properties",
    "Найти недвижимость",
    "Immobilien suchen",
    "Woningen zoeken",
    "Αναζήτηση ακινήτων",
    "חיפוש נכסים",
  ],
  query: [
    "Място, текст или номер",
    "Place, text or reference",
    "Место, текст или номер",
    "Ort, Text oder Referenz",
    "Plaats, tekst of referentie",
    "Τόπος, κείμενο ή κωδικός",
    "מקום, טקסט או מספר נכס",
  ],
  purpose: ["Цел", "Purpose", "Цель", "Zweck", "Doel", "Σκοπός", "מטרה"],
  sort: ["Подредба", "Sort", "Сортировка", "Sortierung", "Sortering", "Ταξινόμηση", "מיון"],
  relevance: [
    "Съответствие",
    "Relevance",
    "Соответствие",
    "Relevanz",
    "Relevantie",
    "Συνάφεια",
    "התאמה",
  ],
  newest: ["Най-нови", "Newest", "Новые", "Neueste", "Nieuwste", "Νεότερα", "החדשים ביותר"],
  priceAsc: [
    "Цена: възходящо",
    "Price: low to high",
    "Цена: по возрастанию",
    "Preis: aufsteigend",
    "Prijs: laag naar hoog",
    "Τιμή: αύξουσα",
    "מחיר: מהנמוך לגבוה",
  ],
  priceDesc: [
    "Цена: низходящо",
    "Price: high to low",
    "Цена: по убыванию",
    "Preis: absteigend",
    "Prijs: hoog naar laag",
    "Τιμή: φθίνουσα",
    "מחיר: מהגבוה לנמוך",
  ],
  minPrice: [
    "Минимална цена (EUR)",
    "Minimum price (EUR)",
    "Минимальная цена (EUR)",
    "Mindestpreis (EUR)",
    "Minimumprijs (EUR)",
    "Ελάχιστη τιμή (EUR)",
    "מחיר מינימום (EUR)",
  ],
  maxPrice: [
    "Максимална цена (EUR)",
    "Maximum price (EUR)",
    "Максимальная цена (EUR)",
    "Höchstpreis (EUR)",
    "Maximumprijs (EUR)",
    "Μέγιστη τιμή (EUR)",
    "מחיר מקסימום (EUR)",
  ],
  minBeds: [
    "Минимум спални",
    "Minimum bedrooms",
    "Минимум спален",
    "Mindestens Schlafzimmer",
    "Minimaal slaapkamers",
    "Ελάχιστα υπνοδωμάτια",
    "מינימום חדרי שינה",
  ],
  includeUnconfirmed: [
    "Включете непотвърдени характеристики и наличност",
    "Include unconfirmed facts and availability",
    "Включить неподтверждённые факты и наличие",
    "Unbestätigte Angaben und Verfügbarkeit einbeziehen",
    "Onbevestigde kenmerken en beschikbaarheid meenemen",
    "Συμπερίληψη ανεπιβεβαίωτων στοιχείων και διαθεσιμότητας",
    "הכללת פרטים וזמינות שטרם אושרו",
  ],
  apply: [
    "Приложете филтрите",
    "Apply filters",
    "Применить фильтры",
    "Filter anwenden",
    "Filters toepassen",
    "Εφαρμογή φίλτρων",
    "החלת מסננים",
  ],
  clear: [
    "Изчистете филтрите",
    "Clear filters",
    "Сбросить фильтры",
    "Filter zurücksetzen",
    "Filters wissen",
    "Καθαρισμός φίλτρων",
    "ניקוי מסננים",
  ],
  results: [
    "Резултати",
    "Results",
    "Результаты",
    "Ergebnisse",
    "Resultaten",
    "Αποτελέσματα",
    "תוצאות",
  ],
  atLeast: ["Поне", "At least", "Не менее", "Mindestens", "Minstens", "Τουλάχιστον", "לפחות"],
  none: [
    "Няма публикувани имоти по тези критерии.",
    "No published properties match these filters.",
    "Нет опубликованных объектов по этим фильтрам.",
    "Keine veröffentlichten Immobilien entsprechen diesen Filtern.",
    "Geen gepubliceerde woningen passen bij deze filters.",
    "Δεν υπάρχουν δημοσιευμένα ακίνητα με αυτά τα φίλτρα.",
    "אין נכסים שפורסמו התואמים למסננים האלה.",
  ],
  unavailable: [
    "Този имот не е достъпен тук.",
    "This property is unavailable here.",
    "Этот объект здесь недоступен.",
    "Diese Immobilie ist hier nicht verfügbar.",
    "Deze woning is hier niet beschikbaar.",
    "Αυτό το ακίνητο δεν είναι διαθέσιμο εδώ.",
    "הנכס הזה אינו זמין כאן.",
  ],
  rateLimited: [
    "Изчакайте {seconds} секунди, преди да опитате отново. Запитването не е изпратено и въведените данни са запазени.",
    "Wait {seconds} seconds before trying again. Your inquiry was not submitted and your entries are retained.",
    "Подождите {seconds} секунд перед повторной попыткой. Заявка не отправлена, введённые данные сохранены.",
    "Warten Sie {seconds} Sekunden, bevor Sie es erneut versuchen. Ihre Anfrage wurde nicht gesendet. Ihre Eingaben bleiben erhalten.",
    "Wacht {seconds} seconden voordat u het opnieuw probeert. Uw aanvraag is niet verzonden en uw invoer blijft bewaard.",
    "Περιμένετε {seconds} δευτερόλεπτα πριν δοκιμάσετε ξανά. Το αίτημά σας δεν υποβλήθηκε και τα στοιχεία σας διατηρούνται.",
    "המתינו {seconds} שניות לפני ניסיון נוסף. הפנייה לא נשלחה והפרטים שהזנתם נשמרו.",
  ],
  failed: [
    "Не успяхме да заредим информацията. Опитайте отново.",
    "We could not load the information. Please try again.",
    "Не удалось загрузить информацию. Попробуйте снова.",
    "Die Informationen konnten nicht geladen werden. Bitte erneut versuchen.",
    "De informatie kon niet worden geladen. Probeer het opnieuw.",
    "Δεν ήταν δυνατή η φόρτωση. Δοκιμάστε ξανά.",
    "לא הצלחנו לטעון את המידע. נסו שוב.",
  ],
  source: [
    "Разгледайте одобрените обяви на български",
    "Browse approved listings in Bulgarian",
    "Посмотреть одобренные объявления на болгарском",
    "Freigegebene Angebote auf Bulgarisch ansehen",
    "Goedgekeurde aanbiedingen in het Bulgaars bekijken",
    "Δείτε εγκεκριμένες αγγελίες στα βουλγαρικά",
    "עיון במודעות מאושרות בבולגרית",
  ],
  noTranslation: [
    "Няма одобрена версия на този език.",
    "An approved version in this language is not available.",
    "Одобренная версия на этом языке недоступна.",
    "Eine freigegebene Fassung in dieser Sprache ist nicht verfügbar.",
    "Er is geen goedgekeurde versie in deze taal.",
    "Δεν υπάρχει εγκεκριμένη έκδοση σε αυτή τη γλώσσα.",
    "אין גרסה מאושרת בשפה הזו.",
  ],
  mapUnavailable: [
    "Картата не е достъпна. Списъкът и филтрите остават достъпни.",
    "The map is unavailable. The list and filters remain available.",
    "Карта недоступна. Список и фильтры доступны.",
    "Die Karte ist nicht verfügbar. Liste und Filter bleiben nutzbar.",
    "De kaart is niet beschikbaar. Lijst en filters blijven beschikbaar.",
    "Ο χάρτης δεν είναι διαθέσιμος. Η λίστα και τα φίλτρα λειτουργούν.",
    "המפה אינה זמינה. הרשימה והמסננים עדיין זמינים.",
  ],
  noPhoto: [
    "Снимките не са достъпни",
    "Photos unavailable",
    "Фотографии недоступны",
    "Fotos nicht verfügbar",
    "Foto’s niet beschikbaar",
    "Οι φωτογραφίες δεν είναι διαθέσιμες",
    "התמונות אינן זמינות",
  ],
  bedrooms: [
    "Спални",
    "Bedrooms",
    "Спальни",
    "Schlafzimmer",
    "Slaapkamers",
    "Υπνοδωμάτια",
    "חדרי שינה",
  ],
  area: ["Площ", "Area", "Площадь", "Fläche", "Oppervlakte", "Εμβαδόν", "שטח"],
  reference: ["Номер", "Reference", "Номер", "Referenz", "Referentie", "Κωδικός", "מספר"],
  confirmedAt: [
    "Последно потвърдено",
    "Last confirmed",
    "Последнее подтверждение",
    "Zuletzt bestätigt",
    "Laatst bevestigd",
    "Τελευταία επιβεβαίωση",
    "אושר לאחרונה",
  ],
  unknown: ["Неизвестно", "Unknown", "Неизвестно", "Unbekannt", "Onbekend", "Άγνωστο", "לא ידוע"],
  withheld: [
    "Не се публикува",
    "Withheld",
    "Не публикуется",
    "Nicht veröffentlicht",
    "Niet gepubliceerd",
    "Δεν δημοσιεύεται",
    "לא לפרסום",
  ],
  not_applicable: [
    "Неприложимо",
    "Not applicable",
    "Неприменимо",
    "Nicht zutreffend",
    "Niet van toepassing",
    "Δεν εφαρμόζεται",
    "לא רלוונטי",
  ],
  conflicting: [
    "Противоречиви данни",
    "Conflicting information",
    "Противоречивые данные",
    "Widersprüchliche Angaben",
    "Tegenstrijdige informatie",
    "Αντικρουόμενα στοιχεία",
    "מידע סותר",
  ],
  not_supplied: [
    "Не е предоставено",
    "Not supplied",
    "Не предоставлено",
    "Nicht angegeben",
    "Niet verstrekt",
    "Δεν δόθηκε",
    "לא נמסר",
  ],
  perMonth: ["на месец", "per month", "в месяц", "pro Monat", "per maand", "ανά μήνα", "לחודש"],
  asking: [
    "Офертна цена",
    "Asking price",
    "Запрашиваемая цена",
    "Angebotspreis",
    "Vraagprijs",
    "Ζητούμενη τιμή",
    "מחיר מבוקש",
  ],
  negotiable: [
    "Договаряема цена",
    "Negotiable price",
    "Договорная цена",
    "Verhandelbarer Preis",
    "Onderhandelbare prijs",
    "Διαπραγματεύσιμη τιμή",
    "מחיר למשא ומתן",
  ],
  fixed: [
    "Фиксирана цена",
    "Fixed price",
    "Фиксированная цена",
    "Festpreis",
    "Vaste prijs",
    "Σταθερή τιμή",
    "מחיר קבוע",
  ],
  indicative: [
    "Ориентировъчна цена",
    "Indicative price",
    "Ориентировочная цена",
    "Richtpreis",
    "Richtprijs",
    "Ενδεικτική τιμή",
    "מחיר משוער",
  ],
  available: ["Наличен", "Available", "Доступен", "Verfügbar", "Beschikbaar", "Διαθέσιμο", "זמין"],
  confirmation_required: [
    "Нужно е потвърждение",
    "Confirmation required",
    "Требуется подтверждение",
    "Bestätigung erforderlich",
    "Bevestiging nodig",
    "Απαιτείται επιβεβαίωση",
    "נדרש אישור",
  ],
  negotiating: [
    "В преговори",
    "Under negotiation",
    "В переговорах",
    "In Verhandlung",
    "In onderhandeling",
    "Σε διαπραγμάτευση",
    "במשא ומתן",
  ],
  reserved_with_recorded_basis: [
    "Резервиран",
    "Reserved",
    "Зарезервирован",
    "Reserviert",
    "Gereserveerd",
    "Δεσμευμένο",
    "שמור",
  ],
  sold: ["Продаден", "Sold", "Продан", "Verkauft", "Verkocht", "Πωλήθηκε", "נמכר"],
  letStatus: ["Отдаден", "Let", "Сдан", "Vermietet", "Verhuurd", "Εκμισθώθηκε", "הושכר"],
  withdrawn: [
    "Оттеглен",
    "Withdrawn",
    "Снят",
    "Zurückgezogen",
    "Ingetrokken",
    "Αποσύρθηκε",
    "הוסר",
  ],
  viewing: [
    "Заявете оглед",
    "Request a viewing",
    "Запросить просмотр",
    "Besichtigung anfragen",
    "Bezichtiging aanvragen",
    "Αίτημα επίσκεψης",
    "בקשת ביקור",
  ],
  ask: [
    "Изпратете запитване",
    "Send an inquiry",
    "Отправить запрос",
    "Anfrage senden",
    "Aanvraag versturen",
    "Αποστολή ερωτήματος",
    "שליחת פנייה",
  ],
  back: [
    "Към имотите",
    "Back to properties",
    "К объектам",
    "Zur Immobilienübersicht",
    "Terug naar woningen",
    "Επιστροφή στα ακίνητα",
    "חזרה לנכסים",
  ],
  more: [
    "Следваща страница",
    "Next page",
    "Следующая страница",
    "Nächste Seite",
    "Volgende pagina",
    "Επόμενη σελίδα",
    "העמוד הבא",
  ],
  saved: [
    "Запазени",
    "Saved",
    "Сохранённое",
    "Gespeichert",
    "Opgeslagen",
    "Αποθηκευμένα",
    "שמורים",
  ],
  compare: ["Сравнете", "Compare", "Сравнить", "Vergleichen", "Vergelijken", "Σύγκριση", "השוואה"],
  save: [
    "Запазете в този браузър",
    "Save in this browser",
    "Сохранить в этом браузере",
    "In diesem Browser speichern",
    "In deze browser opslaan",
    "Αποθήκευση σε αυτόν τον περιηγητή",
    "שמירה בדפדפן זה",
  ],
  remove: ["Премахнете", "Remove", "Удалить", "Entfernen", "Verwijderen", "Αφαίρεση", "הסרה"],
  localOnly: [
    "Запазените номера остават само в този браузър. Не се синхронизират с профил.",
    "Saved references stay in this browser only. They do not sync to an account.",
    "Сохранённые номера остаются только в этом браузере и не синхронизируются с аккаунтом.",
    "Gespeicherte Referenzen bleiben in diesem Browser. Keine Kontosynchronisierung.",
    "Opgeslagen referenties blijven alleen in deze browser. Geen accountsynchronisatie.",
    "Οι κωδικοί αποθηκεύονται μόνο σε αυτόν τον περιηγητή, χωρίς συγχρονισμό λογαριασμού.",
    "המספרים השמורים נשארים בדפדפן זה בלבד ואינם מסתנכרנים לחשבון.",
  ],
  storageFailed: [
    "Съхранението в браузъра не е достъпно. Изборът е временен.",
    "Browser storage is unavailable. This selection is temporary.",
    "Хранилище браузера недоступно. Выбор временный.",
    "Browserspeicher nicht verfügbar. Die Auswahl ist vorübergehend.",
    "Browseropslag is niet beschikbaar. De selectie is tijdelijk.",
    "Ο χώρος αποθήκευσης δεν είναι διαθέσιμος. Η επιλογή είναι προσωρινή.",
    "אחסון הדפדפן אינו זמין. הבחירה זמנית.",
  ],
  emptySaved: [
    "Още няма запазени имоти.",
    "No saved properties yet.",
    "Сохранённых объектов пока нет.",
    "Noch keine gespeicherten Immobilien.",
    "Nog geen opgeslagen woningen.",
    "Δεν υπάρχουν ακόμη αποθηκευμένα ακίνητα.",
    "עדיין אין נכסים שמורים.",
  ],
  compareLimit: [
    "Изберете до 3 имота за сравнение.",
    "Choose up to 3 properties to compare.",
    "Выберите до 3 объектов для сравнения.",
    "Bis zu 3 Immobilien vergleichen.",
    "Kies maximaal 3 woningen om te vergelijken.",
    "Επιλέξτε έως 3 ακίνητα για σύγκριση.",
    "בחרו עד 3 נכסים להשוואה.",
  ],
  noJsSaved: [
    "За запазване в браузъра е нужен JavaScript. Можете да запазите адреса като отметка.",
    "Saving in the browser needs JavaScript. You can bookmark the property address instead.",
    "Для сохранения нужен JavaScript. Можно добавить адрес объекта в закладки.",
    "Speichern im Browser benötigt JavaScript. Sie können die Adresse als Lesezeichen speichern.",
    "Opslaan in de browser vereist JavaScript. U kunt het adres als bladwijzer opslaan.",
    "Η αποθήκευση χρειάζεται JavaScript. Μπορείτε να προσθέσετε τη διεύθυνση στους σελιδοδείκτες.",
    "שמירה בדפדפן דורשת JavaScript. אפשר לשמור את כתובת הנכס בסימניות.",
  ],
  name: ["Име", "Name", "Имя", "Name", "Naam", "Όνομα", "שם"],
  email: ["Имейл", "Email", "Электронная почта", "E-Mail", "E-mail", "Email", "דוא״ל"],
  phone: [
    "Телефон с код на държавата",
    "Phone with country code",
    "Телефон с кодом страны",
    "Telefon mit Ländervorwahl",
    "Telefoon met landcode",
    "Τηλέφωνο με κωδικό χώρας",
    "טלפון עם קידומת מדינה",
  ],
  contactMethod: [
    "Предпочитан контакт",
    "Preferred contact method",
    "Способ связи",
    "Bevorzugter Kontaktweg",
    "Voorkeurscontactmethode",
    "Προτιμώμενος τρόπος επικοινωνίας",
    "דרך קשר מועדפת",
  ],
  message: [
    "Вашето запитване",
    "Your inquiry",
    "Ваш запрос",
    "Ihre Anfrage",
    "Uw aanvraag",
    "Το ερώτημά σας",
    "הפנייה שלכם",
  ],
  callback: [
    "Заявка за обаждане",
    "Request a callback",
    "Запросить звонок",
    "Rückruf anfragen",
    "Terugbelverzoek",
    "Αίτημα κλήσης",
    "בקשה לשיחה חוזרת",
  ],
  callbackWindow: [
    "Удобно време (Europe/Sofia)",
    "Preferred time (Europe/Sofia)",
    "Удобное время (Europe/Sofia)",
    "Bevorzugte Zeit (Europe/Sofia)",
    "Gewenste tijd (Europe/Sofia)",
    "Προτιμώμενη ώρα (Europe/Sofia)",
    "זמן מועדף (Europe/Sofia)",
  ],
  privacy: [
    "Разбирам, че MS Realty ще използва тези данни, за да отговори на запитването ми.",
    "I understand MS Realty will use these details to respond to this inquiry.",
    "Я понимаю, что MS Realty использует эти данные для ответа на мой запрос.",
    "Ich verstehe, dass MS Realty diese Angaben zur Beantwortung meiner Anfrage verwendet.",
    "Ik begrijp dat MS Realty deze gegevens gebruikt om op mijn aanvraag te reageren.",
    "Κατανοώ ότι η MS Realty θα χρησιμοποιήσει αυτά τα στοιχεία για να απαντήσει στο ερώτημά μου.",
    "ברור לי ש־MS Realty תשתמש בפרטים האלה כדי להשיב לפנייה הזו.",
  ],
  sending: [
    "Изпращане…",
    "Sending…",
    "Отправка…",
    "Wird gesendet…",
    "Verzenden…",
    "Αποστολή…",
    "נשלח…",
  ],
  check: [
    "Проверете отговорите",
    "Check your answers",
    "Проверьте ответы",
    "Antworten prüfen",
    "Controleer uw antwoorden",
    "Ελέγξτε τις απαντήσεις",
    "בדקו את התשובות",
  ],
  invalid: [
    "Проверете този отговор и опитайте отново.",
    "Check this answer and try again.",
    "Проверьте этот ответ и попробуйте снова.",
    "Prüfen Sie diese Antwort und versuchen Sie es erneut.",
    "Controleer dit antwoord en probeer het opnieuw.",
    "Ελέγξτε αυτή την απάντηση και δοκιμάστε ξανά.",
    "בדקו את התשובה הזו ונסו שוב.",
  ],
  received: [
    "Запитването е получено",
    "Inquiry received",
    "Запрос получен",
    "Anfrage eingegangen",
    "Aanvraag ontvangen",
    "Το ερώτημα παραλήφθηκε",
    "הפנייה התקבלה",
  ],
  next: [
    "MS Realty ще прегледа запитването. Оглед и отговор по имейл все още не са потвърдени.",
    "MS Realty will review the inquiry. A viewing and email delivery are not yet confirmed.",
    "MS Realty рассмотрит запрос. Просмотр и доставка письма ещё не подтверждены.",
    "MS Realty prüft die Anfrage. Besichtigung und E-Mail-Zustellung sind noch nicht bestätigt.",
    "MS Realty beoordeelt de aanvraag. Een bezichtiging en e-mailbezorging zijn nog niet bevestigd.",
    "Η MS Realty θα εξετάσει το ερώτημα. Η επίσκεψη και η παράδοση email δεν έχουν επιβεβαιωθεί.",
    "MS Realty תבדוק את הפנייה. ביקור ומסירת דוא״ל טרם אושרו.",
  ],
  receipt: [
    "Отворете разписката",
    "Open receipt",
    "Открыть подтверждение",
    "Bestätigung öffnen",
    "Ontvangstbewijs openen",
    "Άνοιγμα απόδειξης",
    "פתיחת האישור",
  ],
  checkOperation: [
    "Проверете същото запитване",
    "Check this same inquiry",
    "Проверить этот запрос",
    "Diese Anfrage prüfen",
    "Deze aanvraag controleren",
    "Έλεγχος του ίδιου ερωτήματος",
    "בדיקת אותה פנייה",
  ],
  notConfirmed: [
    "Не можем да потвърдим резултата в този браузър.",
    "We cannot confirm the result in this browser.",
    "Мы не можем подтвердить результат в этом браузере.",
    "Das Ergebnis kann in diesem Browser nicht bestätigt werden.",
    "Het resultaat kan in deze browser niet worden bevestigd.",
    "Δεν μπορούμε να επιβεβαιώσουμε το αποτέλεσμα σε αυτόν τον περιηγητή.",
    "לא ניתן לאמת את התוצאה בדפדפן זה.",
  ],
  retained: [
    "Текстът ви е запазен. Проверете резултата, преди да изпратите ново запитване.",
    "Your text is retained. Check the result before sending a new inquiry.",
    "Ваш текст сохранён. Проверьте результат перед новым запросом.",
    "Ihr Text bleibt erhalten. Prüfen Sie das Ergebnis vor einer neuen Anfrage.",
    "Uw tekst blijft behouden. Controleer het resultaat voordat u opnieuw verzendt.",
    "Το κείμενό σας διατηρείται. Ελέγξτε το αποτέλεσμα πριν από νέο ερώτημα.",
    "הטקסט שלכם נשמר. בדקו את התוצאה לפני שליחת פנייה חדשה.",
  ],
  newRequest: [
    "Ново запитване",
    "New inquiry",
    "Новый запрос",
    "Neue Anfrage",
    "Nieuwe aanvraag",
    "Νέο ερώτημα",
    "פנייה חדשה",
  ],
  optional: [
    "(по избор)",
    "(optional)",
    "(необязательно)",
    "(optional)",
    "(optioneel)",
    "(προαιρετικό)",
    "(רשות)",
  ],
  messageHint: [
    "До 2000 знака. Без документи за самоличност или финансови данни.",
    "Up to 2,000 characters. No identity documents or financial details.",
    "До 2000 знаков. Без документов и финансовых данных.",
    "Bis zu 2.000 Zeichen. Keine Ausweis- oder Finanzdaten.",
    "Maximaal 2.000 tekens. Geen identiteitsdocumenten of financiële gegevens.",
    "Έως 2.000 χαρακτήρες. Χωρίς έγγραφα ταυτότητας ή οικονομικά στοιχεία.",
    "עד 2,000 תווים. ללא מסמכי זהות או פרטים פיננסיים.",
  ],
  changed: [
    "Обявата е променена. Прегледайте текущата версия, преди да продължите.",
    "The listing changed. Review the current version before continuing.",
    "Объявление изменилось. Проверьте текущую версию.",
    "Das Angebot hat sich geändert. Prüfen Sie die aktuelle Fassung.",
    "De aanbieding is gewijzigd. Bekijk de huidige versie.",
    "Η αγγελία άλλαξε. Ελέγξτε την τρέχουσα έκδοση.",
    "המודעה השתנתה. בדקו את הגרסה הנוכחית לפני שתמשיכו.",
  ],
} satisfies Record<string, Row>;

export type DiscoveryCopy = Record<keyof typeof rows, string>;
export function discoveryCopy(locale: PublicLocale): DiscoveryCopy {
  const index = locales.indexOf(locale);
  return Object.fromEntries(
    Object.entries(rows).map(([key, values]) => [key, values[index]]),
  ) as DiscoveryCopy;
}
