import type { PublicLocale } from "@/i18n/config";

// Interface drafts, not human approval for indexing or professional/property claims.
const locales = ["bg", "en", "ru", "de", "nl", "el", "he"] as const;
type Row = readonly [string, string, string, string, string, string, string];
const rows = {
  entrySources: [
    "Данни за имотите при зареждане на страницата. Актуалните източници се проверяват отново при прегледа преди изпращане.",
    "Property context loaded with this page. Current sources are checked again when you review before sending.",
    "Данные объектов при загрузке страницы. Актуальные источники проверяются повторно при просмотре перед отправкой.",
    "Immobiliendaten beim Laden dieser Seite. Aktuelle Quellen werden bei der Prüfung vor dem Senden erneut geprüft.",
    "Woninggegevens bij het laden van deze pagina. Actuele bronnen worden opnieuw gecontroleerd bij de controle vóór verzending.",
    "Στοιχεία ακινήτων κατά τη φόρτωση της σελίδας. Οι τρέχουσες πηγές ελέγχονται ξανά κατά την εξέταση πριν από την αποστολή.",
    "פרטי הנכסים בעת טעינת העמוד. המקורות העדכניים ייבדקו שוב בבדיקה שלפני השליחה.",
  ],
  service: [
    "Консултация за услуга",
    "Service consultation",
    "Консультация по услуге",
    "Beratung zur Dienstleistung",
    "Advies over een dienst",
    "Συμβουλή για υπηρεσία",
    "ייעוץ לגבי שירות",
  ],
  refreshSources: [
    "Прегледай актуалните източници",
    "Review current sources",
    "Проверить актуальные источники",
    "Aktuelle Quellen prüfen",
    "Actuele bronnen controleren",
    "Έλεγχος τρεχουσών πηγών",
    "בדיקת המקורות העדכניים",
  ],
  sourcesChanged: [
    "Източникът е променен или вече не е достъпен. Данните Ви са запазени. Проверете актуалните източници преди нов преглед; недостъпен имот няма да бъде премахнат автоматично.",
    "A source changed or is no longer available. Your entries are retained. Review current sources before sending; unavailable properties will never be removed automatically.",
    "Источник изменён или недоступен. Ваши данные сохранены. Проверьте актуальные источники перед отправкой; недоступные объекты не удаляются автоматически.",
    "Eine Quelle hat sich geändert oder ist nicht mehr verfügbar. Ihre Angaben bleiben erhalten. Prüfen Sie die aktuellen Quellen; nicht verfügbare Immobilien werden nicht automatisch entfernt.",
    "Een bron is gewijzigd of niet meer beschikbaar. Uw invoer blijft behouden. Controleer de actuele bronnen; niet-beschikbare woningen worden niet automatisch verwijderd.",
    "Μια πηγή άλλαξε ή δεν είναι διαθέσιμη. Τα στοιχεία σας διατηρούνται. Ελέγξτε τις τρέχουσες πηγές· μη διαθέσιμα ακίνητα δεν αφαιρούνται αυτόματα.",
    "מקור השתנה או אינו זמין עוד. הפרטים שהזנתם נשמרו. בדקו את המקורות העדכניים; נכסים שאינם זמינים לא יוסרו אוטומטית.",
  ],
  sale: ["Продажба", "Sale", "Продажа", "Verkauf", "Verkoop", "Πώληση", "מכירה"],
  letting: [
    "Дългосрочен наем",
    "Long-term letting",
    "Долгосрочная аренда",
    "Langzeitvermietung",
    "Langdurige verhuur",
    "Μακροχρόνια μίσθωση",
    "השכרה לטווח ארוך",
  ],
  reviewTitle: [
    "Преглед на запитването",
    "Review your inquiry",
    "Проверьте запрос",
    "Anfrage prüfen",
    "Controleer uw aanvraag",
    "Ελέγξτε το αίτημά σας",
    "בדיקת הפנייה",
  ],
  reviewAction: [
    "Прегледай запитването",
    "Review inquiry",
    "Проверить запрос",
    "Anfrage prüfen",
    "Aanvraag controleren",
    "Έλεγχος αιτήματος",
    "בדיקת הפנייה",
  ],
  confirmAction: [
    "Изпрати запитването до MS Realty",
    "Send inquiry to MS Realty",
    "Отправить запрос в MS Realty",
    "Anfrage an MS Realty senden",
    "Aanvraag naar MS Realty verzenden",
    "Αποστολή αιτήματος στη MS Realty",
    "שליחת הפנייה ל-MS Realty",
  ],
  editAction: [
    "Редактирай",
    "Edit inquiry",
    "Изменить запрос",
    "Anfrage bearbeiten",
    "Aanvraag wijzigen",
    "Επεξεργασία αιτήματος",
    "עריכת הפנייה",
  ],
  reviewNeeded: [
    "Прегледайте отново данните преди изпращане.",
    "Review these details again before sending.",
    "Проверьте данные ещё раз перед отправкой.",
    "Prüfen Sie die Angaben vor dem Senden erneut.",
    "Controleer de gegevens opnieuw voordat u verzendt.",
    "Ελέγξτε ξανά τα στοιχεία πριν την αποστολή.",
    "יש לבדוק שוב את הפרטים לפני השליחה.",
  ],
  reviewNote: [
    "Все още нищо не е изпратено. Проверете данните и потвърдете изпращането.",
    "Nothing has been sent yet. Check the details, then confirm sending.",
    "Пока ничего не отправлено. Проверьте данные и подтвердите отправку.",
    "Es wurde noch nichts gesendet. Prüfen Sie die Angaben und bestätigen Sie das Senden.",
    "Er is nog niets verzonden. Controleer de gegevens en bevestig de verzending.",
    "Δεν έχει σταλεί τίποτα ακόμη. Ελέγξτε τα στοιχεία και επιβεβαιώστε την αποστολή.",
    "עדיין לא נשלח דבר. בדקו את הפרטים ואשרו את השליחה.",
  ],
  recipient: [
    "Получател",
    "Recipient",
    "Получатель",
    "Empfänger",
    "Ontvanger",
    "Παραλήπτης",
    "נמען",
  ],
  language: [
    "Език за отговор",
    "Reply language",
    "Язык ответа",
    "Antwortsprache",
    "Antwoordtaal",
    "Γλώσσα απάντησης",
    "שפת התשובה",
  ],
  ownerTitle: [
    "Разкажете ни за имота",
    "Tell us about the property",
    "Расскажите об объекте",
    "Angaben zur Immobilie",
    "Vertel over de woning",
    "Πείτε μας για το ακίνητο",
    "ספרו לנו על הנכס",
  ],
  ownerNote: [
    "Данните са Ваше твърдение. Те не потвърждават собственост или представителна власт и не разрешават публикуване. Не изпращайте лични или правни документи тук.",
    "These details are self-declared. They do not verify ownership or authority, or authorize publication. Do not submit identity or legal documents here.",
    "Это сведения с Ваших слов. Они не подтверждают собственность или полномочия и не разрешают публикацию. Не отправляйте здесь личные или правовые документы.",
    "Diese Angaben stammen von Ihnen. Sie bestätigen weder Eigentum noch Vertretungsbefugnis und erlauben keine Veröffentlichung. Keine Ausweis- oder Rechtsdokumente hier übermitteln.",
    "Deze gegevens zijn uw eigen verklaring. Ze bevestigen geen eigendom of bevoegdheid en geven geen toestemming voor publicatie. Dien hier geen identiteits- of juridische documenten in.",
    "Τα στοιχεία δηλώνονται από εσάς. Δεν επιβεβαιώνουν ιδιοκτησία ή εξουσιοδότηση και δεν επιτρέπουν δημοσίευση. Μην υποβάλλετε εδώ έγγραφα ταυτότητας ή νομικά έγγραφα.",
    "אלה פרטים לפי הצהרתכם. הם אינם מאמתים בעלות או סמכות ואינם מתירים פרסום. אין לשלוח כאן מסמכי זיהוי או מסמכים משפטיים.",
  ],
  locality: [
    "Населено място или район",
    "Town or area",
    "Населённый пункт или район",
    "Ort oder Gebiet",
    "Plaats of gebied",
    "Πόλη ή περιοχή",
    "יישוב או אזור",
  ],
  propertyType: [
    "Тип имот",
    "Property type",
    "Тип объекта",
    "Immobilientyp",
    "Woningtype",
    "Τύπος ακινήτου",
    "סוג הנכס",
  ],
  transaction: [
    "Продажба или дългосрочен наем",
    "Sale or long-term letting",
    "Продажа или долгосрочная аренда",
    "Verkauf oder Langzeitvermietung",
    "Verkoop of langdurige verhuur",
    "Πώληση ή μακροχρόνια μίσθωση",
    "מכירה או השכרה לטווח ארוך",
  ],
  documentArea: [
    "Площ по документ, ако е известна (m²)",
    "Document area, if known (m²)",
    "Площадь по документу, если известна (m²)",
    "Fläche laut Dokument, falls bekannt (m²)",
    "Oppervlakte volgens document, indien bekend (m²)",
    "Εμβαδόν κατά έγγραφο, εάν είναι γνωστό (m²)",
    "שטח לפי מסמך, אם ידוע (m²)",
  ],
  relationship: [
    "Вашата връзка с имота",
    "Your relationship to the property",
    "Ваше отношение к объекту",
    "Ihr Verhältnis zur Immobilie",
    "Uw relatie tot de woning",
    "Η σχέση σας με το ακίνητο",
    "הקשר שלכם לנכס",
  ],
  propertyStatus: [
    "Текущо ползване или състояние, ако е известно",
    "Current use or condition, if known",
    "Текущее использование или состояние, если известно",
    "Aktuelle Nutzung oder Zustand, falls bekannt",
    "Huidig gebruik of staat, indien bekend",
    "Τρέχουσα χρήση ή κατάσταση, εάν είναι γνωστή",
    "שימוש או מצב נוכחי, אם ידוע",
  ],
  documentSource: [
    "Източник на площта (без лични данни)",
    "Area source (no personal data)",
    "Источник площади (без личных данных)",
    "Flächenquelle (keine persönlichen Daten)",
    "Bron van oppervlakte (geen persoonsgegevens)",
    "Πηγή εμβαδού (χωρίς προσωπικά δεδομένα)",
    "מקור השטח (ללא פרטים אישיים)",
  ],
  owner: ["Собственик", "Owner", "Собственник", "Eigentümer", "Eigenaar", "Ιδιοκτήτης", "בעלים"],
  coOwner: [
    "Съсобственик",
    "Co-owner",
    "Совладелец",
    "Miteigentümer",
    "Mede-eigenaar",
    "Συνιδιοκτήτης",
    "שותף בבעלות",
  ],
  representative: [
    "Представител",
    "Representative",
    "Представитель",
    "Vertreter",
    "Vertegenwoordiger",
    "Εκπρόσωπος",
    "נציג",
  ],
  other: ["Друго", "Other", "Другое", "Andere", "Anders", "Άλλο", "אחר"],
  notProvided: [
    "Не е посочено",
    "Not supplied",
    "Не указано",
    "Nicht angegeben",
    "Niet opgegeven",
    "Δεν δηλώθηκε",
    "לא נמסר",
  ],
} satisfies Record<string, Row>;

export function inquiryReviewCopy(locale: PublicLocale) {
  const index = locales.indexOf(locale);
  return Object.fromEntries(
    Object.entries(rows).map(([key, values]) => [key, values[index]]),
  ) as Record<keyof typeof rows, string>;
}
