import type { PublicLocale } from "@/i18n/config";

// P08/P09 interface copy for public-facts shares. Bulgarian is the source; the other locales
// have not received human approval and must not be treated as indexable or reviewed.
// Locale order: bg, en, ru, de, nl, el, he. Never name the agency's private work record here.
const locales = ["bg", "en", "ru", "de", "nl", "el", "he"] as const;
type Row = readonly [string, string, string, string, string, string, string];
const rows = {
  // P09 recipient page.
  title: [
    "Споделен списък с имоти",
    "Shared list of properties",
    "Общий список объектов",
    "Geteilte Immobilienliste",
    "Gedeelde woninglijst",
    "Κοινοποιημένη λίστα ακινήτων",
    "רשימת נכסים משותפת",
  ],
  badge: [
    "Публично споделен списък",
    "Publicly shared list",
    "Публично доступный список",
    "Öffentlich geteilte Liste",
    "Openbaar gedeelde lijst",
    "Δημόσια κοινοποιημένη λίστα",
    "רשימה משותפת לציבור",
  ],
  publicOnly: [
    "Тук са включени само публични обяви. Няма лични имена, бележки, бюджет или достъп до лични документи.",
    "Only public listings are included here. There are no personal names, notes, budget or access to private documents.",
    "Здесь только публичные объявления. Нет личных имён, заметок, бюджета и доступа к личным документам.",
    "Hier sind nur öffentliche Angebote enthalten. Keine persönlichen Namen, Notizen, kein Budget und kein Zugriff auf private Unterlagen.",
    "Hier staan alleen openbare aanbiedingen. Geen persoonlijke namen, notities, budget of toegang tot privédocumenten.",
    "Περιλαμβάνονται μόνο δημόσιες αγγελίες. Δεν υπάρχουν προσωπικά ονόματα, σημειώσεις, προϋπολογισμός ή πρόσβαση σε ιδιωτικά έγγραφα.",
    "כאן כלולות רק מודעות ציבוריות. אין שמות אישיים, הערות, תקציב או גישה למסמכים פרטיים.",
  ],
  checked: [
    "Данните идват от текущите публични обяви и се проверяват при всяко отваряне на връзката.",
    "Details come from the current public listings and are checked each time this link opens.",
    "Данные берутся из текущих публичных объявлений и проверяются при каждом открытии ссылки.",
    "Die Angaben stammen aus den aktuellen öffentlichen Angeboten und werden bei jedem Öffnen dieses Links geprüft.",
    "De gegevens komen uit de actuele openbare aanbiedingen en worden bij elke opening van deze link gecontroleerd.",
    "Τα στοιχεία προέρχονται από τις τρέχουσες δημόσιες αγγελίες και ελέγχονται κάθε φορά που ανοίγει ο σύνδεσμος.",
    "הפרטים נלקחים מהמודעות הציבוריות העדכניות ונבדקים בכל פעם שהקישור נפתח.",
  ],
  validUntil: [
    "Връзката е валидна до",
    "This link works until",
    "Ссылка действует до",
    "Dieser Link gilt bis",
    "Deze link werkt tot",
    "Ο σύνδεσμος ισχύει έως",
    "הקישור תקף עד",
  ],
  shown: [
    "Показани имоти",
    "Properties shown",
    "Показано объектов",
    "Angezeigte Immobilien",
    "Getoonde woningen",
    "Ακίνητα που εμφανίζονται",
    "נכסים מוצגים",
  ],
  unavailableItem: [
    "Този имот вече не е достъпен в този списък. Не се показват цена, снимки или други данни.",
    "This property is no longer available in this list. No price, photos or other details are shown.",
    "Этот объект больше недоступен в этом списке. Цена, фотографии и другие данные не показываются.",
    "Diese Immobilie ist in dieser Liste nicht mehr verfügbar. Preis, Fotos und weitere Angaben werden nicht angezeigt.",
    "Deze woning is niet meer beschikbaar in deze lijst. Prijs, foto’s en andere gegevens worden niet getoond.",
    "Αυτό το ακίνητο δεν είναι πλέον διαθέσιμο σε αυτή τη λίστα. Δεν εμφανίζονται τιμή, φωτογραφίες ή άλλα στοιχεία.",
    "הנכס הזה אינו זמין עוד ברשימה זו. מחיר, תמונות ופרטים נוספים אינם מוצגים.",
  ],
  allGoneTitle: [
    "Нито един от тези имоти не може да се покаже в момента",
    "None of these properties can be shown right now",
    "Сейчас нельзя показать ни один из этих объектов",
    "Keine dieser Immobilien kann derzeit angezeigt werden",
    "Geen van deze woningen kan nu worden getoond",
    "Κανένα από αυτά τα ακίνητα δεν μπορεί να εμφανιστεί αυτή τη στιγμή",
    "אי אפשר להציג כרגע אף אחד מהנכסים האלה",
  ],
  allGoneBody: [
    "Може да са свалени, продадени или отдадени под наем, или да нямат одобрена версия на този език.",
    "They may have been withdrawn, sold or let, or may not have an approved version in this language.",
    "Возможно, они сняты с публикации, проданы или сданы либо не имеют одобренной версии на этом языке.",
    "Sie wurden möglicherweise zurückgezogen, verkauft oder vermietet, oder es gibt keine freigegebene Fassung in dieser Sprache.",
    "Ze zijn mogelijk ingetrokken, verkocht of verhuurd, of hebben geen goedgekeurde versie in deze taal.",
    "Μπορεί να έχουν αποσυρθεί, πωληθεί ή εκμισθωθεί ή να μην έχουν εγκεκριμένη έκδοση σε αυτή τη γλώσσα.",
    "ייתכן שהם הוסרו, נמכרו או הושכרו, או שאין להם גרסה מאושרת בשפה הזו.",
  ],
  inBulgarian: [
    "Отворете списъка на български",
    "Open this list in Bulgarian",
    "Открыть список на болгарском",
    "Liste auf Bulgarisch öffnen",
    "Lijst in het Bulgaars openen",
    "Άνοιγμα της λίστας στα βουλγαρικά",
    "פתיחת הרשימה בבולגרית",
  ],
  compareThese: [
    "Сравнете тези имоти",
    "Compare these properties",
    "Сравнить эти объекты",
    "Diese Immobilien vergleichen",
    "Deze woningen vergelijken",
    "Σύγκριση αυτών των ακινήτων",
    "השוואת הנכסים האלה",
  ],
  expiredTitle: [
    "Връзката е изтекла",
    "This link has expired",
    "Срок действия ссылки истёк",
    "Dieser Link ist abgelaufen",
    "Deze link is verlopen",
    "Ο σύνδεσμος έχει λήξει",
    "תוקף הקישור פג",
  ],
  expiredBody: [
    "Публичните връзки важат седем дни. Поискайте нова връзка от човека, който Ви я е изпратил, или потърсете текущите имоти.",
    "Public links work for seven days. Ask the person who shared it for a new link, or search the current properties.",
    "Публичные ссылки действуют семь дней. Попросите у отправителя новую ссылку или найдите актуальные объекты.",
    "Öffentliche Links gelten sieben Tage. Bitten Sie die Person, die ihn geteilt hat, um einen neuen Link, oder suchen Sie aktuelle Immobilien.",
    "Openbare links werken zeven dagen. Vraag de afzender om een nieuwe link of zoek actuele woningen.",
    "Οι δημόσιοι σύνδεσμοι ισχύουν επτά ημέρες. Ζητήστε νέο σύνδεσμο από όποιον τον κοινοποίησε ή αναζητήστε τρέχοντα ακίνητα.",
    "קישורים ציבוריים תקפים שבעה ימים. בקשו קישור חדש ממי ששיתף אותו, או חפשו את הנכסים העדכניים.",
  ],
  revokedTitle: [
    "Достъпът чрез тази връзка е прекратен",
    "Access through this link has been stopped",
    "Доступ по этой ссылке прекращён",
    "Der Zugriff über diesen Link wurde beendet",
    "De toegang via deze link is beëindigd",
    "Η πρόσβαση μέσω αυτού του συνδέσμου έχει διακοπεί",
    "הגישה דרך הקישור הזה הופסקה",
  ],
  revokedBody: [
    "Връзката вече не е активна. Поискайте нова връзка от човека, който Ви я е изпратил, или потърсете текущите имоти.",
    "The link is no longer active. Ask the person who shared it for a new link, or search the current properties.",
    "Ссылка больше не активна. Попросите у отправителя новую ссылку или найдите актуальные объекты.",
    "Der Link ist nicht mehr aktiv. Bitten Sie die Person, die ihn geteilt hat, um einen neuen Link, oder suchen Sie aktuelle Immobilien.",
    "De link is niet meer actief. Vraag de afzender om een nieuwe link of zoek actuele woningen.",
    "Ο σύνδεσμος δεν είναι πλέον ενεργός. Ζητήστε νέο σύνδεσμο από όποιον τον κοινοποίησε ή αναζητήστε τρέχοντα ακίνητα.",
    "הקישור אינו פעיל עוד. בקשו קישור חדש ממי ששיתף אותו, או חפשו את הנכסים העדכניים.",
  ],
  unknownTitle: [
    "Тази връзка не може да се отвори",
    "This link can’t be opened",
    "Эту ссылку не удаётся открыть",
    "Dieser Link kann nicht geöffnet werden",
    "Deze link kan niet worden geopend",
    "Δεν είναι δυνατό να ανοίξει αυτός ο σύνδεσμος",
    "אי אפשר לפתוח את הקישור הזה",
  ],
  unknownBody: [
    "Проверете дали целият адрес е копиран. Възможно е връзката никога да не е съществувала.",
    "Check that the whole address was copied. The link may also never have existed.",
    "Проверьте, что адрес скопирован целиком. Возможно, такой ссылки никогда не было.",
    "Prüfen Sie, ob die ganze Adresse kopiert wurde. Der Link hat möglicherweise nie existiert.",
    "Controleer of het hele adres is gekopieerd. De link heeft mogelijk nooit bestaan.",
    "Ελέγξτε ότι αντιγράφηκε ολόκληρη η διεύθυνση. Ο σύνδεσμος μπορεί και να μην υπήρξε ποτέ.",
    "בדקו שהכתובת הועתקה במלואה. ייתכן שהקישור מעולם לא היה קיים.",
  ],
  noCreator: [
    "Не показваме данни за създателя на връзката или лична информация.",
    "We show no information about who shared it, and no personal details.",
    "Мы не показываем сведений о том, кто поделился ссылкой, и личных данных.",
    "Wir zeigen keine Angaben dazu, wer den Link geteilt hat, und keine persönlichen Daten.",
    "We tonen geen informatie over wie de link heeft gedeeld en geen persoonlijke gegevens.",
    "Δεν εμφανίζουμε στοιχεία για το ποιος κοινοποίησε τον σύνδεσμο ούτε προσωπικά δεδομένα.",
    "איננו מציגים מידע על מי ששיתף את הקישור או פרטים אישיים.",
  ],

  // P08 entry and X11 creation review.
  shareSelected: [
    "Сподели избраните",
    "Share selected",
    "Поделиться выбранными",
    "Auswahl teilen",
    "Selectie delen",
    "Κοινοποίηση επιλεγμένων",
    "שיתוף הנבחרים",
  ],
  shareTitle: [
    "Споделете само публичното",
    "Share only the public part",
    "Делитесь только публичным",
    "Nur das Öffentliche teilen",
    "Deel alleen het openbare",
    "Κοινοποιήστε μόνο τα δημόσια στοιχεία",
    "שתפו רק את הציבורי",
  ],
  entryBody: [
    "За да можете да спрете връзката по-късно, този браузър трябва да запази една малка бисквитка. Тя не съдържа лични данни и не съдържа запазените Ви имоти.",
    "So that you can stop a link later, this browser must keep one small cookie. It holds no personal data and none of your saved properties.",
    "Чтобы позже можно было отозвать ссылку, этот браузер должен сохранить один небольшой файл cookie. В нём нет личных данных и сохранённых объектов.",
    "Damit Sie einen Link später beenden können, muss dieser Browser ein kleines Cookie speichern. Es enthält keine persönlichen Daten und keine gespeicherten Immobilien.",
    "Om een link later te kunnen stoppen, moet deze browser één klein cookie bewaren. Het bevat geen persoonlijke gegevens en geen opgeslagen woningen.",
    "Για να μπορείτε να διακόψετε αργότερα έναν σύνδεσμο, αυτός ο περιηγητής πρέπει να κρατήσει ένα μικρό cookie. Δεν περιέχει προσωπικά δεδομένα ούτε αποθηκευμένα ακίνητα.",
    "כדי שתוכלו לעצור קישור בהמשך, הדפדפן הזה צריך לשמור עוגייה קטנה אחת. היא אינה כוללת נתונים אישיים או נכסים שמורים.",
  ],
  entryAction: [
    "Продължи към споделянето",
    "Continue to sharing",
    "Продолжить и поделиться",
    "Weiter zum Teilen",
    "Doorgaan met delen",
    "Συνέχεια στην κοινοποίηση",
    "המשך לשיתוף",
  ],
  entryCaution: [
    "Ако браузърът блокира бисквитките, връзка не може да се създаде, защото по-късно нямаше да можете да я управлявате.",
    "If your browser blocks cookies, a link cannot be created, because you could not manage it afterwards.",
    "Если браузер блокирует cookie, ссылку создать нельзя: потом ею нельзя было бы управлять.",
    "Blockiert Ihr Browser Cookies, kann kein Link erstellt werden, weil Sie ihn danach nicht verwalten könnten.",
    "Blokkeert uw browser cookies, dan kan er geen link worden gemaakt, omdat u die daarna niet kunt beheren.",
    "Αν ο περιηγητής σας μπλοκάρει τα cookies, δεν μπορεί να δημιουργηθεί σύνδεσμος, γιατί δεν θα μπορούσατε να τον διαχειριστείτε μετά.",
    "אם הדפדפן חוסם עוגיות, אי אפשר ליצור קישור, כי לא תוכלו לנהל אותו אחר כך.",
  ],
  reviewLead: [
    "Всеки, който има връзката, вижда само публичните данни, показани по-долу. Не се споделят имена, бележки, бюджет, данни за контакт, документи или други Ваши запазени имоти.",
    "Anyone with the link sees only the public facts shown below. No names, notes, budget, contact details, documents or other saved properties are shared.",
    "Каждый, у кого есть ссылка, видит только публичные данные ниже. Имена, заметки, бюджет, контакты, документы и другие сохранённые объекты не передаются.",
    "Wer den Link hat, sieht nur die unten gezeigten öffentlichen Angaben. Namen, Notizen, Budget, Kontaktdaten, Dokumente und andere gespeicherte Immobilien werden nicht geteilt.",
    "Iedereen met de link ziet alleen de openbare gegevens hieronder. Namen, notities, budget, contactgegevens, documenten en andere opgeslagen woningen worden niet gedeeld.",
    "Όποιος έχει τον σύνδεσμο βλέπει μόνο τα δημόσια στοιχεία παρακάτω. Δεν κοινοποιούνται ονόματα, σημειώσεις, προϋπολογισμός, στοιχεία επικοινωνίας, έγγραφα ή άλλα αποθηκευμένα ακίνητα.",
    "מי שיש לו את הקישור רואה רק את הפרטים הציבוריים שמוצגים למטה. שמות, הערות, תקציב, פרטי קשר, מסמכים ונכסים שמורים אחרים אינם משותפים.",
  ],
  reviewFacts: [
    "Публични данни, които ще се споделят",
    "Public facts that will be shared",
    "Публичные данные, которые будут переданы",
    "Öffentliche Angaben, die geteilt werden",
    "Openbare gegevens die worden gedeeld",
    "Δημόσια στοιχεία που θα κοινοποιηθούν",
    "פרטים ציבוריים שישותפו",
  ],
  include: [
    "Включи във връзката",
    "Include in the link",
    "Включить в ссылку",
    "In den Link aufnehmen",
    "In de link opnemen",
    "Συμπερίληψη στον σύνδεσμο",
    "לכלול בקישור",
  ],
  included: [
    "Включени във връзката",
    "Included in the link",
    "Включено в ссылку",
    "Im Link enthalten",
    "In de link opgenomen",
    "Συμπεριλαμβάνονται στον σύνδεσμο",
    "נכללים בקישור",
  ],
  limit: [
    "Една връзка може да съдържа до 12 имота.",
    "One link can hold up to 12 properties.",
    "В одной ссылке может быть до 12 объектов.",
    "Ein Link kann bis zu 12 Immobilien enthalten.",
    "Eén link kan maximaal 12 woningen bevatten.",
    "Ένας σύνδεσμος μπορεί να περιέχει έως 12 ακίνητα.",
    "קישור אחד יכול לכלול עד 12 נכסים.",
  ],
  skipped: [
    "Запазените имоти, които вече не са достъпни, не могат да се споделят.",
    "Saved properties that are no longer available cannot be shared.",
    "Сохранённые объекты, которые больше недоступны, нельзя передать.",
    "Gespeicherte Immobilien, die nicht mehr verfügbar sind, können nicht geteilt werden.",
    "Opgeslagen woningen die niet meer beschikbaar zijn, kunnen niet worden gedeeld.",
    "Τα αποθηκευμένα ακίνητα που δεν είναι πλέον διαθέσιμα δεν μπορούν να κοινοποιηθούν.",
    "אי אפשר לשתף נכסים שמורים שאינם זמינים עוד.",
  ],
  expiry: [
    "Връзката важи 7 дни след създаването. Можете да я спрете и по-рано.",
    "The link works for 7 days after you create it. You can revoke it earlier.",
    "Ссылка действует 7 дней после создания. Её можно отозвать и раньше.",
    "Der Link gilt 7 Tage nach der Erstellung. Sie können ihn früher widerrufen.",
    "De link werkt 7 dagen na het aanmaken. U kunt hem eerder intrekken.",
    "Ο σύνδεσμος ισχύει 7 ημέρες από τη δημιουργία του. Μπορείτε να τον ανακαλέσετε νωρίτερα.",
    "הקישור תקף 7 ימים מרגע היצירה. אפשר לבטל אותו גם קודם.",
  ],
  reviewed: [
    "Прегледах тези публични данни.",
    "I have reviewed these public facts.",
    "Я просмотрел(а) эти публичные данные.",
    "Ich habe diese öffentlichen Angaben geprüft.",
    "Ik heb deze openbare gegevens bekeken.",
    "Έχω ελέγξει αυτά τα δημόσια στοιχεία.",
    "בדקתי את הפרטים הציבוריים האלה.",
  ],
  create: [
    "Създай връзка за тези обяви",
    "Create a link for these listings",
    "Создать ссылку для этих объявлений",
    "Link für diese Angebote erstellen",
    "Link maken voor deze aanbiedingen",
    "Δημιουργία συνδέσμου για αυτές τις αγγελίες",
    "יצירת קישור למודעות האלה",
  ],
  creating: [
    "Връзката се създава…",
    "Creating the link…",
    "Создаём ссылку…",
    "Link wird erstellt …",
    "Link wordt gemaakt…",
    "Δημιουργία συνδέσμου…",
    "יוצרים את הקישור…",
  ],
  needReview: [
    "Потвърдете, че сте прегледали публичните данни.",
    "Confirm that you have reviewed the public facts.",
    "Подтвердите, что вы просмотрели публичные данные.",
    "Bestätigen Sie, dass Sie die öffentlichen Angaben geprüft haben.",
    "Bevestig dat u de openbare gegevens hebt bekeken.",
    "Επιβεβαιώστε ότι έχετε ελέγξει τα δημόσια στοιχεία.",
    "אשרו שבדקתם את הפרטים הציבוריים.",
  ],
  needOne: [
    "Включете поне един имот.",
    "Include at least one property.",
    "Включите хотя бы один объект.",
    "Nehmen Sie mindestens eine Immobilie auf.",
    "Neem minstens één woning op.",
    "Συμπεριλάβετε τουλάχιστον ένα ακίνητο.",
    "כללו לפחות נכס אחד.",
  ],
  none: [
    "В момента нито един от запазените Ви имоти не може да се сподели.",
    "None of your saved properties can be shared right now.",
    "Сейчас ни один из сохранённых объектов нельзя передать.",
    "Derzeit kann keine Ihrer gespeicherten Immobilien geteilt werden.",
    "Op dit moment kan geen van uw opgeslagen woningen worden gedeeld.",
    "Αυτή τη στιγμή κανένα από τα αποθηκευμένα ακίνητά σας δεν μπορεί να κοινοποιηθεί.",
    "כרגע אי אפשר לשתף אף אחד מהנכסים השמורים שלכם.",
  ],
  selectionUnavailable: [
    "Един или повече от включените имоти вече не са достъпни. Обновете избора и опитайте отново.",
    "One or more included properties are no longer available. Update your selection and try again.",
    "Один или несколько выбранных объектов больше недоступны. Обновите выбор и повторите.",
    "Mindestens eine ausgewählte Immobilie ist nicht mehr verfügbar. Passen Sie die Auswahl an und versuchen Sie es erneut.",
    "Een of meer opgenomen woningen zijn niet meer beschikbaar. Pas uw selectie aan en probeer het opnieuw.",
    "Ένα ή περισσότερα ακίνητα δεν είναι πλέον διαθέσιμα. Ενημερώστε την επιλογή και δοκιμάστε ξανά.",
    "נכס אחד או יותר כבר אינם זמינים. עדכנו את הבחירה ונסו שוב.",
  ],
  rateLimited: [
    "Създадени са твърде много връзки за кратко време. Опитайте отново по-късно.",
    "Too many links were created in a short time. Please try again later.",
    "За короткое время создано слишком много ссылок. Попробуйте позже.",
    "Es wurden zu viele Links in kurzer Zeit erstellt. Bitte versuchen Sie es später erneut.",
    "Er zijn te veel links in korte tijd gemaakt. Probeer het later opnieuw.",
    "Δημιουργήθηκαν πάρα πολλοί σύνδεσμοι σε σύντομο χρονικό διάστημα. Δοκιμάστε ξανά αργότερα.",
    "נוצרו יותר מדי קישורים בזמן קצר. נסו שוב מאוחר יותר.",
  ],
  sessionLost: [
    "Този браузър още не е настроен за управление на връзки. Продължете към споделянето и после създайте връзката отново.",
    "This browser is not set up for managing links yet. Continue to sharing, then create the link again.",
    "Этот браузер ещё не настроен для управления ссылками. Нажмите «Продолжить и поделиться», затем создайте ссылку снова.",
    "Dieser Browser ist noch nicht für die Verwaltung von Links eingerichtet. Fahren Sie fort und erstellen Sie den Link erneut.",
    "Deze browser is nog niet ingesteld voor het beheren van links. Ga verder en maak de link opnieuw.",
    "Αυτός ο περιηγητής δεν έχει ρυθμιστεί ακόμη για διαχείριση συνδέσμων. Συνεχίστε και δημιουργήστε ξανά τον σύνδεσμο.",
    "הדפדפן הזה עדיין לא מוגדר לניהול קישורים. המשיכו וצרו את הקישור שוב.",
  ],
  createFailed: [
    "Връзката не можа да се създаде. Опитайте отново.",
    "The link could not be created. Please try again.",
    "Не удалось создать ссылку. Попробуйте снова.",
    "Der Link konnte nicht erstellt werden. Bitte versuchen Sie es erneut.",
    "De link kon niet worden gemaakt. Probeer het opnieuw.",
    "Δεν ήταν δυνατή η δημιουργία του συνδέσμου. Δοκιμάστε ξανά.",
    "לא ניתן היה ליצור את הקישור. נסו שוב.",
  ],
  createUnknown: [
    "Не можем да потвърдим дали връзката е създадена. Вижте списъка по-долу. Повторният опит ползва същата заявка, затова втора връзка няма да се създаде.",
    "We could not confirm whether the link was created. Check the list below. Trying again uses the same request, so no second link is created.",
    "Не удалось подтвердить, создана ли ссылка. Проверьте список ниже. Повторная попытка использует тот же запрос, поэтому вторая ссылка не появится.",
    "Wir konnten nicht bestätigen, ob der Link erstellt wurde. Prüfen Sie die Liste unten. Ein erneuter Versuch nutzt dieselbe Anfrage, daher entsteht kein zweiter Link.",
    "We konden niet bevestigen of de link is gemaakt. Bekijk de lijst hieronder. Een nieuwe poging gebruikt dezelfde aanvraag, dus er ontstaat geen tweede link.",
    "Δεν μπορέσαμε να επιβεβαιώσουμε αν δημιουργήθηκε ο σύνδεσμος. Δείτε τη λίστα παρακάτω. Η νέα προσπάθεια χρησιμοποιεί το ίδιο αίτημα, οπότε δεν δημιουργείται δεύτερος σύνδεσμος.",
    "לא הצלחנו לאשר אם הקישור נוצר. בדקו את הרשימה למטה. ניסיון חוזר משתמש באותה בקשה, ולכן לא ייווצר קישור שני.",
  ],
  created: [
    "Публичната връзка е създадена",
    "The public link was created",
    "Публичная ссылка создана",
    "Der öffentliche Link wurde erstellt",
    "De openbare link is gemaakt",
    "Ο δημόσιος σύνδεσμος δημιουργήθηκε",
    "הקישור הציבורי נוצר",
  ],
  createdBody: [
    "Вече е в списъка по-долу — там можете да го копирате, да видите кога изтича или да го спрете.",
    "It now appears in the list below, where you can copy it, check when it expires or revoke it.",
    "Она уже в списке ниже: там её можно скопировать, посмотреть срок действия или отозвать.",
    "Er steht jetzt in der Liste unten. Dort können Sie ihn kopieren, das Ablaufdatum prüfen oder ihn widerrufen.",
    "Hij staat nu in de lijst hieronder. Daar kunt u hem kopiëren, de vervaldatum bekijken of hem intrekken.",
    "Βρίσκεται πλέον στη λίστα παρακάτω, όπου μπορείτε να τον αντιγράψετε, να δείτε πότε λήγει ή να τον ανακαλέσετε.",
    "הוא מופיע עכשיו ברשימה למטה, שם אפשר להעתיק אותו, לבדוק מתי תוקפו פג או לבטל אותו.",
  ],
  goToLink: [
    "Към връзката",
    "Go to the link",
    "Перейти к ссылке",
    "Zum Link",
    "Naar de link",
    "Μετάβαση στον σύνδεσμο",
    "מעבר לקישור",
  ],

  // X11M creator management.
  linksTitle: [
    "Споделени връзки",
    "Shared links",
    "Общие ссылки",
    "Geteilte Links",
    "Gedeelde links",
    "Κοινοποιημένοι σύνδεσμοι",
    "קישורים משותפים",
  ],
  linksLead: [
    "Връзки, създадени в този браузър. Само този браузър може да ги управлява.",
    "Links created in this browser. Only this browser can manage them.",
    "Ссылки, созданные в этом браузере. Управлять ими можно только отсюда.",
    "In diesem Browser erstellte Links. Nur dieser Browser kann sie verwalten.",
    "In deze browser gemaakte links. Alleen deze browser kan ze beheren.",
    "Σύνδεσμοι που δημιουργήθηκαν σε αυτόν τον περιηγητή. Μόνο αυτός ο περιηγητής μπορεί να τους διαχειριστεί.",
    "קישורים שנוצרו בדפדפן הזה. רק הדפדפן הזה יכול לנהל אותם.",
  ],
  linksEmpty: [
    "Още не сте създали споделена връзка в този браузър.",
    "You have not created a shared link in this browser yet.",
    "В этом браузере вы ещё не создавали общих ссылок.",
    "In diesem Browser wurde noch kein geteilter Link erstellt.",
    "In deze browser is nog geen gedeelde link gemaakt.",
    "Δεν έχετε δημιουργήσει ακόμη κοινοποιημένο σύνδεσμο σε αυτόν τον περιηγητή.",
    "עדיין לא יצרתם קישור משותף בדפדפן הזה.",
  ],
  linksFailed: [
    "Споделените връзки не се заредиха. Презаредете страницата и опитайте отново.",
    "Shared links could not be loaded. Reload the page to try again.",
    "Не удалось загрузить общие ссылки. Обновите страницу и повторите.",
    "Geteilte Links konnten nicht geladen werden. Laden Sie die Seite neu und versuchen Sie es erneut.",
    "Gedeelde links konden niet worden geladen. Laad de pagina opnieuw en probeer het opnieuw.",
    "Οι κοινοποιημένοι σύνδεσμοι δεν φορτώθηκαν. Ανανεώστε τη σελίδα και δοκιμάστε ξανά.",
    "הקישורים המשותפים לא נטענו. טענו את העמוד מחדש ונסו שוב.",
  ],
  linkTitle: [
    "Публична връзка",
    "Public link",
    "Публичная ссылка",
    "Öffentlicher Link",
    "Openbare link",
    "Δημόσιος σύνδεσμος",
    "קישור ציבורי",
  ],
  linkAddress: [
    "Адрес на връзката",
    "Link address",
    "Адрес ссылки",
    "Link-Adresse",
    "Linkadres",
    "Διεύθυνση συνδέσμου",
    "כתובת הקישור",
  ],
  copy: [
    "Копирай връзката",
    "Copy link",
    "Скопировать ссылку",
    "Link kopieren",
    "Link kopiëren",
    "Αντιγραφή συνδέσμου",
    "העתקת הקישור",
  ],
  copied: [
    "Връзката е копирана",
    "Link copied",
    "Ссылка скопирована",
    "Link kopiert",
    "Link gekopieerd",
    "Ο σύνδεσμος αντιγράφηκε",
    "הקישור הועתק",
  ],
  copyFailed: [
    "Копирането не е налично тук. Маркирайте връзката и я копирайте ръчно.",
    "Copying is not available here. Select the link and copy it by hand.",
    "Копирование здесь недоступно. Выделите ссылку и скопируйте вручную.",
    "Kopieren ist hier nicht verfügbar. Markieren Sie den Link und kopieren Sie ihn manuell.",
    "Kopiëren is hier niet beschikbaar. Selecteer de link en kopieer hem handmatig.",
    "Η αντιγραφή δεν είναι διαθέσιμη εδώ. Επιλέξτε τον σύνδεσμο και αντιγράψτε τον χειροκίνητα.",
    "ההעתקה אינה זמינה כאן. סמנו את הקישור והעתיקו אותו ידנית.",
  ],
  properties: [
    "Имоти във връзката",
    "Properties in this link",
    "Объекты в ссылке",
    "Immobilien im Link",
    "Woningen in de link",
    "Ακίνητα στον σύνδεσμο",
    "נכסים בקישור",
  ],
  createdAt: ["Създадена", "Created", "Создана", "Erstellt", "Gemaakt", "Δημιουργήθηκε", "נוצר"],
  expires: ["Изтича", "Expires", "Истекает", "Läuft ab", "Verloopt", "Λήγει", "תוקף עד"],
  expiredAt: ["Изтекла", "Expired", "Истекла", "Abgelaufen", "Verlopen", "Έληξε", "פג תוקף"],
  revokedAt: ["Спряна", "Revoked", "Отозвана", "Widerrufen", "Ingetrokken", "Ανακλήθηκε", "בוטל"],
  statusActive: ["Активна", "Active", "Активна", "Aktiv", "Actief", "Ενεργός", "פעיל"],
  statusExpiring: [
    "Изтича скоро",
    "Expires soon",
    "Скоро истекает",
    "Läuft bald ab",
    "Verloopt binnenkort",
    "Λήγει σύντομα",
    "פג תוקף בקרוב",
  ],
  viewAs: [
    "Виж публичния получателски изглед",
    "View the public recipient page",
    "Открыть публичную страницу получателя",
    "Öffentliche Empfängeransicht öffnen",
    "Openbare ontvangerweergave bekijken",
    "Προβολή της δημόσιας σελίδας παραλήπτη",
    "צפייה בתצוגת הנמען הציבורית",
  ],
  revoke: [
    "Спри тази връзка",
    "Revoke this link",
    "Отозвать эту ссылку",
    "Diesen Link widerrufen",
    "Deze link intrekken",
    "Ανάκληση αυτού του συνδέσμου",
    "ביטול הקישור הזה",
  ],
  revokeExplain: [
    "Спирането прекратява бъдещия достъп през тази връзка. Публична информация, която вече е била копирана, не може да бъде върната.",
    "Revoking stops future access through this link. Public information that someone has already copied cannot be recalled.",
    "Отзыв прекращает доступ по этой ссылке в будущем. Публичную информацию, которую уже скопировали, вернуть нельзя.",
    "Das Widerrufen beendet den künftigen Zugriff über diesen Link. Öffentliche Angaben, die bereits kopiert wurden, lassen sich nicht zurückholen.",
    "Intrekken stopt toekomstige toegang via deze link. Openbare informatie die al is gekopieerd, kan niet worden teruggehaald.",
    "Η ανάκληση σταματά τη μελλοντική πρόσβαση μέσω αυτού του συνδέσμου. Δημόσιες πληροφορίες που έχουν ήδη αντιγραφεί δεν μπορούν να ανακληθούν.",
    "הביטול עוצר גישה עתידית דרך הקישור הזה. מידע ציבורי שכבר הועתק לא ניתן להחזיר.",
  ],
  revokeNow: [
    "Спри връзката сега",
    "Revoke the link now",
    "Отозвать ссылку сейчас",
    "Link jetzt widerrufen",
    "Link nu intrekken",
    "Ανάκληση συνδέσμου τώρα",
    "ביטול הקישור עכשיו",
  ],
  revoking: [
    "Връзката се спира…",
    "Revoking…",
    "Отзываем…",
    "Wird widerrufen …",
    "Wordt ingetrokken…",
    "Ανάκληση…",
    "מבטלים…",
  ],
  revokedDone: [
    "Връзката е спряна. Бъдещият достъп е прекратен. Вече копирана информация не може да бъде върната.",
    "The link is revoked. Future access has stopped. Information already copied cannot be recalled.",
    "Ссылка отозвана. Доступ в будущем прекращён. Уже скопированную информацию вернуть нельзя.",
    "Der Link ist widerrufen. Künftiger Zugriff ist beendet. Bereits kopierte Angaben lassen sich nicht zurückholen.",
    "De link is ingetrokken. Toekomstige toegang is gestopt. Reeds gekopieerde informatie kan niet worden teruggehaald.",
    "Ο σύνδεσμος ανακλήθηκε. Η μελλοντική πρόσβαση έχει σταματήσει. Πληροφορίες που έχουν ήδη αντιγραφεί δεν μπορούν να ανακληθούν.",
    "הקישור בוטל. הגישה העתידית הופסקה. מידע שכבר הועתק לא ניתן להחזיר.",
  ],
  checking: [
    "Проверяваме спирането",
    "Checking revocation",
    "Проверяем отзыв",
    "Widerruf wird geprüft",
    "Intrekking wordt gecontroleerd",
    "Έλεγχος της ανάκλησης",
    "בודקים את הביטול",
  ],
  checkingBody: [
    "Още не можем да потвърдим спирането. Докато не е потвърдено, връзката може да продължава да работи.",
    "We could not confirm the revocation yet. Until it is confirmed, the link may still work.",
    "Пока не удалось подтвердить отзыв. Пока он не подтверждён, ссылка может продолжать работать.",
    "Der Widerruf konnte noch nicht bestätigt werden. Bis zur Bestätigung funktioniert der Link möglicherweise noch.",
    "De intrekking kon nog niet worden bevestigd. Tot die bevestiging werkt de link mogelijk nog.",
    "Δεν μπορέσαμε ακόμη να επιβεβαιώσουμε την ανάκληση. Μέχρι να επιβεβαιωθεί, ο σύνδεσμος μπορεί να λειτουργεί ακόμη.",
    "עדיין לא הצלחנו לאשר את הביטול. עד לאישור, ייתכן שהקישור עדיין פועל.",
  ],
  checkAgain: [
    "Провери отново",
    "Check again",
    "Проверить снова",
    "Erneut prüfen",
    "Opnieuw controleren",
    "Έλεγχος ξανά",
    "בדיקה חוזרת",
  ],
  revokeFailed: [
    "Тази връзка не може да бъде спряна от този браузър. Презаредете страницата и проверете състоянието ѝ.",
    "This link could not be revoked from this browser. Reload the page and check its status.",
    "Эту ссылку не удалось отозвать из этого браузера. Обновите страницу и проверьте её состояние.",
    "Dieser Link konnte von diesem Browser aus nicht widerrufen werden. Laden Sie die Seite neu und prüfen Sie den Status.",
    "Deze link kon niet vanuit deze browser worden ingetrokken. Laad de pagina opnieuw en controleer de status.",
    "Ο σύνδεσμος δεν μπόρεσε να ανακληθεί από αυτόν τον περιηγητή. Ανανεώστε τη σελίδα και ελέγξτε την κατάστασή του.",
    "לא ניתן היה לבטל את הקישור מהדפדפן הזה. טענו את העמוד מחדש ובדקו את מצבו.",
  ],
  renew: [
    "За да споделите тези имоти отново, създайте нова връзка. Тази не може да бъде възстановена.",
    "To share these properties again, create a new link. This one cannot be revived.",
    "Чтобы поделиться этими объектами снова, создайте новую ссылку. Эту восстановить нельзя.",
    "Um diese Immobilien erneut zu teilen, erstellen Sie einen neuen Link. Dieser lässt sich nicht wiederherstellen.",
    "Maak een nieuwe link om deze woningen opnieuw te delen. Deze kan niet worden hersteld.",
    "Για να κοινοποιήσετε ξανά αυτά τα ακίνητα, δημιουργήστε νέο σύνδεσμο. Αυτός δεν μπορεί να ανακτηθεί.",
    "כדי לשתף שוב את הנכסים האלה, צרו קישור חדש. את הקישור הזה אי אפשר להחיות.",
  ],
  lostTitle: [
    "Не намирате връзка, която сте споделили?",
    "Cannot find a link you shared?",
    "Не находите ссылку, которой поделились?",
    "Sie finden einen geteilten Link nicht?",
    "Vindt u een gedeelde link niet terug?",
    "Δεν βρίσκετε έναν σύνδεσμο που κοινοποιήσατε;",
    "לא מוצאים קישור ששיתפתם?",
  ],
  lostBody: [
    "Връзка, създадена в друг браузър или преди данните на този браузър да бъдат изчистени, не може да се управлява оттук. Самата връзка не връща управлението. Тя спира да работи в посочения час, а нова връзка не изключва старата.",
    "A link created in another browser, or before this browser’s data was cleared, cannot be managed here, and the link itself cannot restore that. It stops working at the time it states, and creating a new link does not turn off an old one.",
    "Ссылкой, созданной в другом браузере или до очистки данных этого браузера, отсюда управлять нельзя, и сама ссылка этого не восстановит. Она перестаёт работать в указанное время, а новая ссылка не отключает старую.",
    "Ein Link, der in einem anderen Browser oder vor dem Löschen der Daten dieses Browsers erstellt wurde, lässt sich hier nicht verwalten, und der Link selbst stellt das nicht wieder her. Er läuft zum angegebenen Zeitpunkt ab, und ein neuer Link deaktiviert einen alten nicht.",
    "Een link die in een andere browser of vóór het wissen van de gegevens van deze browser is gemaakt, kan hier niet worden beheerd, en de link zelf herstelt dat niet. Hij werkt niet meer op het vermelde tijdstip, en een nieuwe link schakelt een oude niet uit.",
    "Ένας σύνδεσμος που δημιουργήθηκε σε άλλον περιηγητή ή πριν διαγραφούν τα δεδομένα αυτού του περιηγητή δεν μπορεί να διαχειριστεί εδώ, και ο ίδιος ο σύνδεσμος δεν το επαναφέρει. Παύει να λειτουργεί τη στιγμή που αναγράφεται και ένας νέος σύνδεσμος δεν απενεργοποιεί τον παλιό.",
    "קישור שנוצר בדפדפן אחר, או לפני שנתוני הדפדפן הזה נמחקו, אי אפשר לנהל מכאן, והקישור עצמו אינו משחזר זאת. הוא מפסיק לפעול במועד שצוין, וקישור חדש אינו מבטל קישור ישן.",
  ],
  lostReport: [
    "Ако връзка Ви тревожи, помолете агенцията да я прегледа.",
    "If a link worries you, ask the agency to review it.",
    "Если ссылка вызывает тревогу, попросите агентство её проверить.",
    "Wenn Ihnen ein Link Sorgen macht, bitten Sie die Agentur, ihn zu prüfen.",
    "Maakt een link u zorgen, vraag het kantoor dan om hem te beoordelen.",
    "Αν κάποιος σύνδεσμος σας ανησυχεί, ζητήστε από το γραφείο να τον εξετάσει.",
    "אם קישור מדאיג אתכם, בקשו מהסוכנות לבדוק אותו.",
  ],
} satisfies Record<string, Row>;

export type ShareCopy = { [K in keyof typeof rows]: string };

/** Every locale's rows, for completeness and wording checks. */
export const shareCopyRows: Readonly<Record<keyof ShareCopy, Row>> = rows;

export function shareCopy(locale: PublicLocale): ShareCopy {
  const index = locales.indexOf(locale);
  return Object.fromEntries(
    Object.entries(rows).map(([key, row]) => [key, row[index]]),
  ) as ShareCopy;
}
