import type { PublicLocale } from "@/i18n/config";

// Interface copy only; this does not approve listing translations or promise a service slot.
const locales = ["bg", "en", "ru", "de", "nl", "el", "he"] as const;
type Row = readonly [string, string, string, string, string, string, string];
const rows = {
  title: [
    "Предпочитания за оглед",
    "Viewing preferences",
    "Пожелания к просмотру",
    "Besichtigungswünsche",
    "Bezichtigingsvoorkeuren",
    "Προτιμήσεις επίσκεψης",
    "העדפות לביקור",
  ],
  note: [
    "Това е заявка, не резервация. Брокерът трябва да провери възможностите и да потвърди уговорката.",
    "This is a request, not a booking. A broker must check availability and confirm the arrangement.",
    "Это запрос, а не бронирование. Брокер проверит возможность и подтвердит договорённость.",
    "Dies ist eine Anfrage, keine Buchung. Ein Makler muss Verfügbarkeit und Termin bestätigen.",
    "Dit is een verzoek, geen boeking. Een makelaar moet beschikbaarheid en afspraak bevestigen.",
    "Αυτό είναι αίτημα, όχι κράτηση. Ο μεσίτης πρέπει να ελέγξει τη διαθεσιμότητα και να επιβεβαιώσει.",
    "זו בקשה, לא הזמנה. מתווך צריך לבדוק זמינות ולאשר את התיאום.",
  ],
  format: [
    "Предпочитан формат",
    "Preferred format",
    "Предпочтительный формат",
    "Gewünschte Form",
    "Gewenste vorm",
    "Προτιμώμενη μορφή",
    "מתכונת מועדפת",
  ],
  inPerson: ["На място", "In person", "Лично", "Vor Ort", "Ter plaatse", "Διά ζώσης", "במקום"],
  noPreference: [
    "Нямам предпочитание",
    "No preference",
    "Нет предпочтений",
    "Keine Präferenz",
    "Geen voorkeur",
    "Χωρίς προτίμηση",
    "אין העדפה",
  ],
  timezone: [
    "Часова зона на предпочитаните часове",
    "Timezone for preferred times",
    "Часовой пояс желаемого времени",
    "Zeitzone der gewünschten Zeiten",
    "Tijdzone voor voorkeurstijden",
    "Ζώνη ώρας προτιμώμενων ωρών",
    "אזור זמן למועדים המועדפים",
  ],
  timezoneHint: [
    "Използвайте именувана зона, напр. Europe/Sofia, Europe/London или Asia/Jerusalem.",
    "Use a named zone, such as Europe/Sofia, Europe/London or Asia/Jerusalem.",
    "Укажите именованный пояс: Europe/Sofia, Europe/London или Asia/Jerusalem.",
    "Benannte Zone verwenden, z. B. Europe/Sofia, Europe/London oder Asia/Jerusalem.",
    "Gebruik een benoemde zone, zoals Europe/Sofia, Europe/London of Asia/Jerusalem.",
    "Χρησιμοποιήστε ονομασμένη ζώνη, π.χ. Europe/Sofia, Europe/London ή Asia/Jerusalem.",
    "השתמשו באזור בעל שם, כגון Europe/Sofia, Europe/London או Asia/Jerusalem.",
  ],
  window: [
    "Предпочитан интервал",
    "Preferred window",
    "Желаемый интервал",
    "Gewünschter Zeitraum",
    "Voorkeursperiode",
    "Προτιμώμενο διάστημα",
    "טווח מועדף",
  ],
  start: [
    "От дата и час",
    "From date and time",
    "С даты и времени",
    "Ab Datum und Uhrzeit",
    "Vanaf datum en tijd",
    "Από ημερομηνία και ώρα",
    "מתאריך ושעה",
  ],
  end: [
    "До дата и час",
    "Until date and time",
    "До даты и времени",
    "Bis Datum und Uhrzeit",
    "Tot datum en tijd",
    "Έως ημερομηνία και ώρα",
    "עד תאריך ושעה",
  ],
  extraWindows: [
    "Още предпочитани интервали (до 3)",
    "More preferred windows (up to 3)",
    "Дополнительные интервалы (до 3)",
    "Weitere Zeiträume (bis zu 3)",
    "Meer voorkeursperioden (maximaal 3)",
    "Περισσότερα διαστήματα (έως 3)",
    "טווחים מועדפים נוספים (עד 3)",
  ],
  clockChoice: [
    "Избор при повторен час",
    "Repeated-clock choice",
    "Выбор повторяющегося времени",
    "Auswahl bei doppelter Uhrzeit",
    "Keuze bij herhaalde kloktijd",
    "Επιλογή επαναλαμβανόμενης ώρας",
    "בחירה בשעה שחוזרת",
  ],
  automatic: [
    "Само ако часът е еднозначен",
    "Only if the time is unambiguous",
    "Только если время однозначно",
    "Nur bei eindeutiger Uhrzeit",
    "Alleen bij eenduidige tijd",
    "Μόνο εάν η ώρα είναι σαφής",
    "רק אם השעה חד משמעית",
  ],
  earlier: [
    "Първата поява",
    "First occurrence",
    "Первое вхождение",
    "Erstes Vorkommen",
    "Eerste keer",
    "Πρώτη εμφάνιση",
    "המופע הראשון",
  ],
  later: [
    "Втората поява",
    "Second occurrence",
    "Второе вхождение",
    "Zweites Vorkommen",
    "Tweede keer",
    "Δεύτερη εμφάνιση",
    "המופע השני",
  ],
  clockHint: [
    "При връщане на часовника изберете първата или втората поява за всеки повторен час. Несъществуващите часове се отхвърлят.",
    "When clocks go back, choose the first or second occurrence of each repeated time. Nonexistent times are rejected.",
    "При переводе часов назад выберите первое или второе вхождение повторённого времени. Несуществующее время отклоняется.",
    "Bei der Zeitumstellung das erste oder zweite Vorkommen wählen. Nicht existierende Zeiten werden abgelehnt.",
    "Kies bij terugzetten van de klok de eerste of tweede keer. Niet-bestaande tijden worden geweigerd.",
    "Όταν το ρολόι γυρίζει πίσω, επιλέξτε την πρώτη ή δεύτερη εμφάνιση. Οι ανύπαρκτες ώρες απορρίπτονται.",
    "כשהשעון חוזר אחורה, בחרו במופע הראשון או השני. שעות שאינן קיימות יידחו.",
  ],
  accessNeeds: [
    "Практически нужди за достъп",
    "Practical access needs",
    "Практические потребности доступа",
    "Praktische Zugangsbedürfnisse",
    "Praktische toegangsbehoeften",
    "Πρακτικές ανάγκες πρόσβασης",
    "צורכי נגישות מעשיים",
  ],
  accessHint: [
    "По желание; например достъп без стъпала. Не включвайте медицински данни, адреси или кодове за достъп. Бележката е само за екипа по заявката и няма да е в публичната разписка.",
    "Optional; for example, step-free access. Do not include medical details, addresses or access codes. This note is for the request team and will not appear in the public receipt.",
    "Необязательно; например, доступ без ступеней. Не указывайте медицинские сведения, адреса или коды. Заметку увидит команда запроса; в публичной квитанции её не будет.",
    "Optional, z. B. stufenloser Zugang. Keine medizinischen Angaben, Adressen oder Zugangscodes. Die Notiz ist nur für das Anfrage-Team, nicht für die öffentliche Bestätigung.",
    "Optioneel, bijvoorbeeld drempelloze toegang. Geen medische gegevens, adressen of toegangscodes. Alleen voor het aanvraagteam, niet op de openbare ontvangstbevestiging.",
    "Προαιρετικό, π.χ. πρόσβαση χωρίς σκαλοπάτια. Χωρίς ιατρικά στοιχεία, διευθύνσεις ή κωδικούς. Μόνο για την ομάδα αιτήματος, όχι στη δημόσια απόδειξη.",
    "רשות, למשל גישה ללא מדרגות. אין לכלול מידע רפואי, כתובות או קודי כניסה. ההערה מיועדת לצוות המטפל ולא תופיע באישור הציבורי.",
  ],
  invalidTime: [
    "Проверете датата, бъдещия интервал и избора при повторен час.",
    "Check the date, future time window and repeated-clock choice.",
    "Проверьте дату, будущий интервал и выбор повторённого времени.",
    "Datum, zukünftigen Zeitraum und Auswahl der doppelten Uhrzeit prüfen.",
    "Controleer datum, toekomstige periode en keuze bij herhaalde tijd.",
    "Ελέγξτε ημερομηνία, μελλοντικό διάστημα και επιλογή επαναλαμβανόμενης ώρας.",
    "בדקו את התאריך, הטווח העתידי והבחירה בשעה החוזרת.",
  ],
  unavailable: [
    "Няма текущи одобрени публични данни за този имот на избрания език. Статусът на уговорката е показан отделно.",
    "No current approved public property details are available in this language. The arrangement status is shown separately.",
    "Нет актуальных одобренных публичных данных об объекте на этом языке. Статус договорённости показан отдельно.",
    "Keine aktuellen freigegebenen öffentlichen Immobiliendaten in dieser Sprache. Der Terminstatus wird separat angezeigt.",
    "Geen actuele goedgekeurde openbare woninggegevens in deze taal. De afspraakstatus wordt apart getoond.",
    "Δεν υπάρχουν τρέχοντα εγκεκριμένα δημόσια στοιχεία σε αυτή τη γλώσσα. Η κατάσταση συνάντησης εμφανίζεται χωριστά.",
    "אין פרטי נכס ציבוריים מאושרים ועדכניים בשפה זו. מצב התיאום מוצג בנפרד.",
  ],
} satisfies Record<string, Row>;
export function viewingCopy(locale: PublicLocale) {
  const index = locales.indexOf(locale);
  return Object.fromEntries(Object.entries(rows).map(([key, row]) => [key, row[index]])) as Record<
    keyof typeof rows,
    string
  >;
}
