// Private workflow translations are drafts, not human language acceptance.
const en = {
  title: "Proposals",
  empty: "No proposals are available in your current scope.",
  create: "Prepare a proposal",
  prepare: "Save proposal draft",
  revise: "Save a new revision",
  counter: "Propose revised terms",
  terms: "Exact terms",
  parties: "Parties to this revision",
  buyer: "Buyer or tenant",
  additionalParties: "Additional buyers or tenants",
  additionalHint:
    "Select every additional party whose agreement is required. The primary party is included automatically. Changing the parties requires a new review.",
  seller: "Recorded seller or landlord",
  amount: "Amount",
  currency: "Currency",
  period: "Price basis",
  total: "Total price",
  month: "Per month",
  paymentBasis: "Payment basis",
  conditions: "Conditions (one per line)",
  inclusions: "Included items (one per line)",
  deadline: "Response deadline in Sofia with UTC offset",
  reason: "Reason or response note",
  review: "Record exact-terms review",
  submit: "Make available to these parties",
  withdraw: "Withdraw this revision",
  expire: "Record expiry",
  reviewCheck:
    "I reviewed these exact parties, terms, source and deadline. This is a coordination record, not legal approval.",
  submitCheck:
    "I reviewed the exact revision and its audience. Make it available to these parties in their client workspace.",
  response: "Your response",
  agree: "Record my agreement for the next step",
  decline: "Decline this revision",
  record: "Record my response",
  responseNote:
    "Your response applies to this revision only. Every required party must agree and the case review must be current before an overall agreement is recorded.",
  boundary:
    "This proposal coordinates the next step. It is not a legal signature, payment instruction or completed transaction. Your broker coordinates the required professional review.",
  notCurrent:
    "A newer draft is under review. This earlier revision remains visible as history and cannot receive a new response.",
  expiredNotice: "The response deadline has passed. This revision cannot be accepted or countered.",
  changed: "The approved source or proposal terms changed. A new review is required.",
  pending:
    "Your response is recorded. Overall agreement is still pending the remaining required parties and case review.",
  agreementBlocked:
    "Your agreement was not recorded. Ask your broker to complete the required case review before trying again.",
  noResponses: "No party responses have been recorded for this revision.",
  history: "Earlier revisions",
  responses: "Recorded party responses",
  revision: "Revision",
  source: "Source listing revision",
  reverify: "Confirm your identity",
  reverifyNotice:
    "Confirm your identity again before recording this response. Your draft is retained.",
  bounded: "Showing up to 50 proposals you can access.",
  draft: "Draft · not shared",
  reviewed: "Reviewed · not shared",
  submitted: "Submitted",
  awaiting_response: "Awaiting party responses",
  countered: "Countered",
  declined: "Declined",
  withdrawn: "Withdrawn",
  expired: "Expired",
  agreed_for_next_step: "Agreed for the next step",
};
type Copy = { [K in keyof typeof en]: string };
const bg: Copy = {
  ...en,
  title: "Предложения",
  empty: "Няма достъпни предложения за текущия ви достъп.",
  create: "Подготовка на предложение",
  prepare: "Запазване на чернова",
  revise: "Запазване на нова версия",
  counter: "Предлагане на изменени условия",
  terms: "Точни условия",
  parties: "Страни по тази версия",
  buyer: "Купувач или наемател",
  additionalParties: "Допълнителни купувачи или наематели",
  additionalHint:
    "Изберете всички допълнителни страни, чието съгласие е необходимо. Основната страна се включва автоматично. Промяната на страните изисква нов преглед.",
  seller: "Записан продавач или наемодател",
  amount: "Сума",
  currency: "Валута",
  period: "Ценова основа",
  total: "Обща цена",
  month: "На месец",
  paymentBasis: "Основа за плащане",
  conditions: "Условия (по едно на ред)",
  inclusions: "Включени вещи (по една на ред)",
  deadline: "Срок за отговор в София с UTC отместване",
  reason: "Причина или бележка към отговора",
  review: "Запис на прегледа на точните условия",
  submit: "Предоставяне на тези страни",
  withdraw: "Оттегляне на версията",
  expire: "Запис на изтичане",
  response: "Вашият отговор",
  agree: "Запис на моето съгласие за следваща стъпка",
  decline: "Отказ от тази версия",
  record: "Запис на моя отговор",
  history: "Предишни версии",
  responses: "Записани отговори на страните",
  revision: "Версия",
  source: "Изходна версия на обявата",
  reverify: "Потвърдете самоличността си",
  draft: "Чернова · не е споделена",
  reviewed: "Прегледана · не е споделена",
  submitted: "Подадена",
  awaiting_response: "Очакват се отговори на страните",
  countered: "Насрещно предложение",
  declined: "Отказана",
  withdrawn: "Оттеглена",
  expired: "Изтекла",
  agreed_for_next_step: "Съгласие за следваща стъпка",
};
const ru: Copy = {
  ...en,
  title: "Предложения",
  empty: "Нет предложений в рамках вашего текущего доступа.",
  create: "Подготовить предложение",
  prepare: "Сохранить черновик",
  revise: "Сохранить новую версию",
  counter: "Предложить изменённые условия",
  terms: "Точные условия",
  parties: "Стороны этой версии",
  buyer: "Покупатель или арендатор",
  additionalParties: "Дополнительные покупатели или арендаторы",
  additionalHint:
    "Выберите все дополнительные стороны, согласие которых необходимо. Основная сторона включается автоматически. Изменение состава требует новой проверки.",
  seller: "Записанный продавец или арендодатель",
  amount: "Сумма",
  currency: "Валюта",
  period: "Основа цены",
  total: "Полная цена",
  month: "В месяц",
  paymentBasis: "Основа оплаты",
  conditions: "Условия (по одному в строке)",
  inclusions: "Включённые предметы (по одному в строке)",
  deadline: "Срок ответа в Софии со смещением UTC",
  reason: "Причина или примечание к ответу",
  review: "Записать проверку точных условий",
  submit: "Открыть этим сторонам",
  withdraw: "Отозвать эту версию",
  expire: "Записать истечение срока",
  response: "Ваш ответ",
  agree: "Записать моё согласие на следующий шаг",
  decline: "Отклонить эту версию",
  record: "Записать мой ответ",
  history: "Предыдущие версии",
  responses: "Записанные ответы сторон",
  revision: "Версия",
  source: "Исходная версия объявления",
  reverify: "Подтвердите личность",
  draft: "Черновик · не открыт сторонам",
  reviewed: "Проверено · не открыто сторонам",
  submitted: "Подано",
  awaiting_response: "Ожидаются ответы сторон",
  countered: "Встречное предложение",
  declined: "Отклонено",
  withdrawn: "Отозвано",
  expired: "Срок истёк",
  agreed_for_next_step: "Согласовано для следующего шага",
};
export const proposalCopy = (locale: string): Copy =>
  locale === "bg" ? bg : locale === "ru" ? ru : en;
