import type { FormCopy } from "@/ui/form/contract";

const en = {
  inventory: "Inventory",
  create: "New listing",
  back: "Back to inventory",
  edit: "Working draft",
  save: "Save draft",
  saved: "Draft saved",
  empty: "No listings are available to your role yet.",
  next: "Review the draft and prepare a separate review candidate when ready.",
  open: "Open listing",
  prepare: "Freeze review candidate",
  source: "Bulgarian source",
  review: "Review and publication",
  scope: "Review scope or reason",
  reviewFacts: "Approve factual revision",
  submit: "Submit editorial review",
  approve: "Approve source revision",
  prepareManifest: "Prepare publication",
  activate: "Activate reviewed manifest",
  restrict: "Restrict all destinations",
  withdraw: "Withdraw all destinations",
  confirm: "I reviewed this exact revision and the stated scope.",
  noRevision: "Save and freeze a draft to create a review candidate.",
  noPublication: "No publication has been activated.",
  privateAddress: "Exact address stays private. Public location is limited to settlement.",
  draftNotice:
    "Saving or freezing a draft does not approve its facts or publish it. Existing live content stays separate.",
  factsHint:
    "Keep unknowns explicit. For conflicting numbers, enter each source value separated by |. Do not resolve a conflict without evidence.",
  blocked:
    "This action could not be completed. Review the current revision, required evidence and your access before trying again.",
  succeeded: "The action was recorded.",
  operation: "Operation receipt",
  recorded: "Recorded",
  pending: "Outcome not yet confirmed",
  revision: "Revision",
  state: "Status",
  location: "Location",
  reference: "Reference",
  purpose: "Purpose",
  permissions: "Your role cannot edit this record.",
  o10: {
    instruction: "Open the listing that is waiting for action, or search for a property by number.",
    search: "Search",
    searchHint: "Listing number, title or settlement",
    filters: "Filters",
    purpose: "Purpose",
    type: "Property type",
    any: "Any",
    apply: "Show",
    views: "Listing views",
    list: "Listings",
    all: "All",
    needs: "Needs action",
    mine: "Mine",
    open: "Open listing {reference}",
    noMatch: "No listing matches this search.",
    clear: "Clear the search",
    noneNeeds: "No listing is waiting for action.",
    noneMine: "No listing is assigned to you.",
    actions: {
      changes: "Changes requested",
      review: "Review needed",
      facts: "Facts needed",
      availability: "Availability to confirm",
      translation_review: "Translation to review · {locale}",
    },
    count: "Matches: {total}",
    more: "Show more",
    first: "Back to the first page",
    shortened: "Search uses up to {n} characters; the rest was left out.",
    restarted: "That page is no longer available; showing the first page.",
  },
  o16: {
    instruction: "See which approvals are missing before the listing can be published.",
    candidate: "Publication candidate",
    publicNone: "Public version: none confirmed",
    publicLive: "Public version: {locales}",
    candidateDraft: "Working draft · Bulgarian",
    candidateApproved: "Approved version {n} · Bulgarian",
    candidateUnapproved: "Review version {n} · Bulgarian · not approved yet",
    newerPending:
      "Review version {newer} is not approved yet; publishing still uses approved version {approved}.",
    approvalsFor: "Approvals for version {n}",
    perMonth: "per month",
    working: "Working version BG",
    workingLine: "Current content from the editor · {reference}",
    photoCaption: "{reference} · Photo 1 of {total} · Original listing photo",
    noPhoto: "No reviewed photo yet",
    changesNeedReview: "Changes to the text or photos need a new review.",
    approvals: "Required approvals",
    checks: {
      facts: "Facts are reviewed",
      photos: "Photo rights are confirmed",
      language: "The language is approved",
      version: "The exact version is reviewed",
      seller: "The seller's instructions are current",
      claims: "Professional claims are reviewed",
    },
    done: "Done",
    missing: "Missing",
    blocked: "Publishing stays blocked until every human approval is in place.",
    eligible:
      "The exact candidate is eligible for a publication decision. Nothing is published until a person decides.",
    reviewMissing: "Review the missing approvals",
    toDecision: "Go to the publication decision",
    decisionByPublisher: "A staff member who may publish takes this decision; you cannot publish.",
    editText: "Edit the text manually",
    back: "Back",
    beforeYouDecide: "Before you decide",
    price: "Price",
    area: "Area",
    needsCheck: "Needs checking",
    remaining: "What remains before publishing",
    published: "The listing is published",
    publishedDetail:
      "Listing {reference} · {locale} · published by {name}. The public page shows exactly the approved package {digest}.",
    publicPage: "Public page",
    openPublic: "Open the public page",
    publishTitle: "Publication decision · {locale}",
    publishLead:
      "You publish exactly this package. The checks run again when you decide; if anything changed, nothing is published.",
    rows: {
      manifest: "Manifest",
      facts: "Facts and terms",
      seller: "Seller instructions",
      media: "Media / public place",
      language: "Language / professional scope",
      actor: "Publishing actor",
      effect: "Intended effect",
      factualDecision: "Factual approval",
      editorialDecision: "Editorial approval",
    },
    decidedBy: "{name} · {when} · {state}",
    currentName: "(name as in the directory now)",
    deciderUnknown: "Recorded decider not found in the directory",
    decisionMissing: "No recorded approval for this package",
    decisionUnavailable: "The approval record could not be read now. Activation checks it again.",
    decisionMismatch: "The recorded approval does not match this package",
    approvalStates: {
      pending: "pending",
      approved: "approved",
      rejected: "rejected",
      invalidated: "invalidated",
      expired: "expired",
      withdrawn: "withdrawn",
    },
    package: "{reference} · {locale} · package {digest}",
    approvedScope: "Approved for the stated scope",
    sellerCurrent: "Current for this version",
    mediaRights: "{n} photos with confirmed rights",
    sourceLanguage: "BG is the source language; translations are published separately",
    localeApproved: "Translation approved for this exact source",
    actorRole: "{name} · publishing authority",
    effectReplace: "{host} shows this package instead of the current one",
    effectNew: "{host} shows this package",
    publishNote:
      "The decision is recorded under your name. Butler cannot publish. If the result is unclear, you will see that activation is still being checked.",
    cancel: "Cancel",
    publishPackage: "Publish the package",
    decisionScope: "Decision scope",
    scopeDefault: "Publish the {locale} package for {host}",
    confirmPackage: "I reviewed exactly this package and the stated scope.",
    checking: "Activation is still being checked",
    checkingLead:
      'The action has a check number. We do not show "published" until the result is confirmed.',
    checkingRows: {
      number: "Check number",
      candidate: "Candidate",
      local: "Local result",
      external: "External channels",
      recovery: "Recovery",
    },
    checkingLocal: "Waiting for an observed confirmation",
    checkingExternal: "Not published automatically",
    checkingRecovery: "Check the same request; no new action",
    checkingNote:
      "A finished background task does not prove the content is public. An older attempt cannot activate a withdrawn candidate.",
    checkAgain: "Check the publication",
    checkingCandidateUnknown: "Known once the result is confirmed",
    activationRecorded: "Activation recorded",
    activationNotCurrent:
      "Listing {reference} · {locale} · activated by {name}. The public page no longer shows this package; now: {state}.",
    stateNewer: "a newer package is live",
    stateNone: "not published",
    stateIneligible: "not shown publicly, the publication conditions are no longer met",
    notEligibleLocale: "This package is not eligible for a decision in {locale} now: {reason}.",
    reviewException: "Review the exception",
  },
  o12: {
    title: "Edit listing",
    instruction: "Change the description, save it and review it for publication.",
    sourceLine: "Bulgarian source · Working draft",
    noDraft:
      "No working draft is saved yet. The fields show the latest recorded revision where it records them; nothing changes until you save.",
    tabs: "Listing parts",
    facts: "Facts",
    text: "Text",
    photos: "Photos",
    titleLabel: "Listing title",
    descriptionLabel: "Description",
    workingDraft: "Working draft BG",
    saveText: "Save the description",
    saveFacts: "Save the facts",
    keptSaved:
      "This page's earlier save already went through. Your current values are kept below: review the latest version and apply them again.",
    reviewForPublication: "Review for publication",
    correctPublished: "Correct the published listing",
    sourceTitle: "Facts from the BG source · Listing {reference}",
    sourceReviewed: "Facts from an approved source",
    sourceUnreviewed: "Facts not reviewed yet",
    terms: "Listing terms and facts",
    changeInFacts: "Change in Facts",
    priceLabel: "Price · EUR",
    areaLabel: "{basis} · m²",
    bedroomsLabel: "Bedrooms",
    settlementLabel: "Settlement",
    bedrooms: { one: "{n} bedroom", other: "{n} bedrooms" } as Partial<
      Record<Intl.LDMLPluralRule, string>
    > & { other: string },
    butler: "Butler",
    butlerStatus: "Under your control",
    butlerOffer:
      "I can improve the structure of the text while keeping the price, area, bedrooms, district and reference exact.",
    butlerRecord: "Current record",
    butlerScope: "Permitted context only",
    butlerNote: "You will get a draft to review. Nothing is sent or published.",
    butlerPrepare: "Prepare a proposal",
    butlerUnavailable:
      "Butler cannot draft listing text yet. Write it yourself; only you save the draft.",
    manualHeading: "Prefer to do it yourself?",
    manual: "Continue without Butler",
    saved: "Working draft saved",
    savedDetail:
      "Saved for listing {reference} · BG · Working draft. Publication and approvals stay separate.",
    savedDescription: "Description at the last save",
    savedLater: "The listing has changed since this save. Open it to see the current draft.",
    toTask: "Back to the current task",
    close: "Close",
    reviewTitle: "Review for publication",
    backToEdit: "Back to editing",
    choose: "Choose…",
    unsupported: "not supported, choose again",
    needsInput: "Needed before this draft can be saved",
    unsavedTitle: "You have unsaved changes",
    unsavedBody: "Save the working draft, discard these changes, or stay on this page.",
    saveDraft: "Save draft",
    discard: "Discard changes",
    stay: "Stay",
    continue: "Continue",
    unsavedNative:
      "You have unsaved changes. Save the draft with the button below, discard them, or stay here.",
    restored: "Unsaved changes from earlier on this page are restored. Save them or discard them.",
    discardRestored: "Discard these changes",
    staleRestored:
      "Unsaved changes from before someone else saved this listing are kept. Compare them with the current version, then apply or discard them.",
    applyStale: "Apply my earlier changes",
    priceRecorded:
      "The source recorded {value}. It cannot be carried over as it is: enter the price in EUR, or confirm that it stays unknown for now.",
    periodTotal: "total price",
    periodMonth: "per month",
    periodNone: "period not stated",
    priceUnreadable: "a price in a form this editor cannot show",
    priceKeepUnknown: "Keep the price unknown for now",
    priceUnknownError: "Enter the price, or confirm that it stays unknown for now.",
    requiredError: "Fill in this field.",
    chooseError: "Choose a value from the list.",
    invalidError: "Check this value.",
    noscriptLeave:
      "Without JavaScript, save before opening Photos or Review, or your changes are lost.",
  },
  labels: {
    propertyType: "Property type",
    purpose: "Purpose",
    country: "Country",
    region: "Region",
    settlement: "Settlement",
    exactAddress: "Private exact address",
    title: "Bulgarian title",
    description: "Bulgarian description",
    brokerNote:
      "Private broker intake note (optional; never published or sent to Butler automatically)",
    priceState: "Price status",
    price: "Price in EUR",
    areaState: "Area status",
    area: "Area in m²",
    areaBasis: "Area basis",
    bedroomsState: "Bedroom status",
    bedrooms: "Bedrooms",
    sourceReference: "Source or evidence reference",
    sourceClass: "Source type",
    sourceLanguage: "Language of the source evidence",
  },
  form: {
    errorSummary: "Check the form",
    pending: "Saving…",
    reapply: "Apply reviewed draft to current revision",
    yourValue: "Your draft",
    latestValue: "Current value",
    revision: "Revision",
    reference: "Reference",
    recordedAt: "Recorded at",
    unknown: "We could not confirm the result",
    draftRetained: "Your entered values are retained below. Check the operation before retrying.",
  } satisfies FormCopy,
};
type Copy = typeof en;
const bg: Copy = {
  ...en,
  inventory: "Имоти и обяви",
  create: "Нова обява",
  back: "Към обявите",
  edit: "Работна чернова",
  save: "Запазване на чернова",
  saved: "Черновата е запазена",
  empty: "Няма достъпни обяви за вашата роля.",
  next: "Проверете черновата и създайте отделна версия за преглед, когато е готова.",
  open: "Отваряне на обявата",
  prepare: "Създаване на версия за преглед",
  source: "Български източник",
  review: "Преглед и публикуване",
  scope: "Обхват на прегледа или причина",
  reviewFacts: "Одобряване на фактите",
  submit: "Изпращане за редакционен преглед",
  approve: "Одобряване на изходната версия",
  prepareManifest: "Подготовка за публикуване",
  activate: "Публикуване на одобрения пакет",
  restrict: "Ограничаване във всички канали",
  withdraw: "Сваляне от всички канали",
  confirm: "Прегледах точно тази версия и посочения обхват.",
  noRevision: "Запазете чернова и създайте версия за преглед.",
  noPublication: "Няма активирано публикуване.",
  privateAddress: "Точният адрес е поверителен. Публично се показва само населеното място.",
  draftNotice:
    "Запазването и създаването на версия не одобряват фактите и не публикуват. Публикуваното съдържание остава отделно.",
  factsHint:
    "Запазвайте неизвестните стойности. При противоречащи числа въведете стойностите, разделени с |. Не избирайте стойност без доказателство.",
  blocked:
    "Действието не е завършено. Проверете текущата версия, нужните доказателства и вашия достъп.",
  succeeded: "Действието е записано.",
  operation: "Потвърждение за действие",
  recorded: "Записано",
  pending: "Резултатът още не е потвърден",
  revision: "Версия",
  state: "Състояние",
  location: "Местоположение",
  reference: "Референция",
  purpose: "Цел",
  permissions: "Вашата роля няма право да редактира този запис.",
  o10: {
    instruction: "Отворете обявата, която чака действие, или потърсете имот по номер.",
    search: "Търсене",
    searchHint: "Номер на обявата, заглавие или населено място",
    filters: "Филтри",
    purpose: "Цел",
    type: "Вид имот",
    any: "Всички",
    apply: "Покажете",
    views: "Изгледи на обявите",
    list: "Обяви",
    all: "Всички",
    needs: "Нужно действие",
    mine: "Мои",
    open: "Отворете обява {reference}",
    noMatch: "Няма обява, която съвпада с търсенето.",
    clear: "Изчистете търсенето",
    noneNeeds: "Няма обяви, които чакат действие.",
    noneMine: "Нямате възложени обяви.",
    actions: {
      changes: "Поискани промени",
      review: "Нужен преглед",
      facts: "Нужни факти",
      availability: "Наличност за потвърждение",
      translation_review: "Превод за преглед · {locale}",
    },
    count: "Съвпадения: {total}",
    more: "Покажете още",
    first: "Към първата страница",
    shortened: "Търсенето използва до {n} знака; останалото е пропуснато.",
    restarted: "Тази страница вече не е налична; показваме първата.",
  },
  o16: {
    instruction: "Вижте кои одобрения липсват, преди обявата да бъде публикувана.",
    candidate: "Кандидат за публикуване",
    publicNone: "Публична версия: няма потвърдена",
    publicLive: "Публична версия: {locales}",
    candidateDraft: "Работна чернова · Български",
    candidateApproved: "Одобрена версия {n} · Български",
    candidateUnapproved: "Версия за преглед {n} · Български · още не е одобрена",
    newerPending:
      "Версия за преглед {newer} още не е одобрена; публикуването използва одобрената версия {approved}.",
    approvalsFor: "Одобрения за версия {n}",
    perMonth: "на месец",
    working: "Работна версия BG",
    workingLine: "Текущо съдържание от редактора · {reference}",
    photoCaption: "{reference} · Снимка 1 от {total} · Оригинална снимка от обявата",
    noPhoto: "Още няма прегледана снимка",
    changesNeedReview: "Промените в текста или снимките изискват нов преглед.",
    approvals: "Нужни одобрения",
    checks: {
      facts: "Фактите са проверени",
      photos: "Правата върху снимките са потвърдени",
      language: "Езикът е одобрен",
      version: "Точната версия е прегледана",
      seller: "Указанията на продавача са в сила",
      claims: "Професионалните твърдения са прегледани",
    },
    done: "Готово",
    missing: "Липсва",
    blocked: "Публикуването остава блокирано до всички човешки одобрения.",
    eligible: "Точният кандидат е допустим за решение. Нищо не се публикува, докато човек не реши.",
    reviewMissing: "Прегледайте липсващите одобрения",
    toDecision: "Към решението на публикуващия",
    decisionByPublisher:
      "Решението се взема от служител с право да публикува; вие не можете да публикувате.",
    editText: "Редактирайте текста ръчно",
    back: "Назад",
    beforeYouDecide: "Преди да решите",
    price: "Цена",
    area: "Площ",
    needsCheck: "Нужна е проверка",
    remaining: "Какво остава преди публикуване",
    published: "Обявата е публикувана",
    publishedDetail:
      "Обява {reference} · {locale} · публикувана от {name}. Публичната страница показва точно одобрения пакет {digest}.",
    publicPage: "Публична страница",
    openPublic: "Отворете публичната страница",
    publishTitle: "Решение за публикуване · {locale}",
    publishLead:
      "Публикувате точно този пакет. Проверките се повтарят в момента на командата; ако нещо се е променило, нищо не се публикува.",
    rows: {
      manifest: "Манифест",
      facts: "Факти и термини",
      seller: "Инструкции на продавача",
      media: "Медии / публично място",
      language: "Език / професионален обхват",
      actor: "Публикуващ актьор",
      effect: "Предвиден ефект",
      factualDecision: "Фактическо одобрение",
      editorialDecision: "Редакционно одобрение",
    },
    decidedBy: "{name} · {when} · {state}",
    currentName: "(името според текущия справочник)",
    deciderUnknown: "Записаният решаващ не е в справочника",
    decisionMissing: "Няма записано одобрение за този пакет",
    decisionUnavailable:
      "Записът за одобрение не може да се прочете сега. Активирането го проверява отново.",
    decisionMismatch: "Записаното одобрение не съответства на този пакет",
    approvalStates: {
      pending: "чака",
      approved: "одобрено",
      rejected: "отказано",
      invalidated: "обезсилено",
      expired: "изтекло",
      withdrawn: "оттеглено",
    },
    package: "{reference} · {locale} · пакет {digest}",
    approvedScope: "Одобрени за посочения обхват",
    sellerCurrent: "В сила за тази версия",
    mediaRights: "{n} снимки с потвърдени права",
    sourceLanguage: "BG е изходният език; преводите се публикуват отделно",
    localeApproved: "Преводът е одобрен за точно този източник",
    actorRole: "{name} · правомощие за публикуване",
    effectReplace: "{host} показва този пакет вместо досегашния",
    effectNew: "{host} показва този пакет",
    publishNote:
      "Решението се записва с Вашето име. Butler не може да публикува. При неясен резултат ще видите, че активирането още се проверява.",
    cancel: "Отказ",
    publishPackage: "Публикувайте пакета",
    decisionScope: "Обхват на решението",
    scopeDefault: "Публикуване на {locale} пакета за {host}",
    confirmPackage: "Прегледах точно този пакет и посочения обхват.",
    checking: "Активирането още се проверява",
    checkingLead:
      "Действието има номер за проверка. Не показваме „публикувано“, докато резултатът не бъде потвърден.",
    checkingRows: {
      number: "Номер за проверка",
      candidate: "Кандидат",
      local: "Локален резултат",
      external: "Външни канали",
      recovery: "Възстановяване",
    },
    checkingLocal: "Чака наблюдавано потвърждение",
    checkingExternal: "Не са автоматично публикувани",
    checkingRecovery: "Проверка на същата заявка, без ново действие",
    checkingNote:
      "Завършена фонова задача не доказва, че съдържанието е публично. По-стар вариант не може да активира отменен кандидат.",
    checkAgain: "Проверете публикуването",
    checkingCandidateUnknown: "Ще се знае, когато резултатът бъде потвърден",
    activationRecorded: "Активирането е записано",
    activationNotCurrent:
      "Обява {reference} · {locale} · активирана от {name}. Публичната страница вече не показва този пакет; сега: {state}.",
    stateNewer: "показва се по-нов пакет",
    stateNone: "не е публикувана",
    stateIneligible: "не се показва публично, условията за публикуване вече не са изпълнени",
    notEligibleLocale: "Този пакет сега не е допустим за решение на {locale}: {reason}.",
    reviewException: "Прегледайте изключението",
  },
  o12: {
    title: "Редактиране на обява",
    instruction: "Променете описанието, запишете го и го прегледайте за публикуване.",
    sourceLine: "Български източник · Работна чернова",
    noDraft:
      "Още няма записана работна чернова. Полетата показват последната записана версия, доколкото тя ги съдържа; нищо не се променя, докато не запишете.",
    tabs: "Части на обявата",
    facts: "Факти",
    text: "Текст",
    photos: "Снимки",
    titleLabel: "Заглавие на обявата",
    descriptionLabel: "Описание",
    workingDraft: "Работна чернова BG",
    saveText: "Запишете описанието",
    saveFacts: "Запишете фактите",
    keptSaved:
      "По-ранното записване от тази страница вече е минало. Текущите ви стойности са запазени по-долу: прегледайте последната версия и ги приложете отново.",
    reviewForPublication: "Прегледайте за публикуване",
    correctPublished: "Коригирайте публикуваната обява",
    sourceTitle: "Факти от BG източника · Обява {reference}",
    sourceReviewed: "Факти от одобрен източник",
    sourceUnreviewed: "Фактите още не са прегледани",
    terms: "Условия и факти на обявата",
    changeInFacts: "Променете във „Факти“",
    priceLabel: "Цена · EUR",
    areaLabel: "{basis} · m²",
    bedroomsLabel: "Спални",
    settlementLabel: "Населено място",
    bedrooms: { one: "{n} спалня", other: "{n} спални" },
    butler: "Butler",
    butlerStatus: "Под Ваш контрол",
    butlerOffer:
      "Мога да подобря структурата на текста, като запазя цената, площта, спалните, района и номера точно.",
    butlerRecord: "Текущ запис",
    butlerScope: "Само разрешен контекст",
    butlerNote: "Ще получите чернова за преглед. Нищо не се изпраща или публикува.",
    butlerPrepare: "Подгответе предложение",
    butlerUnavailable:
      "Butler още не подготвя текстове на обяви. Напишете го сами — само Вие записвате черновата.",
    manualHeading: "Предпочитате сами?",
    manual: "Продължете без Butler",
    saved: "Работната чернова е записана",
    savedDetail:
      "Записано за обява {reference} · BG · Работна чернова. Публикацията и одобренията остават отделни.",
    savedDescription: "Описание при последния запис",
    savedLater: "Обявата е променяна след този запис. Отворете я, за да видите текущата чернова.",
    toTask: "Към текущата задача",
    close: "Затваряне",
    reviewTitle: "Преглед за публикуване",
    backToEdit: "Към редактирането",
    choose: "Изберете…",
    unsupported: "не се поддържа, изберете отново",
    needsInput: "Нужно, преди черновата да може да се запише",
    unsavedTitle: "Имате незаписани промени",
    unsavedBody: "Запишете работната чернова, откажете промените или останете на страницата.",
    saveDraft: "Запишете черновата",
    discard: "Откажете промените",
    stay: "Останете",
    continue: "Продължете",
    unsavedNative:
      "Имате незаписани промени. Запишете черновата с бутона по-долу, откажете ги или останете тук.",
    restored:
      "Незаписаните промени от по-рано на тази страница са възстановени. Запишете ги или ги откажете.",
    discardRestored: "Откажете тези промени",
    staleRestored:
      "Незаписаните промени отпреди друг човек да запише обявата са запазени. Сравнете ги с текущата версия и ги приложете или откажете.",
    applyStale: "Приложете моите по-ранни промени",
    priceRecorded:
      "Източникът е записал {value}. Цената не може да се пренесе както е: въведете я в EUR или потвърдете, че засега остава неизвестна.",
    periodTotal: "обща цена",
    periodMonth: "на месец",
    periodNone: "без посочен период",
    priceUnreadable: "цена във форма, която редакторът не може да покаже",
    priceKeepUnknown: "Засега оставете цената неизвестна",
    priceUnknownError: "Въведете цената или потвърдете, че засега остава неизвестна.",
    requiredError: "Попълнете това поле.",
    chooseError: "Изберете стойност от списъка.",
    invalidError: "Проверете тази стойност.",
    noscriptLeave:
      "Без JavaScript запишете, преди да отворите „Снимки“ или прегледа, иначе промените се губят.",
  },
  labels: {
    propertyType: "Вид имот",
    purpose: "Цел",
    country: "Държава",
    region: "Област",
    settlement: "Населено място",
    exactAddress: "Поверителен точен адрес",
    title: "Заглавие на български",
    description: "Описание на български",
    brokerNote:
      "Частна бележка за въвеждане (по избор; не се публикува или изпраща автоматично към Butler)",
    priceState: "Състояние на цената",
    price: "Цена в EUR",
    areaState: "Състояние на площта",
    area: "Площ в m²",
    areaBasis: "Вид площ",
    bedroomsState: "Състояние на спалните",
    bedrooms: "Спални",
    sourceReference: "Източник или доказателство",
    sourceClass: "Вид източник",
    sourceLanguage: "Език на източника",
  },
  form: {
    errorSummary: "Проверете формуляра",
    pending: "Запазване…",
    reapply: "Прилагане на прегледаната чернова към текущата версия",
    yourValue: "Вашата чернова",
    latestValue: "Текуща стойност",
    revision: "Версия",
    reference: "Референция",
    recordedAt: "Записано на",
    unknown: "Резултатът не е потвърден",
    draftRetained: "Въведеното е запазено по-долу. Проверете действието преди повторен опит.",
  },
};
const ru: Copy = {
  ...en,
  inventory: "Объекты и объявления",
  create: "Новое объявление",
  back: "К объявлениям",
  edit: "Рабочий черновик",
  save: "Сохранить черновик",
  saved: "Черновик сохранён",
  empty: "Для вашей роли пока нет доступных объявлений.",
  next: "Проверьте черновик, затем создайте отдельную версию для проверки.",
  open: "Открыть объявление",
  prepare: "Создать версию для проверки",
  source: "Болгарский источник",
  review: "Проверка и публикация",
  scope: "Область проверки или причина",
  reviewFacts: "Одобрить факты",
  submit: "Передать на редакционную проверку",
  approve: "Одобрить исходную версию",
  prepareManifest: "Подготовить публикацию",
  activate: "Опубликовать проверенный пакет",
  restrict: "Ограничить во всех каналах",
  withdraw: "Снять со всех каналов",
  confirm: "Я проверил именно эту версию и указанный объём.",
  noRevision: "Сохраните черновик и создайте версию для проверки.",
  noPublication: "Публикаций ещё нет.",
  privateAddress: "Точный адрес закрыт. Публично показывается только населённый пункт.",
  draftNotice:
    "Сохранение черновика и создание версии не одобряют факты и не публикуют. Публичная версия остаётся отдельно.",
  factsHint:
    "Сохраняйте неизвестные значения. Противоречащие числа разделяйте знаком |. Не выбирайте значение без доказательств.",
  blocked: "Действие не завершено. Проверьте текущую версию, доказательства и ваши права.",
  succeeded: "Действие записано.",
  operation: "Подтверждение действия",
  recorded: "Записано",
  pending: "Результат ещё не подтверждён",
  revision: "Версия",
  state: "Статус",
  location: "Местоположение",
  reference: "Референция",
  purpose: "Цель",
  permissions: "Ваша роль не может редактировать эту запись.",
  o10: {
    instruction: "Откройте объявление, которое ждёт действия, или найдите объект по номеру.",
    search: "Поиск",
    searchHint: "Номер объявления, заголовок или населённый пункт",
    filters: "Фильтры",
    purpose: "Цель",
    type: "Вид объекта",
    any: "Любой",
    apply: "Показать",
    views: "Виды списка объявлений",
    list: "Объявления",
    all: "Все",
    needs: "Нужно действие",
    mine: "Мои",
    open: "Открыть объявление {reference}",
    noMatch: "Ни одно объявление не подходит под поиск.",
    clear: "Сбросить поиск",
    noneNeeds: "Нет объявлений, ожидающих действия.",
    noneMine: "Вам не назначено ни одного объявления.",
    actions: {
      changes: "Запрошены изменения",
      review: "Нужна проверка",
      facts: "Нужны факты",
      availability: "Подтвердить доступность",
      translation_review: "Перевод на проверку · {locale}",
    },
    count: "Совпадений: {total}",
    more: "Показать ещё",
    first: "К первой странице",
    shortened: "Поиск учитывает до {n} символов; остальное пропущено.",
    restarted: "Эта страница больше недоступна; показываем первую.",
  },
  o16: {
    instruction:
      "Посмотрите, каких одобрений не хватает, прежде чем объявление можно опубликовать.",
    candidate: "Кандидат на публикацию",
    publicNone: "Публичная версия: не подтверждена",
    publicLive: "Публичная версия: {locales}",
    candidateDraft: "Рабочий черновик · Болгарский",
    candidateApproved: "Одобренная версия {n} · Болгарский",
    candidateUnapproved: "Версия для проверки {n} · Болгарский · ещё не одобрена",
    newerPending:
      "Версия для проверки {newer} ещё не одобрена; публикация использует одобренную версию {approved}.",
    approvalsFor: "Одобрения для версии {n}",
    perMonth: "в месяц",
    working: "Рабочая версия BG",
    workingLine: "Текущее содержимое из редактора · {reference}",
    photoCaption: "{reference} · Фото 1 из {total} · Исходное фото объявления",
    noPhoto: "Проверенных фото пока нет",
    changesNeedReview: "Изменения текста или фото требуют новой проверки.",
    approvals: "Необходимые одобрения",
    checks: {
      facts: "Факты проверены",
      photos: "Права на фото подтверждены",
      language: "Язык одобрен",
      version: "Точная версия проверена",
      seller: "Указания продавца действуют",
      claims: "Профессиональные утверждения проверены",
    },
    done: "Готово",
    missing: "Не хватает",
    blocked: "Публикация заблокирована, пока нет всех одобрений людей.",
    eligible:
      "Точный кандидат допустим к решению о публикации. Ничего не публикуется, пока решение не примет человек.",
    reviewMissing: "Проверить недостающие одобрения",
    toDecision: "К решению о публикации",
    decisionByPublisher:
      "Это решение принимает сотрудник с правом публикации; вы не можете публиковать.",
    editText: "Редактировать текст вручную",
    back: "Назад",
    beforeYouDecide: "Прежде чем решать",
    price: "Цена",
    area: "Площадь",
    needsCheck: "Нужна проверка",
    remaining: "Что осталось до публикации",
    published: "Объявление опубликовано",
    publishedDetail:
      "Объявление {reference} · {locale} · опубликовано: {name}. Публичная страница показывает именно одобренный пакет {digest}.",
    publicPage: "Публичная страница",
    openPublic: "Открыть публичную страницу",
    publishTitle: "Решение о публикации · {locale}",
    publishLead:
      "Вы публикуете именно этот пакет. Проверки повторяются в момент решения; если что-то изменилось, ничего не публикуется.",
    rows: {
      manifest: "Манифест",
      facts: "Факты и условия",
      seller: "Указания продавца",
      media: "Медиа / публичное место",
      language: "Язык / профессиональный объём",
      actor: "Кто публикует",
      effect: "Ожидаемый результат",
      factualDecision: "Фактическое одобрение",
      editorialDecision: "Редакционное одобрение",
    },
    decidedBy: "{name} · {when} · {state}",
    currentName: "(имя по текущему справочнику)",
    deciderUnknown: "Записанный решающий не найден в справочнике",
    decisionMissing: "Нет записанного одобрения для этого пакета",
    decisionUnavailable: "Запись об одобрении сейчас не читается. Активация проверит её снова.",
    decisionMismatch: "Записанное одобрение не соответствует этому пакету",
    approvalStates: {
      pending: "ожидает",
      approved: "одобрено",
      rejected: "отклонено",
      invalidated: "аннулировано",
      expired: "истекло",
      withdrawn: "отозвано",
    },
    package: "{reference} · {locale} · пакет {digest}",
    approvedScope: "Одобрены в указанном объёме",
    sellerCurrent: "Действуют для этой версии",
    mediaRights: "{n} фото с подтверждёнными правами",
    sourceLanguage: "BG — исходный язык; переводы публикуются отдельно",
    localeApproved: "Перевод одобрен именно для этого источника",
    actorRole: "{name} · право публикации",
    effectReplace: "{host} показывает этот пакет вместо текущего",
    effectNew: "{host} показывает этот пакет",
    publishNote:
      "Решение записывается под вашим именем. Butler не может публиковать. Если результат неясен, вы увидите, что активация ещё проверяется.",
    cancel: "Отмена",
    publishPackage: "Опубликовать пакет",
    decisionScope: "Объём решения",
    scopeDefault: "Публикация пакета {locale} для {host}",
    confirmPackage: "Я проверил именно этот пакет и указанный объём.",
    checking: "Активация ещё проверяется",
    checkingLead:
      "У действия есть номер для проверки. Мы не показываем «опубликовано», пока результат не подтверждён.",
    checkingRows: {
      number: "Номер для проверки",
      candidate: "Кандидат",
      local: "Локальный результат",
      external: "Внешние каналы",
      recovery: "Восстановление",
    },
    checkingLocal: "Ожидает наблюдаемого подтверждения",
    checkingExternal: "Не публикуются автоматически",
    checkingRecovery: "Проверка того же запроса, без нового действия",
    checkingNote:
      "Завершённая фоновая задача не доказывает, что содержимое публично. Более старая попытка не может активировать снятого кандидата.",
    checkAgain: "Проверить публикацию",
    checkingCandidateUnknown: "Станет известен после подтверждения результата",
    activationRecorded: "Активация записана",
    activationNotCurrent:
      "Объявление {reference} · {locale} · активировано: {name}. Публичная страница больше не показывает этот пакет; сейчас: {state}.",
    stateNewer: "показывается более новый пакет",
    stateNone: "не опубликовано",
    stateIneligible: "не показывается публично, условия публикации больше не выполнены",
    notEligibleLocale: "Этот пакет сейчас недопустим для решения на {locale}: {reason}.",
    reviewException: "Посмотреть исключение",
  },
  o12: {
    title: "Редактирование объявления",
    instruction: "Измените описание, сохраните его и проверьте перед публикацией.",
    sourceLine: "Болгарский источник · Рабочий черновик",
    noDraft:
      "Рабочий черновик ещё не сохранён. Поля показывают последнюю записанную версию, насколько она их содержит; ничего не меняется, пока вы не сохраните.",
    tabs: "Разделы объявления",
    facts: "Факты",
    text: "Текст",
    photos: "Фото",
    titleLabel: "Заголовок объявления",
    descriptionLabel: "Описание",
    workingDraft: "Рабочий черновик BG",
    saveText: "Сохранить описание",
    saveFacts: "Сохранить факты",
    keptSaved:
      "Более раннее сохранение с этой страницы уже прошло. Ваши текущие значения сохранены ниже: проверьте последнюю версию и примените их снова.",
    reviewForPublication: "Проверить перед публикацией",
    correctPublished: "Исправить опубликованное объявление",
    sourceTitle: "Факты из BG-источника · Объявление {reference}",
    sourceReviewed: "Факты из одобренного источника",
    sourceUnreviewed: "Факты ещё не проверены",
    terms: "Условия и факты объявления",
    changeInFacts: "Изменить в «Фактах»",
    priceLabel: "Цена · EUR",
    areaLabel: "{basis} · m²",
    bedroomsLabel: "Спальни",
    settlementLabel: "Населённый пункт",
    bedrooms: { one: "{n} спальня", few: "{n} спальни", many: "{n} спален", other: "{n} спальни" },
    butler: "Butler",
    butlerStatus: "Под вашим контролем",
    butlerOffer:
      "Я могу улучшить структуру текста, сохранив цену, площадь, спальни, район и номер точно.",
    butlerRecord: "Текущая запись",
    butlerScope: "Только разрешённый контекст",
    butlerNote: "Вы получите черновик для проверки. Ничего не отправляется и не публикуется.",
    butlerPrepare: "Подготовить предложение",
    butlerUnavailable:
      "Butler пока не готовит тексты объявлений. Напишите текст сами — сохраняете черновик только вы.",
    manualHeading: "Предпочитаете сами?",
    manual: "Продолжить без Butler",
    saved: "Рабочий черновик сохранён",
    savedDetail:
      "Сохранено для объявления {reference} · BG · Рабочий черновик. Публикация и одобрения остаются отдельными.",
    savedDescription: "Описание при последнем сохранении",
    savedLater:
      "Объявление менялось после этого сохранения. Откройте его, чтобы увидеть текущий черновик.",
    toTask: "К текущей задаче",
    close: "Закрыть",
    reviewTitle: "Проверка перед публикацией",
    backToEdit: "К редактированию",
    choose: "Выберите…",
    unsupported: "не поддерживается, выберите заново",
    needsInput: "Нужно, чтобы черновик можно было сохранить",
    unsavedTitle: "Есть несохранённые изменения",
    unsavedBody: "Сохраните рабочий черновик, отмените изменения или останьтесь на странице.",
    saveDraft: "Сохранить черновик",
    discard: "Отменить изменения",
    stay: "Остаться",
    continue: "Продолжить",
    unsavedNative:
      "Есть несохранённые изменения. Сохраните черновик кнопкой ниже, отмените их или останьтесь здесь.",
    restored:
      "Несохранённые изменения, сделанные ранее на этой странице, восстановлены. Сохраните или отмените их.",
    discardRestored: "Отменить эти изменения",
    staleRestored:
      "Несохранённые изменения, сделанные до того, как объявление сохранил кто-то другой, сохранены. Сравните их с текущей версией и примените или отмените.",
    applyStale: "Применить мои прежние изменения",
    priceRecorded:
      "Источник записал {value}. Цену нельзя перенести как есть: введите её в EUR или подтвердите, что пока она остаётся неизвестной.",
    periodTotal: "общая цена",
    periodMonth: "в месяц",
    periodNone: "период не указан",
    priceUnreadable: "цену в виде, который редактор не может показать",
    priceKeepUnknown: "Пока оставить цену неизвестной",
    priceUnknownError: "Введите цену или подтвердите, что пока она остаётся неизвестной.",
    requiredError: "Заполните это поле.",
    chooseError: "Выберите значение из списка.",
    invalidError: "Проверьте это значение.",
    noscriptLeave:
      "Без JavaScript сохраните перед переходом в «Фото» или к проверке, иначе изменения пропадут.",
  },
  labels: {
    propertyType: "Вид объекта",
    purpose: "Цель",
    country: "Страна",
    region: "Регион",
    settlement: "Населённый пункт",
    exactAddress: "Закрытый точный адрес",
    title: "Заголовок на болгарском",
    description: "Описание на болгарском",
    brokerNote:
      "Частная заметка для ввода (необязательно; не публикуется и не передаётся Butler автоматически)",
    priceState: "Статус цены",
    price: "Цена в EUR",
    areaState: "Статус площади",
    area: "Площадь в m²",
    areaBasis: "Вид площади",
    bedroomsState: "Статус спален",
    bedrooms: "Спальни",
    sourceReference: "Источник или доказательство",
    sourceClass: "Вид источника",
    sourceLanguage: "Язык источника",
  },
  form: {
    errorSummary: "Проверьте форму",
    pending: "Сохранение…",
    reapply: "Применить проверенный черновик к текущей версии",
    yourValue: "Ваш черновик",
    latestValue: "Текущее значение",
    revision: "Версия",
    reference: "Референция",
    recordedAt: "Записано",
    unknown: "Результат не подтверждён",
    draftRetained: "Введённые значения сохранены ниже. Проверьте действие перед повтором.",
  },
};
export const inventoryCopy = (locale: string): Copy =>
  locale === "bg" ? bg : locale === "ru" ? ru : en;

const options = {
  known: ["Known", "Известно", "Известно"],
  unknown: ["Unknown", "Неизвестно", "Неизвестно"],
  not_supplied: ["Not supplied", "Непредоставено", "Не предоставлено"],
  not_applicable: ["Not applicable", "Неприложимо", "Неприменимо"],
  withheld: ["Withheld", "Не се разкрива", "Не раскрывается"],
  conflicting: ["Conflicting", "Противоречиво", "Противоречиво"],
  apartment: ["Apartment", "Апартамент", "Квартира"],
  house: ["House", "Къща", "Дом"],
  plot: ["Land", "Парцел", "Участок"],
  commercial: ["Commercial", "Търговски", "Коммерческий"],
  hotel: ["Hotel", "Хотел", "Отель"],
  development: ["Development", "Строителен проект", "Строительный проект"],
  other: ["Other", "Друг", "Другой"],
  sale: ["Sale", "Продажба", "Продажа"],
  long_term_rent: ["Long-term rent", "Дългосрочен наем", "Долгосрочная аренда"],
  living: ["Living area", "Жилищна площ", "Жилая площадь"],
  usable: ["Usable area", "Полезна площ", "Полезная площадь"],
  built: ["Built area", "Застроена площ", "Застроенная площадь"],
  gross_floor: ["Gross floor area", "РЗП", "Общая площадь этажей"],
  total: ["Total area", "Обща площ", "Общая площадь"],
  land: ["Land area", "Площ на терена", "Площадь участка"],
  source_supplied: ["Supplied by source", "Предоставено от източник", "Предоставлено источником"],
  owner_confirmed: ["Confirmed by owner", "Потвърдено от собственик", "Подтверждено собственником"],
  agency_observed: ["Observed by agency", "Установено от агенцията", "Установлено агентством"],
  document_reviewed: ["Document reviewed", "Прегледан документ", "Документ проверен"],
  professionally_reviewed: [
    "Professional review",
    "Професионален преглед",
    "Профессиональная проверка",
  ],
  system_calculated: ["Calculated", "Изчислено", "Рассчитано"],
  legacy_import: ["Legacy import", "Стар импорт", "Прежний импорт"],
} satisfies Record<string, [string, string, string]>;
export function optionLabel(value: string, locale: string) {
  const labels = options[value as keyof typeof options];
  return labels?.[locale === "bg" ? 1 : locale === "ru" ? 2 : 0] ?? value.replaceAll("_", " ");
}

/** "1 спалня", "2 спални": the count with its plural form for the page locale. */
export function bedroomCount(locale: string, n: number) {
  const forms = inventoryCopy(locale).o12.bedrooms;
  const form = forms[new Intl.PluralRules(locale).select(n)] ?? forms.other;
  return form.replace("{n}", new Intl.NumberFormat(locale).format(n));
}
