import type { FormCopy } from "@/ui/form/contract";

const en = {
  inventory: "Inventory",
  create: "New listing",
  back: "Back to inventory",
  edit: "Working draft",
  save: "Save draft",
  saved: "Draft saved",
  empty: "No listings are available to your role yet.",
  next: "Review the draft and prepare a separate review candidate when ready.",
  open: "Open listing",
  prepare: "Freeze review candidate",
  source: "Bulgarian source",
  review: "Review and publication",
  scope: "Review scope or reason",
  reviewFacts: "Approve factual revision",
  submit: "Submit editorial review",
  approve: "Approve source revision",
  prepareManifest: "Prepare publication",
  activate: "Activate reviewed manifest",
  restrict: "Restrict all destinations",
  withdraw: "Withdraw all destinations",
  confirm: "I reviewed this exact revision and the stated scope.",
  noRevision: "Save and freeze a draft to create a review candidate.",
  noPublication: "No publication has been activated.",
  privateAddress: "Exact address stays private. Public location is limited to settlement.",
  draftNotice:
    "Saving or freezing a draft does not approve its facts or publish it. Existing live content stays separate.",
  factsHint:
    "Keep unknowns explicit. For conflicting numbers, enter each source value separated by |. Do not resolve a conflict without evidence.",
  blocked:
    "This action could not be completed. Review the current revision, required evidence and your access before trying again.",
  succeeded: "The action was recorded.",
  operation: "Operation receipt",
  recorded: "Recorded",
  pending: "Outcome not yet confirmed",
  revision: "Revision",
  state: "Status",
  location: "Location",
  reference: "Reference",
  purpose: "Purpose",
  permissions: "Your role cannot edit this record.",
  labels: {
    propertyType: "Property type",
    purpose: "Purpose",
    country: "Country",
    region: "Region",
    settlement: "Settlement",
    exactAddress: "Private exact address",
    title: "Bulgarian title",
    description: "Bulgarian description",
    brokerNote:
      "Private broker intake note (optional; never published or sent to Hermes automatically)",
    priceState: "Price status",
    price: "Price in EUR",
    areaState: "Area status",
    area: "Area in m²",
    areaBasis: "Area basis",
    bedroomsState: "Bedroom status",
    bedrooms: "Bedrooms",
    sourceReference: "Source or evidence reference",
    sourceClass: "Source type",
    sourceLanguage: "Language of the source evidence",
  },
  form: {
    errorSummary: "Check the form",
    pending: "Saving…",
    reapply: "Apply reviewed draft to current revision",
    yourValue: "Your draft",
    latestValue: "Current value",
    revision: "Revision",
    reference: "Reference",
    recordedAt: "Recorded at",
    unknown: "We could not confirm the result",
    draftRetained: "Your entered values are retained below. Check the operation before retrying.",
  } satisfies FormCopy,
};
type Copy = typeof en;
const bg: Copy = {
  ...en,
  inventory: "Имоти и обяви",
  create: "Нова обява",
  back: "Към обявите",
  edit: "Работна чернова",
  save: "Запазване на чернова",
  saved: "Черновата е запазена",
  empty: "Няма достъпни обяви за вашата роля.",
  next: "Проверете черновата и създайте отделна версия за преглед, когато е готова.",
  open: "Отваряне на обявата",
  prepare: "Създаване на версия за преглед",
  source: "Български източник",
  review: "Преглед и публикуване",
  scope: "Обхват на прегледа или причина",
  reviewFacts: "Одобряване на фактите",
  submit: "Изпращане за редакционен преглед",
  approve: "Одобряване на изходната версия",
  prepareManifest: "Подготовка за публикуване",
  activate: "Публикуване на одобрения пакет",
  restrict: "Ограничаване във всички канали",
  withdraw: "Сваляне от всички канали",
  confirm: "Прегледах точно тази версия и посочения обхват.",
  noRevision: "Запазете чернова и създайте версия за преглед.",
  noPublication: "Няма активирано публикуване.",
  privateAddress: "Точният адрес е поверителен. Публично се показва само населеното място.",
  draftNotice:
    "Запазването и създаването на версия не одобряват фактите и не публикуват. Публикуваното съдържание остава отделно.",
  factsHint:
    "Запазвайте неизвестните стойности. При противоречащи числа въведете стойностите, разделени с |. Не избирайте стойност без доказателство.",
  blocked:
    "Действието не е завършено. Проверете текущата версия, нужните доказателства и вашия достъп.",
  succeeded: "Действието е записано.",
  operation: "Потвърждение за действие",
  recorded: "Записано",
  pending: "Резултатът още не е потвърден",
  revision: "Версия",
  state: "Състояние",
  location: "Местоположение",
  reference: "Референция",
  purpose: "Цел",
  permissions: "Вашата роля няма право да редактира този запис.",
  labels: {
    propertyType: "Вид имот",
    purpose: "Цел",
    country: "Държава",
    region: "Област",
    settlement: "Населено място",
    exactAddress: "Поверителен точен адрес",
    title: "Заглавие на български",
    description: "Описание на български",
    brokerNote:
      "Частна бележка за въвеждане (по избор; не се публикува или изпраща автоматично към Hermes)",
    priceState: "Състояние на цената",
    price: "Цена в EUR",
    areaState: "Състояние на площта",
    area: "Площ в m²",
    areaBasis: "Вид площ",
    bedroomsState: "Състояние на спалните",
    bedrooms: "Спални",
    sourceReference: "Източник или доказателство",
    sourceClass: "Вид източник",
    sourceLanguage: "Език на източника",
  },
  form: {
    errorSummary: "Проверете формуляра",
    pending: "Запазване…",
    reapply: "Прилагане на прегледаната чернова към текущата версия",
    yourValue: "Вашата чернова",
    latestValue: "Текуща стойност",
    revision: "Версия",
    reference: "Референция",
    recordedAt: "Записано на",
    unknown: "Резултатът не е потвърден",
    draftRetained: "Въведеното е запазено по-долу. Проверете действието преди повторен опит.",
  },
};
const ru: Copy = {
  ...en,
  inventory: "Объекты и объявления",
  create: "Новое объявление",
  back: "К объявлениям",
  edit: "Рабочий черновик",
  save: "Сохранить черновик",
  saved: "Черновик сохранён",
  empty: "Для вашей роли пока нет доступных объявлений.",
  next: "Проверьте черновик, затем создайте отдельную версию для проверки.",
  open: "Открыть объявление",
  prepare: "Создать версию для проверки",
  source: "Болгарский источник",
  review: "Проверка и публикация",
  scope: "Область проверки или причина",
  reviewFacts: "Одобрить факты",
  submit: "Передать на редакционную проверку",
  approve: "Одобрить исходную версию",
  prepareManifest: "Подготовить публикацию",
  activate: "Опубликовать проверенный пакет",
  restrict: "Ограничить во всех каналах",
  withdraw: "Снять со всех каналов",
  confirm: "Я проверил именно эту версию и указанный объём.",
  noRevision: "Сохраните черновик и создайте версию для проверки.",
  noPublication: "Публикаций ещё нет.",
  privateAddress: "Точный адрес закрыт. Публично показывается только населённый пункт.",
  draftNotice:
    "Сохранение черновика и создание версии не одобряют факты и не публикуют. Публичная версия остаётся отдельно.",
  factsHint:
    "Сохраняйте неизвестные значения. Противоречащие числа разделяйте знаком |. Не выбирайте значение без доказательств.",
  blocked: "Действие не завершено. Проверьте текущую версию, доказательства и ваши права.",
  succeeded: "Действие записано.",
  operation: "Подтверждение действия",
  recorded: "Записано",
  pending: "Результат ещё не подтверждён",
  revision: "Версия",
  state: "Статус",
  location: "Местоположение",
  reference: "Референция",
  purpose: "Цель",
  permissions: "Ваша роль не может редактировать эту запись.",
  labels: {
    propertyType: "Вид объекта",
    purpose: "Цель",
    country: "Страна",
    region: "Регион",
    settlement: "Населённый пункт",
    exactAddress: "Закрытый точный адрес",
    title: "Заголовок на болгарском",
    description: "Описание на болгарском",
    brokerNote:
      "Частная заметка для ввода (необязательно; не публикуется и не передаётся Hermes автоматически)",
    priceState: "Статус цены",
    price: "Цена в EUR",
    areaState: "Статус площади",
    area: "Площадь в m²",
    areaBasis: "Вид площади",
    bedroomsState: "Статус спален",
    bedrooms: "Спальни",
    sourceReference: "Источник или доказательство",
    sourceClass: "Вид источника",
    sourceLanguage: "Язык источника",
  },
  form: {
    errorSummary: "Проверьте форму",
    pending: "Сохранение…",
    reapply: "Применить проверенный черновик к текущей версии",
    yourValue: "Ваш черновик",
    latestValue: "Текущее значение",
    revision: "Версия",
    reference: "Референция",
    recordedAt: "Записано",
    unknown: "Результат не подтверждён",
    draftRetained: "Введённые значения сохранены ниже. Проверьте действие перед повтором.",
  },
};
export const inventoryCopy = (locale: string): Copy =>
  locale === "bg" ? bg : locale === "ru" ? ru : en;

const options = {
  known: ["Known", "Известно", "Известно"],
  unknown: ["Unknown", "Неизвестно", "Неизвестно"],
  not_supplied: ["Not supplied", "Непредоставено", "Не предоставлено"],
  not_applicable: ["Not applicable", "Неприложимо", "Неприменимо"],
  withheld: ["Withheld", "Не се разкрива", "Не раскрывается"],
  conflicting: ["Conflicting", "Противоречиво", "Противоречиво"],
  apartment: ["Apartment", "Апартамент", "Квартира"],
  house: ["House", "Къща", "Дом"],
  plot: ["Land", "Парцел", "Участок"],
  commercial: ["Commercial", "Търговски", "Коммерческий"],
  hotel: ["Hotel", "Хотел", "Отель"],
  development: ["Development", "Строителен проект", "Строительный проект"],
  other: ["Other", "Друг", "Другой"],
  sale: ["Sale", "Продажба", "Продажа"],
  long_term_rent: ["Long-term rent", "Дългосрочен наем", "Долгосрочная аренда"],
  living: ["Living area", "Жилищна площ", "Жилая площадь"],
  usable: ["Usable area", "Полезна площ", "Полезная площадь"],
  built: ["Built area", "Застроена площ", "Застроенная площадь"],
  gross_floor: ["Gross floor area", "РЗП", "Общая площадь этажей"],
  total: ["Total area", "Обща площ", "Общая площадь"],
  land: ["Land area", "Площ на терена", "Площадь участка"],
  source_supplied: ["Supplied by source", "Предоставено от източник", "Предоставлено источником"],
  owner_confirmed: ["Confirmed by owner", "Потвърдено от собственик", "Подтверждено собственником"],
  agency_observed: ["Observed by agency", "Установено от агенцията", "Установлено агентством"],
  document_reviewed: ["Document reviewed", "Прегледан документ", "Документ проверен"],
  professionally_reviewed: [
    "Professional review",
    "Професионален преглед",
    "Профессиональная проверка",
  ],
  system_calculated: ["Calculated", "Изчислено", "Рассчитано"],
  legacy_import: ["Legacy import", "Стар импорт", "Прежний импорт"],
} satisfies Record<string, [string, string, string]>;
export function optionLabel(value: string, locale: string) {
  const labels = options[value as keyof typeof options];
  return labels?.[locale === "bg" ? 1 : locale === "ru" ? 2 : 0] ?? value.replaceAll("_", " ");
}
