const en = {
  title: "Seller evidence and availability",
  back: "Back to listing",
  documents: "Documents",
  media: "Photos and media",
  authority: "Review seller authority",
  party: "Contact",
  role: "Role",
  seller: "Seller",
  landlord: "Landlord",
  authorized_representative: "Authorized representative",
  authorityDocument: "Reviewed authority document",
  agreementDocument: "Reviewed brokerage agreement",
  scope: "Evidence checked and scope of review",
  authorityConfirm:
    "I checked this person's authority for this property against the selected evidence.",
  instruction: "Record agreed instructions",
  instructionNotice:
    "Record the actual agreement. The instruction binds the current frozen price and public location precision. This action does not publish a listing.",
  commission: "Agreed commission terms",
  representation: "Representation scope",
  sale: "Sale",
  letting: "Letting",
  sale_and_letting: "Sale and letting",
  agreedAt: "Agreed at (Europe/Sofia)",
  expiresAt: "Expires at (Europe/Sofia, optional)",
  publication: "The agreement permits publication",
  rights: "The agreement grants the stated media usage rights",
  instructionConfirm:
    "I checked these exact instructions and permissions against the selected agreement.",
  missing:
    "First link an inquiry contact and review the relevant property documents. Uploading a file alone does not establish authority or permission.",
  availability: "Confirm current availability",
  evidence: "Confirmation source and date",
  readiness: "Publication prerequisites",
  yes: "Recorded",
  no: "Required",
  factual: "Current factual review",
  editorial: "Current editorial approval",
  agreement: "Seller permission for these terms",
  photos: "Reviewed, permitted media",
  language: "Language review for this source",
  claims: "Review of regulated claims",
  choose: "Choose…",
  instructions: "Recorded instructions",
  source: "Frozen review candidate",
  sourceHint:
    "Review this candidate, including its sources. Edits to the working draft do not change it.",
};
type Copy = typeof en;
const bg: Copy = {
  ...en,
  title: "Документи на продавача и наличност",
  back: "Към обявата",
  documents: "Документи",
  media: "Снимки и медия",
  authority: "Преглед на представителната власт",
  party: "Контакт",
  role: "Роля",
  seller: "Продавач",
  landlord: "Наемодател",
  authorized_representative: "Упълномощен представител",
  authorityDocument: "Прегледан документ за представителна власт",
  agreementDocument: "Прегледан посреднически договор",
  scope: "Проверени доказателства и обхват",
  authorityConfirm:
    "Проверих представителната власт на това лице за този имот по избрания документ.",
  instruction: "Записване на договорените условия",
  instructionNotice:
    "Запишете действително договореното. Указанията се свързват с цената и публичната точност на местоположението в текущата версия за преглед. Това действие не публикува обявата.",
  commission: "Договорена комисиона",
  representation: "Обхват на представителство",
  sale: "Продажба",
  letting: "Отдаване под наем",
  sale_and_letting: "Продажба и отдаване",
  agreedAt: "Договорено на (Europe/Sofia)",
  expiresAt: "Валидно до (Europe/Sofia, по избор)",
  publication: "Договорът разрешава публикуване",
  rights: "Договорът предоставя посочените права за ползване на медията",
  instructionConfirm: "Проверих точните условия и разрешения по избрания договор.",
  missing:
    "Първо свържете контакт от запитване и прегледайте документите за имота. Самото качване на файл не доказва представителна власт или разрешение.",
  availability: "Потвърждаване на актуалната наличност",
  evidence: "Източник и дата на потвърждението",
  readiness: "Условия за публикуване",
  yes: "Записано",
  no: "Необходимо",
  factual: "Актуален преглед на фактите",
  editorial: "Актуално редакционно одобрение",
  agreement: "Разрешение за тези условия",
  photos: "Прегледана медия с права",
  language: "Езиков преглед за този източник",
  claims: "Преглед на регулирани твърдения",
  choose: "Изберете…",
  instructions: "Записани указания",
  source: "Фиксирана версия за преглед",
  sourceHint:
    "Прегледайте тази версия и източниците ѝ. Редакциите на работната чернова не я променят.",
};
const ru: Copy = {
  ...en,
  title: "Документы продавца и доступность",
  back: "К объявлению",
  documents: "Документы",
  media: "Фото и медиа",
  authority: "Проверка полномочий продавца",
  party: "Контакт",
  role: "Роль",
  seller: "Продавец",
  landlord: "Арендодатель",
  authorized_representative: "Уполномоченный представитель",
  authorityDocument: "Проверенный документ о полномочиях",
  agreementDocument: "Проверенный договор с агентством",
  scope: "Проверенные доказательства и объём проверки",
  authorityConfirm:
    "Я проверил полномочия этого лица по данному объекту на основании выбранного документа.",
  instruction: "Записать согласованные условия",
  instructionNotice:
    "Запишите фактические условия договора. Они привязываются к цене и точности публичного местоположения в текущей версии. Это действие не публикует объявление.",
  commission: "Согласованная комиссия",
  representation: "Объём представительства",
  sale: "Продажа",
  letting: "Аренда",
  sale_and_letting: "Продажа и аренда",
  agreedAt: "Согласовано (Europe/Sofia)",
  expiresAt: "Действует до (Europe/Sofia, необязательно)",
  publication: "Договор разрешает публикацию",
  rights: "Договор предоставляет указанные права на использование медиа",
  instructionConfirm: "Я сверил точные условия и разрешения с выбранным договором.",
  missing:
    "Сначала свяжите контакт из заявки и проверьте документы объекта. Загрузка файла сама по себе не подтверждает полномочия или разрешение.",
  availability: "Подтвердить актуальную доступность",
  evidence: "Источник и дата подтверждения",
  readiness: "Условия публикации",
  yes: "Записано",
  no: "Требуется",
  factual: "Актуальная проверка фактов",
  editorial: "Актуальное редакционное одобрение",
  agreement: "Разрешение на эти условия",
  photos: "Проверенные медиа с правами",
  language: "Языковая проверка этой версии",
  claims: "Проверка регулируемых утверждений",
  choose: "Выберите…",
  instructions: "Записанные указания",
  source: "Зафиксированная версия для проверки",
  sourceHint: "Проверьте эту версию и её источники. Правки рабочей версии её не меняют.",
};
export function evidenceCopy(locale: string): Copy {
  return locale === "bg" ? bg : locale === "ru" ? ru : en;
}
